INSERT INTO CODE_TYPE (NAME, LABEL, SITE_NAME) VALUES ('projectCode','Project Code',null);
INSERT INTO CODE_TYPE (NAME, LABEL, SITE_NAME) VALUES ('motivationCode','Motivation Code',null);
INSERT INTO CODE_TYPE (NAME, LABEL, SITE_NAME) VALUES ('commitmentCode','Commitment Code',null);

INSERT INTO CODE SET CODE_VALUE='000001',CODE_DESCRIPTION='Default Project Code',CODE_TYPE_ID='1';
INSERT INTO CODE SET CODE_VALUE='000002',CODE_DESCRIPTION='Default Motivation Code',CODE_TYPE_ID='2';
INSERT INTO CODE SET CODE_VALUE='000003',CODE_DESCRIPTION='Default Commitment Code',CODE_TYPE_ID='3';

