-- Make sure keys for out-of-box data start numbering at 1000000

INSERT INTO SECTION_DEFINITION (SECTION_DEFINITION_ID, PAGE_TYPE, SECTION_NAME, DEFAULT_LABEL, SECTION_ORDER, LAYOUT_TYPE, ROLE) VALUES (1000000, '', '', ' ', 0, '', '');
INSERT INTO FIELD_DEFINITION (FIELD_DEFINITION_ID, ENTITY_TYPE, FIELD_NAME, DEFAULT_LABEL, FIELD_TYPE) VALUES ('', '', '', '', '');
INSERT INTO SECTION_FIELD (SECTION_FIELD_ID, SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES (1000000, 1000000, '', 0);
INSERT INTO QUERY_LOOKUP (QUERY_LOOKUP_ID, ENTITY_TYPE, SQL_WHERE, FIELD_DEFINITION_ID, SECTION_NAME, SITE_NAME) VALUES (1000000, '','', '', '', null);
INSERT INTO QUERY_LOOKUP_PARAM (QUERY_LOOKUP_PARAM_ID, PARAM_NAME, QUERY_LOOKUP_ID) VALUES (1000000, '', 1000000);
INSERT INTO PICKLIST (PICKLIST_ID, PICKLIST_NAME_ID, PICKLIST_NAME, PICKLIST_DESC) VALUES (1000000, '', '', '');
INSERT INTO PICKLIST_ITEM (PICKLIST_ITEM_ID, PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, REFERENCE_VALUE, ITEM_ORDER) VALUES (1000000, 1000000, '', '', '', 0);

