-- Override a section name

INSERT INTO MESSAGE_RESOURCE (LANGUAGE_ABBREVIATION, MESSAGE_RESOURCE_TYPE, MESSAGE_KEY, MESSAGE_VALUE, SITE_NAME) VALUES ('en', 'SECTION_HEADER', 'person.contactInfo', 'Hakeem Olajuwaon', 'CrederaDev');

-- Override a field label

INSERT INTO MESSAGE_RESOURCE (LANGUAGE_ABBREVIATION, MESSAGE_RESOURCE_TYPE, MESSAGE_KEY, MESSAGE_VALUE, SITE_NAME) VALUES ('en', 'FIELD_LABEL', 'person.idReadOnly', 'Clyde Drexler', 'CrederaDev');

-- Override a picklist display value

INSERT INTO MESSAGE_RESOURCE (LANGUAGE_ABBREVIATION, MESSAGE_RESOURCE_TYPE, MESSAGE_KEY, MESSAGE_VALUE, SITE_NAME) VALUES ('en', 'PICKLIST_VALUE', 'US', 'Otis Thorpe', 'CrederaDev');

INSERT INTO FIELD_REQUIRED (SITE_NAME, SECTION_NAME, FIELD_DEFINITION_ID, REQUIRED) VALUES ('CrederaDev', 'person.contactInfo', 'person.lastName',  true);