package com.mpower.domain

import com.mpower.domain.Person;
import com.mpower.service.PersonService;
import com.mpower.service.GiftService;
import com.mpower.domain.Gift;
import java.util.Calendar;
import java.util.Date;
import com.mpower.service.rule.ScheduledMaintenance;

expander Site1Language.dsl

global org.springframework.context.ApplicationContext applicationContext;

rule "Analyze Lapsed Donor"
	when
		Scheduled maintenance needs to be done	
	then
		Flag the people who have not made a donation in the past 12 "months"
		>System.out.println("hia");
end

function Date getBeginDate(int number, String timeUnit) {
	Calendar cal = Calendar.getInstance();
	StringBuilder args = new StringBuilder(timeUnit.toUpperCase());
	if (args.toString().equals("MONTHS") || args.toString().equals("YEARS")) {
		args.deleteCharAt(args.length()-1);
	}
	if (args.toString().equals("MONTH")) {
		cal.add(Calendar.MONTH, -(number));
	}
	if (args.toString().equals("YEAR")) {
		cal.add(Calendar.YEAR, -(number));
	}
		return cal.getTime();
}

function Date getCurrentDate() {
	Calendar cal = Calendar.getInstance();
	return cal.getTime();
}