package com.mpower.type;

public enum FieldType {
    DATE,
    DATE_DISPLAY,
    TEXT,
    READ_ONLY_TEXT,
    LOOKUP,
    CODE,
    PICKLIST,
    PICKLIST_DISPLAY,
    MULTI_PICKLIST,
    MULTI_PICKLIST_DISPLAY,
    PREFERRED_PHONE_TYPES,
    DATE_TIME,
    ADDRESS,
    PHONE,
    LONG_TEXT,
    NUMBER,
    SPACER,
    CC_EXPIRATION,
    CC_EXPIRATION_DISPLAY,
    CHECKBOX,
    PAYMENT_SOURCE_PICKLIST,
    ADDRESS_PICKLIST,
    PHONE_PICKLIST,
    QUERY_LOOKUP,
    MULTI_QUERY_LOOKUP
}