<PC3FreightAmt>[% PC3FreightAmt= %]</PC3FreightAmt>
<PC3DutyAmt>[% PC3DutyAmt= %]</PC3DutyAmt>
<PC3DestCountryCd>[% PC3DestCountryCd= %]</PC3DestCountryCd>
<PC3ShipFromZip>[% PC3ShipFromZip= %]</PC3ShipFromZip>
<PC3DiscAmt>[% PC3DiscAmt= %]</PC3DiscAmt>
<PC3VATtaxAmt>[% PC3VATtaxAmt= %]</PC3VATtaxAmt>
<PC3VATtaxRate>[% PC3VATtaxRate= %]</PC3VATtaxRate>
<PC3AltTaxInd>[% PC3AltTaxInd= %]</PC3AltTaxInd>
<PC3AltTaxAmt>[% PC3AltTaxAmt= %]</PC3AltTaxAmt>
<PC3LineItemCount>[% PC3LineItemCount %]</PC3LineItemCount>
<PC3LineItemArray>
	[# PC3LineItems #]
</PC3LineItemArray>