/*
V5 Schema changes
*********************************************************************
*/

DROP TABLE IF EXISTS `ENTITY_SEARCH`;

CREATE TABLE `ENTITY_SEARCH` (
`ENTITY_TYPE` varchar(255) NOT NULL,
`ENTITY_ID` bigint(20) NOT NULL,
`SITE_NAME` varchar(255) NOT NULL,
`SEARCH_TEXT` TEXT NOT NULL,
INDEX `ENTITY_SEARCH` (`ENTITY_ID`,`ENTITY_TYPE`),
FULLTEXT INDEX (`SEARCH_TEXT`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;



ALTER TABLE `CUSTOM_FIELD`
    ADD KEY `IDX_CUSTOM_FIELD_FIELD_VALUE`(`FIELD_VALUE`(10));
    
ALTER TABLE `SECTION_FIELD`
    ADD COLUMN (`TAB_INDEX` int(11) default 0);

ALTER TABLE `PICKLIST_ITEM`
    ADD COLUMN (`DETAIL` varchar(255));

