/*
SQLyog Job Agent Version 8.14 n2 Copyright(c) Webyog Softworks Pvt. Ltd. All Rights Reserved.

MySQL - 5.1.35-community
*********************************************************************
*/
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/* SYNC DB : company1 */
SET AUTOCOMMIT = 0;


UPDATE VERSION SET SCHEMA_MAJOR_VERSION = 3 WHERE COMPONENT_ID = 'ORANGE' AND COMPONENT_DESC = 'Orange Leap';


INSERT INTO FIELD_DEFINITION (FIELD_DEFINITION_ID, ENTITY_TYPE, FIELD_NAME, DEFAULT_LABEL, FIELD_TYPE) VALUES ('adjustedGift.id', 'adjustedGift', 'id', 'Reference Number', 'TEXT');


UPDATE `SECTION_DEFINITION` SET `DEFAULT_LABEL`='All Gifts', `LAYOUT_TYPE`='TREE_GRID' WHERE (`SECTION_NAME`='giftList.resultsInfo' AND `PAGE_TYPE`='giftList') ;



UPDATE `SECTION_FIELD` SET `FIELD_ORDER`='100'  WHERE (`SECTION_DEFINITION_ID` = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='giftList.resultsInfo' AND PAGE_TYPE='giftList') AND `FIELD_DEFINITION_ID` = 'gift.id' AND `SECONDARY_FIELD_DEFINITION_ID` IS NULL);

UPDATE `SECTION_FIELD` SET `FIELD_DEFINITION_ID` = 'gift.donationDate'  WHERE (`SECTION_DEFINITION_ID` = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='giftList.resultsInfo' AND PAGE_TYPE='giftList') AND `FIELD_DEFINITION_ID` = 'gift.transactionDate' AND `SECONDARY_FIELD_DEFINITION_ID` IS NULL);

UPDATE `SECTION_FIELD` SET `FIELD_ORDER`='2000'  WHERE (`SECTION_DEFINITION_ID` = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='giftList.resultsInfo' AND PAGE_TYPE='giftList') AND `FIELD_DEFINITION_ID` = 'gift.amount' AND `SECONDARY_FIELD_DEFINITION_ID` IS NULL);

UPDATE `SECTION_FIELD` SET `FIELD_ORDER`='8000'  WHERE (`SECTION_DEFINITION_ID` = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='giftList.resultsInfo' AND PAGE_TYPE='giftList') AND `FIELD_DEFINITION_ID` = 'gift.comments' AND `SECONDARY_FIELD_DEFINITION_ID` IS NULL);

UPDATE `SECTION_FIELD` SET `FIELD_ORDER`='6000'  WHERE (`SECTION_DEFINITION_ID` = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='giftList.resultsInfo' AND PAGE_TYPE='giftList') AND `FIELD_DEFINITION_ID` = 'gift.authCodeReadOnly' AND `SECONDARY_FIELD_DEFINITION_ID` IS NULL);

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER) SELECT SECTION_DEFINITION_ID, 'gift.currencyCode', 3000 FROM SECTION_DEFINITION WHERE SECTION_NAME='giftList.resultsInfo' AND PAGE_TYPE='giftList';

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER) SELECT SECTION_DEFINITION_ID, 'gift.paymentType', 4000 FROM SECTION_DEFINITION WHERE SECTION_NAME='giftList.resultsInfo' AND PAGE_TYPE='giftList';

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER) SELECT SECTION_DEFINITION_ID, 'gift.paymentStatusReadOnly', 5000 FROM SECTION_DEFINITION WHERE SECTION_NAME='giftList.resultsInfo' AND PAGE_TYPE='giftList';

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER) SELECT SECTION_DEFINITION_ID, 'gift.txRefNumReadOnly', 7000 FROM SECTION_DEFINITION WHERE SECTION_NAME='giftList.resultsInfo' AND PAGE_TYPE='giftList';




SET @Next_ID=(SELECT MAX(SECTION_DEFINITION_ID)+1000 FROM SECTION_DEFINITION);

INSERT INTO SECTION_DEFINITION (SECTION_DEFINITION_ID, PAGE_TYPE, SECTION_NAME, DEFAULT_LABEL, SECTION_ORDER, LAYOUT_TYPE, ROLE) VALUES (@Next_ID, 'adjustedGiftList', 'adjustedGiftList.resultsInfo', ' ', 2, 'TREE_GRID_HIDDEN_ROW', 'ROLE_USER');



INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES (@Next_ID, 'adjustedGift.id', 100);

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES (@Next_ID, 'adjustedGift.transactionDate', 1000);

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES (@Next_ID, 'adjustedGift.adjustedAmount', 2000);

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES (@Next_ID, 'adjustedGift.currencyCodeReadOnly', 3000);

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES (@Next_ID, 'adjustedGift.paymentType', 4000);

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES (@Next_ID, 'adjustedGift.paymentStatusReadOnly', 5000);

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES (@Next_ID, 'adjustedGift.authCodeReadOnly', 6000);

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES (@Next_ID, 'adjustedGift.txRefNumReadOnly', 7000);

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES (@Next_ID, 'adjustedGift.comments', 8000);



/* Constituent search results */
UPDATE `SECTION_DEFINITION` SET `LAYOUT_TYPE`='SEARCH_GRID' WHERE (`SECTION_NAME`='constituentSearchResults.resultsInfo' AND `PAGE_TYPE`='constituentSearchResults') ;

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER)
SELECT SECTION_DEFINITION_ID, 'constituent.id', 100 FROM SECTION_DEFINITION WHERE SECTION_NAME='constituentSearchResults.resultsInfo' AND PAGE_TYPE='constituentSearchResults';


/* Gift search */
UPDATE `SECTION_FIELD` SET `FIELD_ORDER`='100'  WHERE (`SECTION_DEFINITION_ID` = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='giftSearch.searchInfo' AND PAGE_TYPE='giftSearch')
AND `FIELD_DEFINITION_ID` = 'gift.id' AND `SECONDARY_FIELD_DEFINITION_ID` IS NULL);

UPDATE `SECTION_FIELD` SET `FIELD_ORDER`='1500'  WHERE (`SECTION_DEFINITION_ID` = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='giftSearch.searchInfo' AND PAGE_TYPE='giftSearch')
AND `FIELD_DEFINITION_ID` = 'gift.constituent.organizationName' AND `SECONDARY_FIELD_DEFINITION_ID` = 'constituent.organizationName');

DELETE FROM SECTION_FIELD WHERE FIELD_DEFINITION_ID = 'gift.constituent.primaryAddress' AND SECONDARY_FIELD_DEFINITION_ID = 'address.postalCode'
AND SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='giftSearch.searchInfo' AND PAGE_TYPE='giftSearch');

/* Gift search results */
INSERT INTO FIELD_DEFINITION (FIELD_DEFINITION_ID, ENTITY_TYPE, FIELD_NAME, DEFAULT_LABEL, FIELD_TYPE) VALUES ('gift.constituent.id', 'gift', 'constituent', 'Account Id', 'READ_ONLY_TEXT');

UPDATE `SECTION_DEFINITION` SET `LAYOUT_TYPE`='SEARCH_GRID' WHERE (`SECTION_NAME`='giftSearchResults.resultsInfo' AND `PAGE_TYPE`='giftSearchResults') ;

UPDATE `SECTION_FIELD` SET `FIELD_ORDER`='100'  WHERE (`SECTION_DEFINITION_ID` = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='giftSearchResults.resultsInfo' AND PAGE_TYPE='giftSearchResults')
AND `FIELD_DEFINITION_ID` = 'gift.id' AND `SECONDARY_FIELD_DEFINITION_ID` IS NULL);

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, SECONDARY_FIELD_DEFINITION_ID, FIELD_ORDER)
SELECT SECTION_DEFINITION_ID, 'gift.constituent.id', 'constituent.id', 200 FROM SECTION_DEFINITION WHERE SECTION_NAME='giftSearchResults.resultsInfo' AND PAGE_TYPE='giftSearchResults';

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, SECONDARY_FIELD_DEFINITION_ID, FIELD_ORDER) 
SELECT SECTION_DEFINITION_ID, 'gift.constituent.accountNumber', 'constituent.accountNumber', 2000 FROM SECTION_DEFINITION WHERE SECTION_NAME='giftSearchResults.resultsInfo' AND PAGE_TYPE='giftSearchResults';

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, SECONDARY_FIELD_DEFINITION_ID, FIELD_ORDER)
SELECT SECTION_DEFINITION_ID, 'gift.constituent.organizationName', 'constituent.organizationName', 2500 FROM SECTION_DEFINITION WHERE SECTION_NAME='giftSearchResults.resultsInfo' AND PAGE_TYPE='giftSearchResults';

UPDATE `SECTION_FIELD` SET `FIELD_DEFINITION_ID`='gift.constituent.lastName', SECONDARY_FIELD_DEFINITION_ID='constituent.lastName'
WHERE (`SECTION_DEFINITION_ID` = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='giftSearchResults.resultsInfo' AND PAGE_TYPE='giftSearchResults')
AND `FIELD_DEFINITION_ID` = 'gift.constituentLastName' AND `SECONDARY_FIELD_DEFINITION_ID` IS NULL);

UPDATE `SECTION_FIELD` SET `FIELD_DEFINITION_ID`='gift.constituent.firstName', SECONDARY_FIELD_DEFINITION_ID='constituent.firstName' 
WHERE (`SECTION_DEFINITION_ID` = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='giftSearchResults.resultsInfo' AND PAGE_TYPE='giftSearchResults')
AND `FIELD_DEFINITION_ID` = 'gift.constituentFirstName' AND `SECONDARY_FIELD_DEFINITION_ID` IS NULL);


/* Tangerine-1272 */
UPDATE FIELD_DEFINITION set FIELD_TYPE = 'PICKLIST_DISPLAY' WHERE FIELD_DEFINITION_ID = 'recurringGift.frequencyReadOnly';


/* Tangerine-1237 */
INSERT INTO PICKLIST (PICKLIST_ID, PICKLIST_NAME_ID, PICKLIST_NAME, PICKLIST_DESC) VALUES (1001004, 'screenDefinitionRole', 'screenDefinitionRole', 'Screen Definition Role');
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (1001004, 'ROLE_SUPER_ADMIN', 'ROLE_SUPER_ADMIN', 1);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (1001004, 'ROLE_ADMIN', 'ROLE_ADMIN', 2);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (1001004, 'ROLE_USER', 'ROLE_USER', 3);


COMMIT;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

