/*
SQLyog Job Agent Version 8.14 n2 Copyright(c) Webyog Softworks Pvt. Ltd. All Rights Reserved.

MySQL - 5.1.35-community
*********************************************************************
*/
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/* SYNC DB : company1 */
SET AUTOCOMMIT = 0;


UPDATE VERSION SET SCHEMA_MAJOR_VERSION = 3 WHERE COMPONENT_ID = 'ORANGE' AND COMPONENT_DESC = 'Orange Leap';



/* Recurring gift view changes */
UPDATE SECTION_DEFINITION SET LAYOUT_TYPE = 'DISTRIBUTION_LINE_GRID' WHERE PAGE_TYPE = 'recurringGiftView' and SECTION_NAME = 'recurringGift.distribution';

UPDATE SECTION_FIELD set FIELD_DEFINITION_ID = 'recurringGift.endDate' WHERE FIELD_DEFINITION_ID = 'recurringGift.endDateReadOnly'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGiftView.info' AND PAGE_TYPE='recurringGiftView');



UPDATE SECTION_FIELD set FIELD_DEFINITION_ID = 'recurringGift.paymentType' WHERE FIELD_DEFINITION_ID = 'recurringGift.paymentTypeReadOnly'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.payment' AND PAGE_TYPE='recurringGiftView');

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, SECONDARY_FIELD_DEFINITION_ID, FIELD_ORDER)
SELECT SECTION_DEFINITION_ID, 'recurringGift.paymentSource.id', 'paymentSource.id', 12500 FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.payment' AND PAGE_TYPE='recurringGiftView';

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, SECONDARY_FIELD_DEFINITION_ID, FIELD_ORDER)
SELECT SECTION_DEFINITION_ID, 'recurringGift.address.id', 'address.id', 13000 FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.payment' AND PAGE_TYPE='recurringGiftView';

UPDATE SECTION_FIELD set FIELD_DEFINITION_ID = 'recurringGift.address.customFieldMap[addressType]', SECONDARY_FIELD_DEFINITION_ID='address.customFieldMap[addressType]'
WHERE FIELD_DEFINITION_ID = 'recurringGift.address.customFieldMap[addressTypeReadOnly]' and SECONDARY_FIELD_DEFINITION_ID='address.customFieldMap[addressTypeReadOnly]'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.payment' AND PAGE_TYPE='recurringGiftView');

UPDATE SECTION_FIELD set FIELD_DEFINITION_ID = 'recurringGift.address.addressLine1', SECONDARY_FIELD_DEFINITION_ID='address.addressLine1'
WHERE FIELD_DEFINITION_ID = 'recurringGift.address.addressLine1ReadOnly' and SECONDARY_FIELD_DEFINITION_ID='address.addressLine1ReadOnly'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.payment' AND PAGE_TYPE='recurringGiftView');

UPDATE SECTION_FIELD set FIELD_DEFINITION_ID = 'recurringGift.address.addressLine2', SECONDARY_FIELD_DEFINITION_ID='address.addressLine2'
WHERE FIELD_DEFINITION_ID = 'recurringGift.address.addressLine2ReadOnly' and SECONDARY_FIELD_DEFINITION_ID='address.addressLine2ReadOnly'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.payment' AND PAGE_TYPE='recurringGiftView');

UPDATE SECTION_FIELD set FIELD_DEFINITION_ID = 'recurringGift.address.addressLine3', SECONDARY_FIELD_DEFINITION_ID='address.addressLine3'
WHERE FIELD_DEFINITION_ID = 'recurringGift.address.addressLine3ReadOnly' and SECONDARY_FIELD_DEFINITION_ID='address.addressLine3ReadOnly'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.payment' AND PAGE_TYPE='recurringGiftView');

UPDATE SECTION_FIELD set FIELD_DEFINITION_ID = 'recurringGift.address.city', SECONDARY_FIELD_DEFINITION_ID='address.city'
WHERE FIELD_DEFINITION_ID = 'recurringGift.address.cityReadOnly' and SECONDARY_FIELD_DEFINITION_ID='address.cityReadOnly'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.payment' AND PAGE_TYPE='recurringGiftView');

UPDATE SECTION_FIELD set FIELD_DEFINITION_ID = 'recurringGift.address.stateProvince', SECONDARY_FIELD_DEFINITION_ID='address.stateProvince'
WHERE FIELD_DEFINITION_ID = 'recurringGift.address.stateProvinceReadOnly' and SECONDARY_FIELD_DEFINITION_ID='address.stateProvinceReadOnly'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.payment' AND PAGE_TYPE='recurringGiftView');

UPDATE SECTION_FIELD set FIELD_DEFINITION_ID = 'recurringGift.address.postalCode', SECONDARY_FIELD_DEFINITION_ID='address.postalCode'
WHERE FIELD_DEFINITION_ID = 'recurringGift.address.postalCodeReadOnly' and SECONDARY_FIELD_DEFINITION_ID='address.postalCodeReadOnly'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.payment' AND PAGE_TYPE='recurringGiftView');

UPDATE SECTION_FIELD set FIELD_DEFINITION_ID = 'recurringGift.address.country', SECONDARY_FIELD_DEFINITION_ID='address.country'
WHERE FIELD_DEFINITION_ID = 'recurringGift.address.countryReadOnly' and SECONDARY_FIELD_DEFINITION_ID='address.countryReadOnly'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.payment' AND PAGE_TYPE='recurringGiftView');

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, SECONDARY_FIELD_DEFINITION_ID, FIELD_ORDER)
SELECT SECTION_DEFINITION_ID, 'recurringGift.phone.id', 'phone.id', 20500 FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.payment' AND PAGE_TYPE='recurringGiftView';

UPDATE SECTION_FIELD set FIELD_DEFINITION_ID = 'recurringGift.phone.customFieldMap[phoneType]', SECONDARY_FIELD_DEFINITION_ID='phone.customFieldMap[phoneType]'
WHERE FIELD_DEFINITION_ID = 'recurringGift.phone.customFieldMap[phoneTypeReadOnly]' and SECONDARY_FIELD_DEFINITION_ID='phone.customFieldMap[phoneTypeReadOnly]'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.payment' AND PAGE_TYPE='recurringGiftView');

UPDATE SECTION_FIELD set FIELD_DEFINITION_ID = 'recurringGift.phone.number', SECONDARY_FIELD_DEFINITION_ID='phone.number'
WHERE FIELD_DEFINITION_ID = 'recurringGift.phone.numberReadOnly' and SECONDARY_FIELD_DEFINITION_ID='phone.numberReadOnly'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.payment' AND PAGE_TYPE='recurringGiftView');

UPDATE SECTION_FIELD set FIELD_ORDER = 5000
WHERE FIELD_DEFINITION_ID = 'recurringGift.paymentSource.creditCardHolderNameReadOnly' and SECONDARY_FIELD_DEFINITION_ID='paymentSource.creditCardHolderNameReadOnly'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.creditCard' AND PAGE_TYPE='recurringGiftView');

UPDATE SECTION_FIELD set FIELD_ORDER = 6000
WHERE FIELD_DEFINITION_ID = 'recurringGift.paymentSource.creditCardTypeReadOnly' and SECONDARY_FIELD_DEFINITION_ID='paymentSource.creditCardTypeReadOnly'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.creditCard' AND PAGE_TYPE='recurringGiftView');

UPDATE SECTION_FIELD set FIELD_ORDER = 7000
WHERE FIELD_DEFINITION_ID = 'recurringGift.paymentSource.creditCardNumberReadOnly' and SECONDARY_FIELD_DEFINITION_ID='paymentSource.creditCardNumberReadOnly'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.creditCard' AND PAGE_TYPE='recurringGiftView');

UPDATE SECTION_FIELD set FIELD_ORDER = 8000
WHERE FIELD_DEFINITION_ID = 'recurringGift.paymentSource.creditCardExpirationDisplay' and SECONDARY_FIELD_DEFINITION_ID='paymentSource.creditCardExpirationDisplay'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.creditCard' AND PAGE_TYPE='recurringGiftView');

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, SECONDARY_FIELD_DEFINITION_ID, FIELD_ORDER)
SELECT SECTION_DEFINITION_ID, 'recurringGift.paymentSource.creditCardHolderName', 'paymentSource.creditCardHolderName', 1000 FROM SECTION_DEFINITION
WHERE SECTION_NAME='recurringGift.creditCard' AND PAGE_TYPE='recurringGiftView';

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, SECONDARY_FIELD_DEFINITION_ID, FIELD_ORDER)
SELECT SECTION_DEFINITION_ID, 'recurringGift.paymentSource.creditCardType', 'paymentSource.creditCardType', 2000 FROM SECTION_DEFINITION
WHERE SECTION_NAME='recurringGift.creditCard' AND PAGE_TYPE='recurringGiftView';

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, SECONDARY_FIELD_DEFINITION_ID, FIELD_ORDER)
SELECT SECTION_DEFINITION_ID, 'recurringGift.paymentSource.creditCardNumber', 'paymentSource.creditCardNumber', 3000 FROM SECTION_DEFINITION
WHERE SECTION_NAME='recurringGift.creditCard' AND PAGE_TYPE='recurringGiftView';

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, SECONDARY_FIELD_DEFINITION_ID, FIELD_ORDER)
SELECT SECTION_DEFINITION_ID, 'recurringGift.paymentSource.creditCardExpiration', 'paymentSource.creditCardExpiration', 4000 FROM SECTION_DEFINITION
WHERE SECTION_NAME='recurringGift.creditCard' AND PAGE_TYPE='recurringGiftView';

UPDATE SECTION_FIELD set FIELD_ORDER = 4000
WHERE FIELD_DEFINITION_ID = 'recurringGift.paymentSource.achHolderNameReadOnly' and SECONDARY_FIELD_DEFINITION_ID='paymentSource.achHolderNameReadOnly'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.ach' AND PAGE_TYPE='recurringGiftView');

UPDATE SECTION_FIELD set FIELD_ORDER = 5000
WHERE FIELD_DEFINITION_ID = 'recurringGift.paymentSource.achRoutingNumberReadOnly' and SECONDARY_FIELD_DEFINITION_ID='paymentSource.achRoutingNumberReadOnly'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.ach' AND PAGE_TYPE='recurringGiftView');

UPDATE SECTION_FIELD set FIELD_ORDER = 6000
WHERE FIELD_DEFINITION_ID = 'recurringGift.paymentSource.achAccountNumberReadOnly' and SECONDARY_FIELD_DEFINITION_ID='paymentSource.achAccountNumberReadOnly'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.ach' AND PAGE_TYPE='recurringGiftView');

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, SECONDARY_FIELD_DEFINITION_ID, FIELD_ORDER)
SELECT SECTION_DEFINITION_ID, 'recurringGift.paymentSource.achHolderName', 'paymentSource.achHolderName', 1000 FROM SECTION_DEFINITION
WHERE SECTION_NAME='recurringGift.ach' AND PAGE_TYPE='recurringGiftView';

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, SECONDARY_FIELD_DEFINITION_ID, FIELD_ORDER)
SELECT SECTION_DEFINITION_ID, 'recurringGift.paymentSource.achRoutingNumber', 'paymentSource.achRoutingNumber', 2000 FROM SECTION_DEFINITION
WHERE SECTION_NAME='recurringGift.ach' AND PAGE_TYPE='recurringGiftView';

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, SECONDARY_FIELD_DEFINITION_ID, FIELD_ORDER)
SELECT SECTION_DEFINITION_ID, 'recurringGift.paymentSource.achAccountNumber', 'paymentSource.achAccountNumber', 3000 FROM SECTION_DEFINITION
WHERE SECTION_NAME='recurringGift.ach' AND PAGE_TYPE='recurringGiftView';




UPDATE SECTION_FIELD set FIELD_DEFINITION_ID = 'recurringGift.distributionLines.amount', SECONDARY_FIELD_DEFINITION_ID='distributionLines.amount'
WHERE FIELD_DEFINITION_ID = 'recurringGift.distributionLines.amountReadOnly' and SECONDARY_FIELD_DEFINITION_ID='distributionLines.amountReadOnly'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.distribution' AND PAGE_TYPE='recurringGiftView');

UPDATE SECTION_FIELD set FIELD_DEFINITION_ID = 'recurringGift.distributionLines.percentage', SECONDARY_FIELD_DEFINITION_ID='distributionLines.percentage'
WHERE FIELD_DEFINITION_ID = 'recurringGift.distributionLines.percentageReadOnly' and SECONDARY_FIELD_DEFINITION_ID='distributionLines.percentageReadOnly'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.distribution' AND PAGE_TYPE='recurringGiftView');

UPDATE SECTION_FIELD set FIELD_DEFINITION_ID = 'recurringGift.distributionLines.projectCode', SECONDARY_FIELD_DEFINITION_ID='distributionLines.projectCode'
WHERE FIELD_DEFINITION_ID = 'recurringGift.distributionLines.projectCodeReadOnly' and SECONDARY_FIELD_DEFINITION_ID='distributionLines.projectCodeReadOnly'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.distribution' AND PAGE_TYPE='recurringGiftView');

UPDATE SECTION_FIELD set FIELD_DEFINITION_ID = 'recurringGift.distributionLines.motivationCode', SECONDARY_FIELD_DEFINITION_ID='distributionLines.motivationCode'
WHERE FIELD_DEFINITION_ID = 'recurringGift.distributionLines.motivationCodeReadOnly' and SECONDARY_FIELD_DEFINITION_ID='distributionLines.motivationCodeReadOnly'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.distribution' AND PAGE_TYPE='recurringGiftView');

UPDATE SECTION_FIELD set FIELD_DEFINITION_ID = 'recurringGift.distributionLines.other_motivationCode', SECONDARY_FIELD_DEFINITION_ID='distributionLines.other_motivationCode'
WHERE FIELD_DEFINITION_ID = 'recurringGift.distributionLines.other_motivationCodeReadOnly' and SECONDARY_FIELD_DEFINITION_ID='distributionLines.other_motivationCodeReadOnly'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.distribution' AND PAGE_TYPE='recurringGiftView');

UPDATE SECTION_FIELD set FIELD_DEFINITION_ID = 'recurringGift.distributionLines.customFieldMap[reference]', SECONDARY_FIELD_DEFINITION_ID='distributionLines.customFieldMap[reference]'
WHERE FIELD_DEFINITION_ID = 'recurringGift.distributionLines.customFieldMap[referenceReadOnly]' and SECONDARY_FIELD_DEFINITION_ID='distributionLines.customFieldMap[referenceReadOnly]'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.distribution' AND PAGE_TYPE='recurringGiftView');

UPDATE SECTION_FIELD set FIELD_DEFINITION_ID = 'recurringGift.distributionLines.customFieldMap[other_reference]', SECONDARY_FIELD_DEFINITION_ID='distributionLines.customFieldMap[other_reference]'
WHERE FIELD_DEFINITION_ID = 'recurringGift.distributionLines.customFieldMap[other_referenceReadOnly]' and SECONDARY_FIELD_DEFINITION_ID='distributionLines.customFieldMap[other_referenceReadOnly]'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.distribution' AND PAGE_TYPE='recurringGiftView');



UPDATE SECTION_FIELD set FIELD_DEFINITION_ID = 'recurringGift.distributionLines.customFieldMap[tribute]', SECONDARY_FIELD_DEFINITION_ID='distributionLines.customFieldMap[tribute]'
WHERE FIELD_DEFINITION_ID = 'recurringGift.distributionLines.customFieldMap[tributeReadOnly]' and SECONDARY_FIELD_DEFINITION_ID='distributionLines.customFieldMap[tributeReadOnly]'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.extendedDistribution' AND PAGE_TYPE='recurringGiftView');

UPDATE SECTION_FIELD set FIELD_DEFINITION_ID = 'recurringGift.distributionLines.customFieldMap[tributeReference]', SECONDARY_FIELD_DEFINITION_ID='distributionLines.customFieldMap[tributeReference]'
WHERE FIELD_DEFINITION_ID = 'recurringGift.distributionLines.customFieldMap[tributeReferenceReadOnly]' and SECONDARY_FIELD_DEFINITION_ID='distributionLines.customFieldMap[tributeReferenceReadOnly]'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.extendedDistribution' AND PAGE_TYPE='recurringGiftView');

UPDATE SECTION_FIELD set FIELD_DEFINITION_ID = 'recurringGift.distributionLines.customFieldMap[other_tributeReference]', SECONDARY_FIELD_DEFINITION_ID='distributionLines.customFieldMap[other_tributeReference]'
WHERE FIELD_DEFINITION_ID = 'recurringGift.distributionLines.customFieldMap[other_tributeReferenceReadOnly]' and SECONDARY_FIELD_DEFINITION_ID='distributionLines.customFieldMap[other_tributeReferenceReadOnly]'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.extendedDistribution' AND PAGE_TYPE='recurringGiftView');

UPDATE SECTION_FIELD set FIELD_DEFINITION_ID = 'recurringGift.distributionLines.customFieldMap[tributeOccasion]', SECONDARY_FIELD_DEFINITION_ID='distributionLines.customFieldMap[tributeOccasion]'
WHERE FIELD_DEFINITION_ID = 'recurringGift.distributionLines.customFieldMap[tributeOccasionReadOnly]' and SECONDARY_FIELD_DEFINITION_ID='distributionLines.customFieldMap[tributeOccasionReadOnly]'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.extendedDistribution' AND PAGE_TYPE='recurringGiftView');

UPDATE SECTION_FIELD set FIELD_DEFINITION_ID = 'recurringGift.distributionLines.customFieldMap[additional_tributeOccasion]', SECONDARY_FIELD_DEFINITION_ID='distributionLines.customFieldMap[additional_tributeOccasion]'
WHERE FIELD_DEFINITION_ID = 'recurringGift.distributionLines.customFieldMap[additional_tributeOccasionReadOnly]' and SECONDARY_FIELD_DEFINITION_ID='distributionLines.customFieldMap[additional_tributeOccasionReadOnly]'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.extendedDistribution' AND PAGE_TYPE='recurringGiftView');

UPDATE SECTION_FIELD set FIELD_DEFINITION_ID = 'recurringGift.distributionLines.customFieldMap[onBehalfOf]', SECONDARY_FIELD_DEFINITION_ID='distributionLines.customFieldMap[onBehalfOf]'
WHERE FIELD_DEFINITION_ID = 'recurringGift.distributionLines.customFieldMap[onBehalfOfReadOnly]' and SECONDARY_FIELD_DEFINITION_ID='distributionLines.customFieldMap[onBehalfOfReadOnly]'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.extendedDistribution' AND PAGE_TYPE='recurringGiftView');

UPDATE SECTION_FIELD set FIELD_DEFINITION_ID = 'recurringGift.distributionLines.customFieldMap[other_onBehalfOf]', SECONDARY_FIELD_DEFINITION_ID='distributionLines.customFieldMap[other_onBehalfOf]'
WHERE FIELD_DEFINITION_ID = 'recurringGift.distributionLines.customFieldMap[other_onBehalfOfReadOnly]' and SECONDARY_FIELD_DEFINITION_ID='distributionLines.customFieldMap[other_onBehalfOfReadOnly]'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.extendedDistribution' AND PAGE_TYPE='recurringGiftView');

UPDATE SECTION_FIELD set FIELD_DEFINITION_ID = 'recurringGift.distributionLines.customFieldMap[anonymous]', SECONDARY_FIELD_DEFINITION_ID='distributionLines.customFieldMap[anonymous]'
WHERE FIELD_DEFINITION_ID = 'recurringGift.distributionLines.customFieldMap[anonymousReadOnly]' and SECONDARY_FIELD_DEFINITION_ID='distributionLines.customFieldMap[anonymousReadOnly]'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.extendedDistribution' AND PAGE_TYPE='recurringGiftView');

UPDATE SECTION_FIELD set FIELD_DEFINITION_ID = 'recurringGift.distributionLines.customFieldMap[recognitionName]', SECONDARY_FIELD_DEFINITION_ID='distributionLines.customFieldMap[recognitionName]'
WHERE FIELD_DEFINITION_ID = 'recurringGift.distributionLines.customFieldMap[recognitionNameReadOnly]' and SECONDARY_FIELD_DEFINITION_ID='distributionLines.customFieldMap[recognitionNameReadOnly]'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.extendedDistribution' AND PAGE_TYPE='recurringGiftView');

UPDATE SECTION_FIELD set FIELD_DEFINITION_ID = 'recurringGift.distributionLines.customFieldMap[notified]', SECONDARY_FIELD_DEFINITION_ID='distributionLines.customFieldMap[notified]'
WHERE FIELD_DEFINITION_ID = 'recurringGift.distributionLines.customFieldMap[notifiedReadOnly]' and SECONDARY_FIELD_DEFINITION_ID='distributionLines.customFieldMap[notifiedReadOnly]'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.extendedDistribution' AND PAGE_TYPE='recurringGiftView');

UPDATE SECTION_FIELD set FIELD_DEFINITION_ID = 'recurringGift.distributionLines.customFieldMap[other_notified]', SECONDARY_FIELD_DEFINITION_ID='distributionLines.customFieldMap[other_notified]'
WHERE FIELD_DEFINITION_ID = 'recurringGift.distributionLines.customFieldMap[other_notifiedReadOnly]' and SECONDARY_FIELD_DEFINITION_ID='distributionLines.customFieldMap[other_notifiedReadOnly]'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.extendedDistribution' AND PAGE_TYPE='recurringGiftView');

UPDATE SECTION_FIELD set FIELD_DEFINITION_ID = 'recurringGift.distributionLines.customFieldMap[message]', SECONDARY_FIELD_DEFINITION_ID='distributionLines.customFieldMap[message]'
WHERE FIELD_DEFINITION_ID = 'recurringGift.distributionLines.customFieldMap[messageReadOnly]' and SECONDARY_FIELD_DEFINITION_ID='distributionLines.customFieldMap[messageReadOnly]'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.extendedDistribution' AND PAGE_TYPE='recurringGiftView');

UPDATE SECTION_FIELD set FIELD_DEFINITION_ID = 'recurringGift.distributionLines.customFieldMap[taxDeductible]', SECONDARY_FIELD_DEFINITION_ID='distributionLines.customFieldMap[taxDeductible]'
WHERE FIELD_DEFINITION_ID = 'recurringGift.distributionLines.customFieldMap[taxDeductibleReadOnly]' and SECONDARY_FIELD_DEFINITION_ID='distributionLines.customFieldMap[taxDeductibleReadOnly]'
and SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.extendedDistribution' AND PAGE_TYPE='recurringGiftView');






INSERT INTO FIELD_DEFINITION (FIELD_DEFINITION_ID, ENTITY_TYPE, FIELD_NAME, DEFAULT_LABEL, FIELD_TYPE) VALUES ('adjustedGift.id', 'adjustedGift', 'id', 'Reference Number', 'TEXT');


UPDATE `SECTION_DEFINITION` SET `DEFAULT_LABEL`='All Gifts', `LAYOUT_TYPE`='TREE_GRID' WHERE (`SECTION_NAME`='giftList.resultsInfo' AND `PAGE_TYPE`='giftList') ;



UPDATE `SECTION_FIELD` SET `FIELD_ORDER`='100'  WHERE (`SECTION_DEFINITION_ID` = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='giftList.resultsInfo' AND PAGE_TYPE='giftList') AND `FIELD_DEFINITION_ID` = 'gift.id' AND `SECONDARY_FIELD_DEFINITION_ID` IS NULL);

UPDATE `SECTION_FIELD` SET `FIELD_DEFINITION_ID` = 'gift.donationDate'  WHERE (`SECTION_DEFINITION_ID` = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='giftList.resultsInfo' AND PAGE_TYPE='giftList') AND `FIELD_DEFINITION_ID` = 'gift.transactionDate' AND `SECONDARY_FIELD_DEFINITION_ID` IS NULL);

UPDATE `SECTION_FIELD` SET `FIELD_ORDER`='2000'  WHERE (`SECTION_DEFINITION_ID` = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='giftList.resultsInfo' AND PAGE_TYPE='giftList') AND `FIELD_DEFINITION_ID` = 'gift.amount' AND `SECONDARY_FIELD_DEFINITION_ID` IS NULL);

UPDATE `SECTION_FIELD` SET `FIELD_ORDER`='8000'  WHERE (`SECTION_DEFINITION_ID` = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='giftList.resultsInfo' AND PAGE_TYPE='giftList') AND `FIELD_DEFINITION_ID` = 'gift.comments' AND `SECONDARY_FIELD_DEFINITION_ID` IS NULL);

UPDATE `SECTION_FIELD` SET `FIELD_ORDER`='6000'  WHERE (`SECTION_DEFINITION_ID` = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='giftList.resultsInfo' AND PAGE_TYPE='giftList') AND `FIELD_DEFINITION_ID` = 'gift.authCodeReadOnly' AND `SECONDARY_FIELD_DEFINITION_ID` IS NULL);

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER) SELECT SECTION_DEFINITION_ID, 'gift.currencyCode', 3000 FROM SECTION_DEFINITION WHERE SECTION_NAME='giftList.resultsInfo' AND PAGE_TYPE='giftList';

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER) SELECT SECTION_DEFINITION_ID, 'gift.paymentType', 4000 FROM SECTION_DEFINITION WHERE SECTION_NAME='giftList.resultsInfo' AND PAGE_TYPE='giftList';

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER) SELECT SECTION_DEFINITION_ID, 'gift.paymentStatusReadOnly', 5000 FROM SECTION_DEFINITION WHERE SECTION_NAME='giftList.resultsInfo' AND PAGE_TYPE='giftList';

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER) SELECT SECTION_DEFINITION_ID, 'gift.txRefNumReadOnly', 7000 FROM SECTION_DEFINITION WHERE SECTION_NAME='giftList.resultsInfo' AND PAGE_TYPE='giftList';




SET @Next_ID=(SELECT MAX(SECTION_DEFINITION_ID)+1000 FROM SECTION_DEFINITION);

INSERT INTO SECTION_DEFINITION (SECTION_DEFINITION_ID, PAGE_TYPE, SECTION_NAME, DEFAULT_LABEL, SECTION_ORDER, LAYOUT_TYPE, ROLE) VALUES (@Next_ID, 'adjustedGiftList', 'adjustedGiftList.resultsInfo', ' ', 2, 'TREE_GRID_HIDDEN_ROW', 'ROLE_USER');



INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES (@Next_ID, 'adjustedGift.id', 100);

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES (@Next_ID, 'adjustedGift.transactionDate', 1000);

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES (@Next_ID, 'adjustedGift.adjustedAmount', 2000);

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES (@Next_ID, 'adjustedGift.currencyCodeReadOnly', 3000);

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES (@Next_ID, 'adjustedGift.paymentType', 4000);

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES (@Next_ID, 'adjustedGift.paymentStatusReadOnly', 5000);

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES (@Next_ID, 'adjustedGift.authCodeReadOnly', 6000);

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES (@Next_ID, 'adjustedGift.txRefNumReadOnly', 7000);

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES (@Next_ID, 'adjustedGift.comments', 8000);



/* Constituent search results */
UPDATE `SECTION_DEFINITION` SET `LAYOUT_TYPE`='SEARCH_GRID' WHERE (`SECTION_NAME`='constituentSearchResults.resultsInfo' AND `PAGE_TYPE`='constituentSearchResults') ;

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER)
SELECT SECTION_DEFINITION_ID, 'constituent.id', 100 FROM SECTION_DEFINITION WHERE SECTION_NAME='constituentSearchResults.resultsInfo' AND PAGE_TYPE='constituentSearchResults';


/* Gift search */
UPDATE `SECTION_FIELD` SET `FIELD_ORDER`='100'  WHERE (`SECTION_DEFINITION_ID` = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='giftSearch.searchInfo' AND PAGE_TYPE='giftSearch')
AND `FIELD_DEFINITION_ID` = 'gift.id' AND `SECONDARY_FIELD_DEFINITION_ID` IS NULL);

UPDATE `SECTION_FIELD` SET `FIELD_ORDER`='1500'  WHERE (`SECTION_DEFINITION_ID` = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='giftSearch.searchInfo' AND PAGE_TYPE='giftSearch')
AND `FIELD_DEFINITION_ID` = 'gift.constituent.organizationName' AND `SECONDARY_FIELD_DEFINITION_ID` = 'constituent.organizationName');

DELETE FROM SECTION_FIELD WHERE FIELD_DEFINITION_ID = 'gift.constituent.primaryAddress' AND SECONDARY_FIELD_DEFINITION_ID = 'address.postalCode'
AND SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='giftSearch.searchInfo' AND PAGE_TYPE='giftSearch');

/* Gift search results */
INSERT INTO FIELD_DEFINITION (FIELD_DEFINITION_ID, ENTITY_TYPE, FIELD_NAME, DEFAULT_LABEL, FIELD_TYPE) VALUES ('gift.constituent.id', 'gift', 'constituent', 'Account Id', 'READ_ONLY_TEXT');

UPDATE `SECTION_DEFINITION` SET `LAYOUT_TYPE`='SEARCH_GRID' WHERE (`SECTION_NAME`='giftSearchResults.resultsInfo' AND `PAGE_TYPE`='giftSearchResults') ;

UPDATE `SECTION_FIELD` SET `FIELD_ORDER`='100'  WHERE (`SECTION_DEFINITION_ID` = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='giftSearchResults.resultsInfo' AND PAGE_TYPE='giftSearchResults')
AND `FIELD_DEFINITION_ID` = 'gift.id' AND `SECONDARY_FIELD_DEFINITION_ID` IS NULL);

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, SECONDARY_FIELD_DEFINITION_ID, FIELD_ORDER)
SELECT SECTION_DEFINITION_ID, 'gift.constituent.id', 'constituent.id', 200 FROM SECTION_DEFINITION WHERE SECTION_NAME='giftSearchResults.resultsInfo' AND PAGE_TYPE='giftSearchResults';

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, SECONDARY_FIELD_DEFINITION_ID, FIELD_ORDER) 
SELECT SECTION_DEFINITION_ID, 'gift.constituent.accountNumber', 'constituent.accountNumber', 2000 FROM SECTION_DEFINITION WHERE SECTION_NAME='giftSearchResults.resultsInfo' AND PAGE_TYPE='giftSearchResults';

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, SECONDARY_FIELD_DEFINITION_ID, FIELD_ORDER)
SELECT SECTION_DEFINITION_ID, 'gift.constituent.organizationName', 'constituent.organizationName', 2500 FROM SECTION_DEFINITION WHERE SECTION_NAME='giftSearchResults.resultsInfo' AND PAGE_TYPE='giftSearchResults';

UPDATE `SECTION_FIELD` SET `FIELD_DEFINITION_ID`='gift.constituent.lastName', SECONDARY_FIELD_DEFINITION_ID='constituent.lastName'
WHERE (`SECTION_DEFINITION_ID` = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='giftSearchResults.resultsInfo' AND PAGE_TYPE='giftSearchResults')
AND `FIELD_DEFINITION_ID` = 'gift.constituentLastName' AND `SECONDARY_FIELD_DEFINITION_ID` IS NULL);

UPDATE `SECTION_FIELD` SET `FIELD_DEFINITION_ID`='gift.constituent.firstName', SECONDARY_FIELD_DEFINITION_ID='constituent.firstName' 
WHERE (`SECTION_DEFINITION_ID` = (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE SECTION_NAME='giftSearchResults.resultsInfo' AND PAGE_TYPE='giftSearchResults')
AND `FIELD_DEFINITION_ID` = 'gift.constituentFirstName' AND `SECONDARY_FIELD_DEFINITION_ID` IS NULL);


/* Tangerine-1272 */
UPDATE FIELD_DEFINITION set FIELD_TYPE = 'PICKLIST_DISPLAY' WHERE FIELD_DEFINITION_ID = 'recurringGift.frequencyReadOnly';


/* Tangerine-1237 */
INSERT INTO PICKLIST (PICKLIST_ID, PICKLIST_NAME_ID, PICKLIST_NAME, PICKLIST_DESC) VALUES (1001004, 'screenDefinitionRole', 'screenDefinitionRole', 'Screen Definition Role');
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (1001004, 'ROLE_SUPER_ADMIN', 'ROLE_SUPER_ADMIN', 1);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (1001004, 'ROLE_ADMIN', 'ROLE_ADMIN', 2);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (1001004, 'ROLE_USER', 'ROLE_USER', 3);

/* Tangerine-1339 */
DELETE FROM ENTITY_DEFAULT WHERE DEFAULT_VALUE LIKE 'picklist:%';

/* Tangerine-1217 */
INSERT INTO FIELD_DEFINITION (FIELD_DEFINITION_ID, ENTITY_TYPE, FIELD_NAME, DEFAULT_LABEL, FIELD_TYPE) VALUES ('recurringGift.customFieldMap[recurringGiftName]', 'recurringGift', 'customFieldMap[recurringGiftName]', 'Recurring Gift Name', 'TEXT');
INSERT INTO FIELD_DEFINITION (FIELD_DEFINITION_ID, ENTITY_TYPE, FIELD_NAME, DEFAULT_LABEL, FIELD_TYPE) VALUES ('pledge.customFieldMap[pledgeName]', 'pledge', 'customFieldMap[pledgeName]', 'Pledge Name', 'TEXT');

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER)
SELECT SECTION_DEFINITION_ID, 'recurringGift.customFieldMap[recurringGiftName]', 14000 FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGift.info' AND PAGE_TYPE='recurringGift';

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER)
SELECT SECTION_DEFINITION_ID, 'recurringGift.customFieldMap[recurringGiftName]', 9700 FROM SECTION_DEFINITION WHERE SECTION_NAME='recurringGiftView.info' AND PAGE_TYPE='recurringGiftView';

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER)
SELECT SECTION_DEFINITION_ID, 'pledge.customFieldMap[pledgeName]', 14500 FROM SECTION_DEFINITION WHERE SECTION_NAME='pledge.info' AND PAGE_TYPE='pledge';

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER)
SELECT SECTION_DEFINITION_ID, 'pledge.customFieldMap[pledgeName]', 11250 FROM SECTION_DEFINITION WHERE SECTION_NAME='pledge.info' AND PAGE_TYPE='pledgeView';

insert into ENTITY_DEFAULT (DEFAULT_VALUE, ENTITY_FIELD_NAME, ENTITY_TYPE)
values ('', 'customFieldMap[recurringGiftName]', 'recurringGift');

insert into ENTITY_DEFAULT (DEFAULT_VALUE, ENTITY_FIELD_NAME, ENTITY_TYPE)
values ('', 'customFieldMap[pledgeName]', 'pledge');





COMMIT;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

