SET AUTOCOMMIT = 0;


SET @NEXT_ID=(SELECT MAX(MESSAGE_RESOURCE_ID)+1 FROM MESSAGE_RESOURCE);

INSERT INTO `MESSAGE_RESOURCE` (`MESSAGE_RESOURCE_ID`,`LANGUAGE_ABBREVIATION`,`MESSAGE_KEY`,`MESSAGE_RESOURCE_TYPE`,`MESSAGE_VALUE`,`SITE_NAME`)
VALUES (@NEXT_ID, 'en_US', 'appName', 'FIELD_VALIDATION', 'Pursuant Open', 'pursuant');

COMMIT;
