INSERT INTO CODE_TYPE (ID, NAME, LABEL, SITE_NAME) VALUES (1, 'projectCode', 'Designation Code', null);
INSERT INTO CODE_TYPE (ID, NAME, LABEL, SITE_NAME) VALUES (2, 'motivationCode', 'Motivation Code', null);
INSERT INTO CODE_TYPE (ID, NAME, LABEL, SITE_NAME) VALUES (10, 'currencyCode', 'Currency Code', null);

INSERT INTO CODE SET CODE_VALUE='001000',CODE_DESCRIPTION='General Fund - President',CODE_TYPE_ID='1',INACTIVE=false;
INSERT INTO CODE SET CODE_VALUE='0201',CODE_DESCRIPTION='Conversion',CODE_TYPE_ID='2',INACTIVE=false;
INSERT INTO CODE (CODE_TYPE_ID, CODE_VALUE, CODE_DESCRIPTION, INACTIVE) VALUES ('10', 'USD', 'United States of America, Dollars', false);

