INSERT INTO PICKLIST (PICKLIST_ID, PICKLIST_NAME) VALUES ('creditCardExpirationYear', 'creditCardExpirationYear');
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES ('creditCardExpirationYear', year(current_date), year(current_date), 1);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES ('creditCardExpirationYear', year(current_date)+1, year(current_date)+1, 2);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES ('creditCardExpirationYear', year(current_date)+2, year(current_date)+2, 3);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES ('creditCardExpirationYear', year(current_date)+3, year(current_date)+3, 4);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES ('creditCardExpirationYear', year(current_date)+4, year(current_date)+4, 5);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES ('creditCardExpirationYear', year(current_date)+5, year(current_date)+5, 6);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES ('creditCardExpirationYear', year(current_date)+6, year(current_date)+6, 7);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES ('creditCardExpirationYear', year(current_date)+7, year(current_date)+7, 8);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES ('creditCardExpirationYear', year(current_date)+8, year(current_date)+8, 9);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES ('creditCardExpirationYear', year(current_date)+9, year(current_date)+9, 10);