INSERT INTO PICKLIST (PICKLIST_ID, PICKLIST_NAME_ID, PICKLIST_NAME, PICKLIST_DESC) VALUES (43,'giftStatus', 'giftStatus', 'Gift Status');
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, REFERENCE_VALUE, READ_ONLY, ITEM_ORDER) VALUES (43, 'Pending', 'Pending', '', TRUE, 1);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, REFERENCE_VALUE, READ_ONLY, ITEM_ORDER) VALUES (43, 'In Progress', 'In Progress', '', TRUE, 2);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, REFERENCE_VALUE, READ_ONLY, ITEM_ORDER) VALUES (43, 'Fulfilled', 'Fulfilled', '', TRUE, 3);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, REFERENCE_VALUE, READ_ONLY, ITEM_ORDER) VALUES (43, 'Cancelled', 'Cancelled', '', TRUE, 4);
