INSERT INTO PICKLIST (PICKLIST_ID, PICKLIST_NAME_ID, PICKLIST_NAME, PICKLIST_DESC) VALUES (39,'customFieldMap[organization.ineligibleOrganizations]', 'customFieldMap[organization.ineligibleOrganizations]', 'Matching Eligible Organizations');
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (39, 'higherEducationalInstitutions', 'Higher Educational Institutions', 1);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (39, 'primarySecondarySchools', 'Primary and Secondary Schools', 2);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (39, 'artsCulturalOrganizations', 'Arts and Cultural Organizations', 3);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (39, 'publicPolicyOrganizations', 'Public Policy Organizations', 4);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (39, 'environmentalOrganizations', 'Environmental Organizations', 5);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (39, 'athleticPrograms', 'Athletic Programs', 6);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (39, 'religiousOrganizations', 'Religious Organizations', 7);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (39, 'politicalCampaignsOrganizations', 'Political Campaigns or Organizations', 8);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (39, 'healthHumanServiceOrganizations', 'Health and Human Service Organizations', 9);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (39, 'hospitalsMedicalResearchOrganizations', 'Hospitals or Medical Research Organizations', 10);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (39, 'humaneSocietiesOrganizations', 'Humane Societies or Organizations', 11);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (39, 'individualsFraternalVeteransOrganizations', 'Individuals, Fraternal or Veterans Organizations', 12);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (39, 'ministriesTheologicalBibleSchools', 'Ministries, Theological or Bible Schools', 13);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (39, 'pledgesTithesTuition', 'Pledges, Tithes or Tuition', 14);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (39, 'professionalAssociations', 'Professional Associations', 15);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (39, 'schoolChoirsBandsDrillTeams', 'School Choirs, Bands or Drill Teams', 16);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (39, 'scoutingOrganizations', 'Scouting Organizations', 17);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (39, 'gifts-in-Kind', 'Gifts-in-Kind', 18);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (39, 'membershipSubscriptionPortionDonation', 'Membership or Subscription Portion of a Donation', 19);
