INSERT INTO PICKLIST (PICKLIST_ID, PICKLIST_NAME_ID, PICKLIST_NAME, ENTITY_TYPE, PICKLIST_DESC) VALUES (19,'gift.paymentType', 'paymentType', 'gift', 'Gift Payment Type');
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, REFERENCE_VALUE, ITEM_ORDER) VALUES (19, 'Credit Card', 'Credit Card', 'li:has(#selectedPaymentSource)', 1);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, REFERENCE_VALUE, ITEM_ORDER) VALUES (19, 'ACH', 'ACH', 'li:has(#selectedPaymentSource)', 2);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, REFERENCE_VALUE, ITEM_ORDER) VALUES (19, 'Check', 'Check', '.gift_check', 3);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, REFERENCE_VALUE, ITEM_ORDER) VALUES (19, 'Cash', 'Cash', '.gift_cash', 4);

INSERT INTO PICKLIST (PICKLIST_ID, PICKLIST_NAME_ID, PICKLIST_NAME, ENTITY_TYPE, PICKLIST_DESC) VALUES (20,'recurringGift.paymentType', 'paymentType', 'recurringGift', 'Recurring Gift Payment Type');
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, REFERENCE_VALUE, ITEM_ORDER) VALUES (20, 'Credit Card', 'Credit Card', '.recurringGift_creditCard', 1);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, REFERENCE_VALUE, ITEM_ORDER) VALUES (20, 'ACH', 'ACH', '.recurringGift_ach', 4);

INSERT INTO PICKLIST (PICKLIST_ID, PICKLIST_NAME_ID, PICKLIST_NAME, ENTITY_TYPE, PICKLIST_DESC) VALUES (21,'paymentSource.paymentType', 'paymentType', 'paymentSource', 'Payment Source Payment Type');
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, REFERENCE_VALUE, ITEM_ORDER) VALUES (21, 'Credit Card', 'Credit Card', '.paymentSource_creditCard', 1);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, REFERENCE_VALUE, ITEM_ORDER) VALUES (21, 'ACH', 'ACH', '.paymentSource_ach', 2);

INSERT INTO PICKLIST (PICKLIST_ID, PICKLIST_NAME_ID, PICKLIST_NAME, ENTITY_TYPE, PICKLIST_DESC) VALUES (49, 'adjustedGift.paymentType', 'paymentType', 'adjustedGift', 'Gift Payment Type');
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, REFERENCE_VALUE, ITEM_ORDER) VALUES (49, 'Credit Card', 'Credit Card', 'li:has(#selectedPaymentSource)', 1);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, REFERENCE_VALUE, ITEM_ORDER) VALUES (49, 'ACH', 'ACH', 'li:has(#selectedPaymentSource)', 2);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, REFERENCE_VALUE, ITEM_ORDER) VALUES (49, 'Check', 'Check', '.adjustedGift_check', 3);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, REFERENCE_VALUE, ITEM_ORDER) VALUES (49, 'Cash', 'Cash', '.adjustedGift_cash', 4);
