INSERT INTO PICKLIST (PICKLIST_ID, PICKLIST_NAME) VALUES ('paymentType', 'paymentType');
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES ('paymentSource.paymentType', 'Credit Card', 'Credit Card', 1);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES ('paymentSource.paymentType', 'Check', 'Check', 2);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES ('paymentSource.paymentType', 'Cash', 'Cash', 3);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES ('paymentSource.paymentType', 'ACH', 'ACH', 4);