INSERT INTO PICKLIST (PICKLIST_ID, PICKLIST_NAME_ID, PICKLIST_NAME, PICKLIST_DESC) VALUES (1000034,'provider', 'provider', 'Phone Provider');
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('item-template-SMSStringUS','<blank>','picklist',1000034);
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('item-template-SMSStringCA','<blank>','picklist',1000034);

INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (1000034, 'AT&T', 'AT&T', 1);
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('SMSStringUS','mmode.com','picklistItem',LAST_INSERT_ID());
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (1000034, 'Boost Mobile', 'Boost Mobile', 2);
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('SMSStringUS','myboostmobile.com','picklistItem',LAST_INSERT_ID());
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (1000034, 'Cellular One', 'Cellular One', 3);
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('SMSStringUS','mobile.celloneusa.com','picklistItem',LAST_INSERT_ID());
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (1000034, 'Cricket', 'Cricket', 4);
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('SMSStringUS','sms.mycricket.com','picklistItem',LAST_INSERT_ID());
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (1000034, 'MetroPCS', 'MetroPCS', 5);
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('SMSStringUS','mymetropcs.com','picklistItem',LAST_INSERT_ID());
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (1000034, 'Qwest', 'Qwest', 6);
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('SMSStringUS','qwestmp.com','picklistItem',LAST_INSERT_ID());
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (1000034, 'Sprint Nextel', 'Sprint Nextel', 7);
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('SMSStringUS','page.nextel.com','picklistItem',LAST_INSERT_ID());
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (1000034, 'T-Mobile', 'T-Mobile', 8);
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('SMSStringUS','tmomail.net','picklistItem',LAST_INSERT_ID());
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (1000034, 'Verizon', 'Verizon', 9);
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('SMSStringUS','vtext.com','picklistItem',LAST_INSERT_ID());

INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (1000034, 'Alaska Communications Systems', 'Alaska Communications Systems', 10);
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('SMSStringUS','msg.acsalaska.com','picklistItem',LAST_INSERT_ID());
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (1000034, 'AT&T Wireless', 'AT&T Wireless', 11);
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('SMSStringUS','txt.att.net','picklistItem',LAST_INSERT_ID());
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (1000034, 'US Cellular', 'US Cellular', 12);
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('SMSStringUS','email.uscc.net','picklistItem',LAST_INSERT_ID());
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (1000034, 'Virgin Mobile (US)', 'Virgin Mobile (US)', 13);
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('SMSStringUS','vmobl.com','picklistItem',LAST_INSERT_ID());
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (1000034, 'MobiPCS', 'MobiPCS', 14);
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('SMSStringUS','mobipcs.net','picklistItem',LAST_INSERT_ID());
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (1000034, 'Cincinnati Bell', 'Cincinnati Bell', 15);
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('SMSStringUS','gocbw.com','picklistItem',LAST_INSERT_ID());
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (1000034, 'Helio', 'Helio', 16);
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('SMSStringUS','myhelio.com','picklistItem',LAST_INSERT_ID());


INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (1000034, 'MTS', 'MTS', 100);
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('SMSStringCA','text.mtsmobility.com','picklistItem',LAST_INSERT_ID());
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (1000034, 'President''s Choice', 'President''s Choice', 101);
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('SMSStringCA','mobiletxt.ca','picklistItem',LAST_INSERT_ID());
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (1000034, 'Rogers', 'Rogers', 102);
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('SMSStringCA','pcs.rogers.com','picklistItem',LAST_INSERT_ID());
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (1000034, 'Sasktel', 'Sasktel', 103);
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('SMSStringCA','sms.sasktel.com','picklistItem',LAST_INSERT_ID());
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (1000034, 'Telus Mobility', 'Telus Mobility', 104);
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('SMSStringCA','msg.telus.com','picklistItem',LAST_INSERT_ID());
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (1000034, 'Virgin Mobile (CA)', 'Virgin Mobile (CA)', 105);
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('SMSStringCA','vmobile.ca','picklistItem',LAST_INSERT_ID());
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (1000034, 'Bell Mobility', 'Bell Mobility', 106);
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('SMSStringCA','txt.bell.ca','picklistItem',LAST_INSERT_ID());
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (1000034, 'Fido', 'Fido', 107);
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('SMSStringCA','fido.ca','picklistItem',LAST_INSERT_ID());


INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (1000034, 'Other', 'Other', 200);
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('SMSStringUS','','picklistItem',LAST_INSERT_ID());
