
UPDATE PICKLIST SET CREATE_DATE = now() WHERE CREATE_DATE IS null;

UPDATE PICKLIST SET UPDATE_DATE = now() WHERE UPDATE_DATE IS null;

UPDATE PICKLIST_ITEM SET CREATE_DATE = now() WHERE CREATE_DATE IS null;

UPDATE PICKLIST_ITEM SET UPDATE_DATE = now() WHERE UPDATE_DATE IS null;
