INSERT INTO PICKLIST (PICKLIST_ID, PICKLIST_NAME_ID, PICKLIST_NAME, PICKLIST_DESC) VALUES (1001004, 'screenDefinitionRole', 'screenDefinitionRole', 'Screen Definition Role');
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (1001004, 'ROLE_SUPER_ADMIN', 'ROLE_SUPER_ADMIN', 1);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (1001004, 'ROLE_ADMIN', 'ROLE_ADMIN', 2);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (1001004, 'ROLE_USER', 'ROLE_USER', 3);
