UPDATE PICKLIST_ITEM SET INACTIVE=false;

UPDATE PICKLIST_ITEM SET INACTIVE=true where PICKLIST_ID='currencyCode';
UPDATE PICKLIST_ITEM SET INACTIVE=false where PICKLIST_ID='currencyCode' and ITEM_NAME='USD';


