package com.mpower.domain.model.communication;

public class PhoneCustomField {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PHONE_CUSTOM_FIELD.PHONE_CUSTOM_FIELD_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long phoneCustomFieldId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PHONE_CUSTOM_FIELD.CUSTOM_FIELD_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long customFieldId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PHONE_CUSTOM_FIELD.PHONE_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long phoneId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PHONE_CUSTOM_FIELD.PHONE_CUSTOM_FIELD_ID
     *
     * @return the value of PHONE_CUSTOM_FIELD.PHONE_CUSTOM_FIELD_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getPhoneCustomFieldId() {
        return phoneCustomFieldId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PHONE_CUSTOM_FIELD.PHONE_CUSTOM_FIELD_ID
     *
     * @param phoneCustomFieldId the value for PHONE_CUSTOM_FIELD.PHONE_CUSTOM_FIELD_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setPhoneCustomFieldId(Long phoneCustomFieldId) {
        this.phoneCustomFieldId = phoneCustomFieldId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PHONE_CUSTOM_FIELD.CUSTOM_FIELD_ID
     *
     * @return the value of PHONE_CUSTOM_FIELD.CUSTOM_FIELD_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getCustomFieldId() {
        return customFieldId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PHONE_CUSTOM_FIELD.CUSTOM_FIELD_ID
     *
     * @param customFieldId the value for PHONE_CUSTOM_FIELD.CUSTOM_FIELD_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setCustomFieldId(Long customFieldId) {
        this.customFieldId = customFieldId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PHONE_CUSTOM_FIELD.PHONE_ID
     *
     * @return the value of PHONE_CUSTOM_FIELD.PHONE_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getPhoneId() {
        return phoneId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PHONE_CUSTOM_FIELD.PHONE_ID
     *
     * @param phoneId the value for PHONE_CUSTOM_FIELD.PHONE_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setPhoneId(Long phoneId) {
        this.phoneId = phoneId;
    }
}