SET AUTOCOMMIT = 0;

SELECT count(sf.FIELD_DEFINITION_ID) AS REC_COUNT, 6 AS EXPECTED_COUNT
FROM SECTION_FIELD sf
WHERE sf.SECTION_DEFINITION_ID IN (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE PAGE_TYPE IN ('gift', 'giftView', 'adjustedGift', 'adjustedGiftView'))
AND sf.SITE_NAME IS NOT NULL;


INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER, SITE_NAME)
SELECT SECTION_DEFINITION_ID, 'churcharmyaus-gift.customFieldMap[OtherPayMethodReadOnly]', 1200, 'churcharmyaus' FROM SECTION_DEFINITION WHERE SECTION_NAME='gift.payment' AND PAGE_TYPE='giftPaid';

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER, SITE_NAME)
SELECT SECTION_DEFINITION_ID, 'churcharmyaus-gift.customFieldMap[batchnbr]', 7000, 'churcharmyaus' FROM SECTION_DEFINITION WHERE SECTION_NAME='gift.donation' AND PAGE_TYPE='giftPaid';

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER, SITE_NAME)
SELECT SECTION_DEFINITION_ID, 'churcharmyaus-gift.customFieldMap[batchnbrReadOnly]', 5000, 'churcharmyaus' FROM SECTION_DEFINITION WHERE SECTION_NAME='adjustedGift.information' AND PAGE_TYPE='adjustedGiftPaid';


COMMIT;
