SET AUTOCOMMIT = 0;


SELECT count(sf.FIELD_DEFINITION_ID) AS REC_COUNT, 9 AS EXPECTED_COUNT
FROM SECTION_FIELD sf
WHERE sf.SECTION_DEFINITION_ID IN (SELECT SECTION_DEFINITION_ID FROM SECTION_DEFINITION WHERE PAGE_TYPE IN ('gift', 'giftView', 'adjustedGift', 'adjustedGiftView'))
AND sf.SITE_NAME IS NOT NULL;


INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER, SITE_NAME)
SELECT SECTION_DEFINITION_ID, 'smi-gift.customFieldMap[OtherPayMethodReadOnly]', 1200, 'smi' FROM SECTION_DEFINITION WHERE SECTION_NAME='gift.payment' AND PAGE_TYPE='giftPaid';

-- TODO: smi-gift.customFieldMap[receiptnumberReadOnly] for gift.payment, giftPaid?
-- TODO: gift.idReadOnly?
-- TODO: smi-gift.customFieldMap[receiptnumberReadOnly] for adjustedGift.information, adjustedGiftView?

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER, SITE_NAME)
SELECT SECTION_DEFINITION_ID, 'smi-gift.customFieldMap[batchno]', 7000, 'smi' FROM SECTION_DEFINITION WHERE SECTION_NAME='gift.donation' AND PAGE_TYPE='giftPaid';

INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER, SITE_NAME)
SELECT SECTION_DEFINITION_ID, 'smi-gift.customFieldMap[batchnoReadOnly]', 5000, 'smi' FROM SECTION_DEFINITION WHERE SECTION_NAME='adjustedGift.information' AND PAGE_TYPE='adjustedGiftPaid';


COMMIT;
