INSERT INTO SECTION_DEFINITION (PAGE_TYPE, SECTION_NAME, DEFAULT_LABEL, SECTION_ORDER, LAYOUT_TYPE) VALUES ('giftList', 'giftList.resultsInfo', ' ', 1, 'GRID');

INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('giftList.resultsInfo', 'gift.giftEnteredDate', 1000);
INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('giftList.resultsInfo', 'gift.id', 2000);
INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('giftList.resultsInfo', 'gift.value', 3000);
INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('giftList.resultsInfo', 'gift.comments', 4000);
