INSERT INTO SECTION_DEFINITION (PAGE_TYPE, SECTION_NAME, DEFAULT_LABEL, SECTION_ORDER, LAYOUT_TYPE) VALUES ('giftView', 'giftView.info', 'Gift Information', 1, 'ONE_COLUMN');

INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('giftView.info', 'gift.valueReadOnly', 1000);
INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('giftView.info', 'gift.commentsReadOnly', 2000);
INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('giftView.info', 'gift.paymentTypeReadOnly', 3000);


INSERT INTO SECTION_DEFINITION (PAGE_TYPE, SECTION_NAME, DEFAULT_LABEL, SECTION_ORDER, LAYOUT_TYPE) VALUES ('giftView', 'giftView.creditCard', 'Credit Card', 2, 'ONE_COLUMN');

INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('giftView.creditCard', 'gift.creditCardTypeReadOnly', 1000);
INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('giftView.creditCard', 'gift.creditCardNumberReadOnly', 2000);
INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('giftView.creditCard', 'gift.creditCardExpirationDate', 3000);


INSERT INTO SECTION_DEFINITION (PAGE_TYPE, SECTION_NAME, DEFAULT_LABEL, SECTION_ORDER, LAYOUT_TYPE) VALUES ('giftView', 'giftView.ach', 'ACH', 3, 'ONE_COLUMN');

INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('giftView.ach', 'gift.achTypeReadOnly', 1000);
INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('giftView.ach', 'gift.achRoutingNumberReadOnly', 2000);
INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('giftView.ach', 'gift.achAccountNumberReadOnly', 3000);


INSERT INTO SECTION_DEFINITION (PAGE_TYPE, SECTION_NAME, DEFAULT_LABEL, SECTION_ORDER, LAYOUT_TYPE) VALUES ('giftView', 'giftView.check', 'Check', 4, 'ONE_COLUMN');

INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('giftView.check', 'gift.checkNumberReadOnly', 1000);
