INSERT INTO PAGE_ACCESS (PAGE_ACCESS_ID, ACCESS_TYPE, PAGE_TYPE, ROLE, SITE_NAME) VALUES (1000000, 'ALLOWED', 'importexport', 'ROLE_ADMIN', null);
INSERT INTO PAGE_ACCESS (PAGE_ACCESS_ID, ACCESS_TYPE, PAGE_TYPE, ROLE, SITE_NAME) VALUES (1000001, 'ALLOWED', 'picklistItems', 'ROLE_SUPER_USER', null);
INSERT INTO PAGE_ACCESS (PAGE_ACCESS_ID, ACCESS_TYPE, PAGE_TYPE, ROLE, SITE_NAME) VALUES (1000002, 'ALLOWED', 'fieldRelationshipCustomize', 'ROLE_SUPER_ADMIN', null);
INSERT INTO PAGE_ACCESS (PAGE_ACCESS_ID, ACCESS_TYPE, PAGE_TYPE, ROLE, SITE_NAME) VALUES (1000003, 'ALLOWED', 'siteAudit', 'ROLE_ADMIN', null);
INSERT INTO PAGE_ACCESS (PAGE_ACCESS_ID, ACCESS_TYPE, PAGE_TYPE, ROLE, SITE_NAME) VALUES (1000004, 'ALLOWED', 'audit', 'ROLE_ADMIN', null);
INSERT INTO PAGE_ACCESS (PAGE_ACCESS_ID, ACCESS_TYPE, PAGE_TYPE, ROLE, SITE_NAME) VALUES (1000005, 'ALLOWED', 'customField', 'ROLE_SUPER_ADMIN', null);
INSERT INTO PAGE_ACCESS (PAGE_ACCESS_ID, ACCESS_TYPE, PAGE_TYPE, ROLE, SITE_NAME) VALUES (1000006, 'ALLOWED', 'siteSettings', 'ROLE_SUPER_ADMIN', null);
INSERT INTO PAGE_ACCESS (PAGE_ACCESS_ID, ACCESS_TYPE, PAGE_TYPE, ROLE, SITE_NAME) VALUES (1000007, 'ALLOWED', 'logView', 'ROLE_SUPER_ADMIN', null);
