INSERT INTO PAGE_ACCESS (PAGE_ACCESS_ID, ACCESS_TYPE, PAGE_TYPE, ROLE, SITE_NAME) VALUES (1000000, 'ALLOWED', 'importexport', 'ROLE_SUPER_ADMIN', null);
INSERT INTO PAGE_ACCESS (PAGE_ACCESS_ID, ACCESS_TYPE, PAGE_TYPE, ROLE, SITE_NAME) VALUES (1000001, 'ALLOWED', 'picklistItems', 'ROLE_SUPER_ADMIN', null);
