INSERT INTO SECTION_DEFINITION (PAGE_TYPE, SECTION_NAME, DEFAULT_LABEL, SECTION_ORDER, LAYOUT_TYPE) VALUES ('personSearch', 'personSearch.searchInfo', 'Search People', 1, 'TWO_COLUMN');

INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('personSearch.searchInfo', 'person.accountNumber', 1000);
INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('personSearch.searchInfo', 'person.lastName', 2000);
INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('personSearch.searchInfo', 'person.firstName', 3000);
INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('personSearch.searchInfo', 'person.organizationName', 4000);
INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('personSearch.searchInfo', 'person.email', 5000);
INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, SECONDARY_FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('personSearch.searchInfo', 'person.addressMap[primaryAddress]', 'address.postalCode', 6000);
INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, SECONDARY_FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('personSearch.searchInfo', 'person.addressMap[primaryAddress]', 'address.addressLine1', 7000);
INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, SECONDARY_FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('personSearch.searchInfo', 'person.addressMap[primaryAddress]', 'address.city', 8000);
INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, SECONDARY_FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('personSearch.searchInfo', 'person.addressMap[primaryAddress]', 'address.stateProvince', 9000);
INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('personSearch.searchInfo', 'person.phoneMap[generic]', 10000);