INSERT INTO SECTION_DEFINITION (PAGE_TYPE, SECTION_NAME, DEFAULT_LABEL, SECTION_ORDER, LAYOUT_TYPE) VALUES ('viewGift', 'viewGift.info', 'Gift Information', 1, 'TWO_COLUMN');

INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('viewGift.info', 'gift.valueReadOnly', 1000);
INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('viewGift.info', 'gift.commentsReadOnly', 2000);
INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('viewGift.info', 'gift.paymentTypeReadOnly', 3000);


INSERT INTO SECTION_DEFINITION (PAGE_TYPE, SECTION_NAME, DEFAULT_LABEL, SECTION_ORDER, LAYOUT_TYPE) VALUES ('viewGift', 'viewGift.creditCard', 'Credit Card', 2, 'TWO_COLUMN');

INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('viewGift.creditCard', 'gift.creditCardTypeReadOnly', 1000);
INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('viewGift.creditCard', 'gift.creditCardNumberReadOnly', 2000);
INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('viewGift.creditCard', 'gift.creditCardExpirationMonthReadOnly', 3000);
INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('viewGift.creditCard', 'gift.creditCardExpirationYearReadOnly', 4000);


INSERT INTO SECTION_DEFINITION (PAGE_TYPE, SECTION_NAME, DEFAULT_LABEL, SECTION_ORDER, LAYOUT_TYPE) VALUES ('viewGift', 'viewGift.ach', 'ACH', 3, 'TWO_COLUMN');

INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('viewGift.ach', 'gift.achTypeReadOnly', 1000);
INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('viewGift.ach', 'gift.achRoutingNumberReadOnly', 2000);
INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('viewGift.ach', 'gift.achAccountNumberReadOnly', 3000);


INSERT INTO SECTION_DEFINITION (PAGE_TYPE, SECTION_NAME, DEFAULT_LABEL, SECTION_ORDER, LAYOUT_TYPE) VALUES ('viewGift', 'viewGift.check', 'Check', 4, 'TWO_COLUMN');

INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('viewGift.check', 'gift.checkNumberReadOnly', 1000);
