INSERT INTO SECTION_DEFINITION (PAGE_TYPE, SECTION_NAME, DEFAULT_LABEL, SECTION_ORDER, LAYOUT_TYPE) VALUES ('viewGift', 'viewGift.info', 'Gift Information', 1, 'TWO_COLUMN');

INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('viewGift.info', 'viewGift.valueReadOnly', 1000);
INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('viewGift.info', 'viewGift.commentsReadOnly', 2000);
INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('viewGift.info', 'viewGift.paymentTypeReadOnly', 3000);


INSERT INTO SECTION_DEFINITION (PAGE_TYPE, SECTION_NAME, DEFAULT_LABEL, SECTION_ORDER, LAYOUT_TYPE) VALUES ('viewGift', 'viewGift.creditCard', 'Credit Card', 2, 'TWO_COLUMN');

INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('viewGift.creditCard', 'viewGift.creditCardTypeReadOnly', 1000);
INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('viewGift.creditCard', 'viewGift.creditCardNumberReadOnly', 2000);
INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('viewGift.creditCard', 'viewGift.creditCardExpirationReadOnly', 3000);


INSERT INTO SECTION_DEFINITION (PAGE_TYPE, SECTION_NAME, DEFAULT_LABEL, SECTION_ORDER, LAYOUT_TYPE) VALUES ('viewGift', 'viewGift.ach', 'ACH', 3, 'TWO_COLUMN');

INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('viewGift.ach', 'viewGift.achTypeReadOnly', 1000);
INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('viewGift.ach', 'viewGift.achRoutingNumberReadOnly', 2000);
INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('viewGift.ach', 'viewGift.achAccountNumberReadOnly', 3000);


INSERT INTO SECTION_DEFINITION (PAGE_TYPE, SECTION_NAME, DEFAULT_LABEL, SECTION_ORDER, LAYOUT_TYPE) VALUES ('viewGift', 'viewGift.check', 'Check', 4, 'TWO_COLUMN');

INSERT INTO SECTION_FIELD (SECTION_NAME, FIELD_DEFINITION_ID, FIELD_ORDER) VALUES ('viewGift.check', 'viewGift.checkNumberReadOnly', 1000);
