SET foreign_key_checks = 0;


TRUNCATE TABLE ADDRESS;
TRUNCATE TABLE ADDRESS_CUSTOM_FIELD;
TRUNCATE TABLE AUDIT;
TRUNCATE TABLE CODE;
TRUNCATE TABLE CODE_TYPE;
TRUNCATE TABLE COMMITMENT;
TRUNCATE TABLE COMMITMENT_CUSTOM_FIELD;
TRUNCATE TABLE CUSTOM_FIELD;
TRUNCATE TABLE DISTRO_LINE;
TRUNCATE TABLE DISTRO_LINE_CUSTOM_FIELD;
TRUNCATE TABLE EMAIL;
TRUNCATE TABLE EMAIL_CUSTOM_FIELD;
TRUNCATE TABLE ENTITY_DEFAULT;
TRUNCATE TABLE FIELD_CONDITION;
TRUNCATE TABLE FIELD_DEFINITION;
TRUNCATE TABLE FIELD_RELATIONSHIP;
TRUNCATE TABLE FIELD_REQUIRED;
TRUNCATE TABLE FIELD_VALIDATION;
TRUNCATE TABLE GIFT;
TRUNCATE TABLE GIFT_CUSTOM_FIELD;
TRUNCATE TABLE MESSAGE_RESOURCE;
TRUNCATE TABLE PAGE_ACCESS;
TRUNCATE TABLE PAYMENT_SOURCE;
TRUNCATE TABLE PAYMENT_HISTORY;
TRUNCATE TABLE PERSON;
TRUNCATE TABLE PERSON_CUSTOM_FIELD;
TRUNCATE TABLE PHONE;
TRUNCATE TABLE PHONE_CUSTOM_FIELD;
TRUNCATE TABLE PICKLIST;
TRUNCATE TABLE PICKLIST_ITEM;
TRUNCATE TABLE QUERY_LOOKUP;
TRUNCATE TABLE QUERY_LOOKUP_PARAM;
TRUNCATE TABLE RECURRING_GIFT;
TRUNCATE TABLE SECTION_DEFINITION;
TRUNCATE TABLE SECTION_FIELD;
TRUNCATE TABLE SITE;



SET foreign_key_checks = 1;
