SET foreign_key_checks = 0;


TRUNCATE TABLE ADDRESS;
TRUNCATE TABLE AUDIT;
TRUNCATE TABLE ADJUSTED_GIFT;
TRUNCATE TABLE RECURRING_GIFT;
TRUNCATE TABLE PLEDGE;
TRUNCATE TABLE COMMUNICATION_HISTORY;
TRUNCATE TABLE CUSTOM_FIELD_RELATIONSHIP;
TRUNCATE TABLE CONSTITUENT_CUSTOM_FIELD_RELATIONSHIP;
TRUNCATE TABLE CACHE_GROUP;
TRUNCATE TABLE CUSTOM_FIELD;
TRUNCATE TABLE DASHBOARD_ITEM;
TRUNCATE TABLE DASHBOARD_ITEM_DATASET;
TRUNCATE TABLE DISTRO_LINE;
TRUNCATE TABLE EMAIL;
TRUNCATE TABLE ENTITY_DEFAULT;
TRUNCATE TABLE ENTITY_SEARCH;
TRUNCATE TABLE FIELD_CONDITION;
TRUNCATE TABLE FIELD_DEFINITION;
TRUNCATE TABLE FIELD_RELATIONSHIP;
TRUNCATE TABLE FIELD_REQUIRED;
TRUNCATE TABLE FIELD_VALIDATION;
TRUNCATE TABLE GIFT;
TRUNCATE TABLE PLEDGE_GIFT;
TRUNCATE TABLE RECURRING_GIFT_GIFT;
TRUNCATE TABLE MESSAGE_RESOURCE;
TRUNCATE TABLE PAGE_ACCESS;
TRUNCATE TABLE PAYMENT_SOURCE;
TRUNCATE TABLE PAYMENT_HISTORY;
--TRUNCATE TABLE ROLLUP_SERIES;
--TRUNCATE TABLE ROLLUP_ATTRIBUTE;
--TRUNCATE TABLE ROLLUP_VALUE;
TRUNCATE TABLE CONSTITUENT;
TRUNCATE TABLE PHONE;
TRUNCATE TABLE PICKLIST;
TRUNCATE TABLE PICKLIST_ITEM;
TRUNCATE TABLE QUERY_LOOKUP;
TRUNCATE TABLE QUERY_LOOKUP_PARAM;
TRUNCATE TABLE RECURRING_GIFT;
TRUNCATE TABLE SECTION_DEFINITION;
TRUNCATE TABLE SECTION_FIELD;
TRUNCATE TABLE SITE;
TRUNCATE TABLE CUSTOM_ID;
TRUNCATE TABLE POST_BATCH;
TRUNCATE TABLE POST_BATCH_REVIEW_SET_ITEM;
TRUNCATE TABLE JOURNAL;
TRUNCATE TABLE SCHEDULED_ITEM;
TRUNCATE TABLE SITE_OPTION;
-- TRUNCATE TABLE ERROR_LOG;    cant do this with ARCHIVE option



SET foreign_key_checks = 1;
