-- ******************* Un-comment out the below line when running this script in mySql Query Browser ***************************************
-- DELIMITER $$

-- Create function to retrieve custom fields
DROP FUNCTION IF EXISTS ISDONORTYPE$$
CREATE FUNCTION `ISDONORTYPE`(ENTITYID INT, DONOR_TYPE VARCHAR(255))
        RETURNS BIT
BEGIN

        DECLARE CNT TINYINT;
        
        SELECT COUNT(CUSTOM_FIELD_ID) INTO CNT
                FROM CUSTOM_FIELD
                WHERE ENTITY_ID = ENTITYID
                AND ENTITY_TYPE = 'person'
                AND FIELD_NAME = 'donorProfiles'
                AND FIELD_VALUE = DONOR_TYPE;
                
        RETURN (CNT > 0);
        
END$$

-- Create function to get next key for a site
DROP FUNCTION IF EXISTS GENERATEID$$

CREATE FUNCTION GENERATEID(SITENAME VARCHAR(255))
    RETURNS VARCHAR(255)
BEGIN
    DECLARE CUSTOMID VARCHAR(255);

    IF (SELECT COUNT(SITE_NAME) FROM CUSTOM_ID WHERE SITE_NAME = SITENAME) = 0 THEN
    	INSERT CUSTOM_ID(SITE_NAME) VALUES(SITENAME);
    END IF;


    SELECT CONCAT(SITE_PREFIX,LPAD(CAST(NEXT_KEY as CHAR),6, '0')) INTO CUSTOMID
    FROM CUSTOM_ID
    WHERE SITE_NAME=SITENAME;

    UPDATE CUSTOM_ID SET NEXT_KEY = NEXT_KEY+1 WHERE SITE_NAME=SITENAME;

    RETURN CUSTOMID;

END$$

DROP TRIGGER IF EXISTS INSERT_CUSTOM_FIELD_NUMERIC_AND_DATE$$

CREATE TRIGGER INSERT_CUSTOM_FIELD_NUMERIC_AND_DATE 
BEFORE INSERT ON `CUSTOM_FIELD` 
FOR EACH ROW
BEGIN

  IF NEW.FIELD_VALUE RLIKE '^[0-9]*\.?[0-9]{0,2}$' THEN SET NEW.FIELD_NUMERIC_VALUE = CONVERT(NEW.FIELD_VALUE, decimal(19,2));
  ELSE SET NEW.FIELD_NUMERIC_VALUE = null;
  END IF;
  
  -- CUSTOM_FIELD stores dates as mm/dd/yyyy
  -- STR_TO_DATE will set to NULL if invalid date
  IF NEW.FIELD_VALUE RLIKE '^[0-9]{2}\/[0-9]{2}\/[0-9]{4}$' THEN SET NEW.FIELD_DATE_VALUE = STR_TO_DATE(NEW.FIELD_VALUE, '%m/%d/%Y'); 
  ELSE SET NEW.FIELD_DATE_VALUE = null;
  END IF;
  
END$$

DROP TRIGGER IF EXISTS UPDATE_CUSTOM_FIELD_NUMERIC_AND_DATE$$

CREATE TRIGGER UPDATE_CUSTOM_FIELD_NUMERIC_AND_DATE 
BEFORE UPDATE ON `CUSTOM_FIELD` 
FOR EACH ROW
BEGIN

  IF NEW.FIELD_VALUE RLIKE '^[0-9]*\.?[0-9]{0,2}$' THEN SET NEW.FIELD_NUMERIC_VALUE = CONVERT(NEW.FIELD_VALUE, decimal(19,2));
  ELSE SET NEW.FIELD_NUMERIC_VALUE = null;
  END IF;
  
  -- CUSTOM_FIELD stores dates as mm/dd/yyyy
  -- STR_TO_DATE will set to NULL if invalid date
  IF NEW.FIELD_VALUE RLIKE '^[0-9]{2}\/[0-9]{2}\/[0-9]{4}$' THEN SET NEW.FIELD_DATE_VALUE = STR_TO_DATE(NEW.FIELD_VALUE, '%m/%d/%Y'); 
  ELSE SET NEW.FIELD_DATE_VALUE = null;
  END IF;
  
END$$

