SET foreign_key_checks = 0;

TRUNCATE TABLE CODE;
TRUNCATE TABLE SECTION_FIELD;
TRUNCATE TABLE SECTION_DEFINITION;
TRUNCATE TABLE FIELD_DEFINITION;
TRUNCATE TABLE FIELD_RELATIONSHIP;
TRUNCATE TABLE PICKLIST_ITEM;
TRUNCATE TABLE PICKLIST;
TRUNCATE TABLE MESSAGE_RESOURCE;
TRUNCATE TABLE ENTITY_DEFAULT;
TRUNCATE TABLE GIFT_CUSTOM_FIELD;
TRUNCATE TABLE GIFT;
TRUNCATE TABLE PAYMENT_SOURCE;
TRUNCATE TABLE PERSON_CUSTOM_FIELD;
TRUNCATE TABLE ADDRESS;
TRUNCATE TABLE PERSON;
TRUNCATE TABLE SITE;
TRUNCATE TABLE PHONE;
TRUNCATE TABLE CUSTOM_FIELD;
TRUNCATE TABLE FIELD_VALIDATION;
TRUNCATE TABLE FIELD_REQUIRED;
TRUNCATE TABLE PAGE_ACCESS;
TRUNCATE TABLE QUERY_LOOKUP;
TRUNCATE TABLE QUERY_LOOKUP_PARAM;


SET foreign_key_checks = 1;
