SET AUTOCOMMIT = 0;


UPDATE PAGE_ACCESS SET ROLE = 'ROLE_SUPER_ADMIN,ROLE_ADMIN' WHERE PAGE_TYPE IN ('siteSettings', 'logView', 'manageDashboard');

UPDATE PAGE_ACCESS SET ROLE = 'ROLE_SUPER_ADMIN' WHERE PAGE_TYPE IN ('postbatch');

COMMIT;
