SET AUTOCOMMIT = 0;

DELETE FROM PICKLIST_ITEM WHERE ITEM_NAME IN ('ROLE_SUPER_ADMIN', 'ROLE_ADMIN', 'ROLE_USER') and PICKLIST_ID NOT IN (SELECT PICKLIST_ID FROM PICKLIST WHERE PICKLIST_NAME_ID = 'screenDefinitionRole');


SELECT COUNT(PICKLIST_ITEM_ID) AS ITEM_COUNT 
FROM PICKLIST_ITEM WHERE ITEM_NAME IN ('ROLE_SUPER_ADMIN', 'ROLE_ADMIN', 'ROLE_USER') and
PICKLIST_ID IN (SELECT PICKLIST_ID FROM PICKLIST WHERE PICKLIST_NAME_ID = 'screenDefinitionRole');


SET @Next_ID=(SELECT MAX(PICKLIST_ID)+1000 FROM PICKLIST);
INSERT INTO PICKLIST (PICKLIST_ID, PICKLIST_NAME_ID, PICKLIST_NAME, PICKLIST_DESC) VALUES (@Next_ID, 'screenDefinitionRole', 'screenDefinitionRole', 'Screen Definition Role');
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (@Next_ID, 'ROLE_SUPER_ADMIN', 'ROLE_SUPER_ADMIN', 1);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (@Next_ID, 'ROLE_ADMIN', 'ROLE_ADMIN', 2);
INSERT INTO PICKLIST_ITEM (PICKLIST_ID, ITEM_NAME, DEFAULT_DISPLAY_VALUE, ITEM_ORDER) VALUES (@Next_ID, 'ROLE_USER', 'ROLE_USER', 3);

COMMIT;