package com.mpower.domain.model;

import java.util.Date;

public class Address {
	
	public Address() {}
	public Address(Person person) {};
	
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ADDRESS.ADDRESS_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long addressId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ADDRESS.ACTIVATION_STATUS
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String activationStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ADDRESS.ADDRESS_LINE_1
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String addressLine1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ADDRESS.ADDRESS_LINE_2
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String addressLine2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ADDRESS.ADDRESS_LINE_3
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String addressLine3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ADDRESS.ADDRESS_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String addressType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ADDRESS.CITY
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String city;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ADDRESS.COMMENT
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String comment;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ADDRESS.COUNTRY
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String country;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ADDRESS.CREATE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date createDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ADDRESS.EFFECTIVE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date effectiveDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ADDRESS.INACTIVE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Boolean inactive;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ADDRESS.POSTAL_CODE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String postalCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ADDRESS.RECEIVE_CORRESPONDENCE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Boolean receiveCorrespondence;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ADDRESS.SEASONAL_END_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date seasonalEndDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ADDRESS.SEASONAL_START_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date seasonalStartDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ADDRESS.STATE_PROVINCE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String stateProvince;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ADDRESS.TEMPORARY_END_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date temporaryEndDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ADDRESS.TEMPORARY_START_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date temporaryStartDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ADDRESS.UPDATE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date updateDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ADDRESS.PERSON_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long personId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ADDRESS.ADDRESS_ID
     *
     * @return the value of ADDRESS.ADDRESS_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ADDRESS.ADDRESS_ID
     *
     * @param addressId the value for ADDRESS.ADDRESS_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ADDRESS.ACTIVATION_STATUS
     *
     * @return the value of ADDRESS.ACTIVATION_STATUS
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getActivationStatus() {
        return activationStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ADDRESS.ACTIVATION_STATUS
     *
     * @param activationStatus the value for ADDRESS.ACTIVATION_STATUS
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setActivationStatus(String activationStatus) {
        this.activationStatus = activationStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ADDRESS.ADDRESS_LINE_1
     *
     * @return the value of ADDRESS.ADDRESS_LINE_1
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getAddressLine1() {
        return addressLine1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ADDRESS.ADDRESS_LINE_1
     *
     * @param addressLine1 the value for ADDRESS.ADDRESS_LINE_1
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ADDRESS.ADDRESS_LINE_2
     *
     * @return the value of ADDRESS.ADDRESS_LINE_2
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getAddressLine2() {
        return addressLine2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ADDRESS.ADDRESS_LINE_2
     *
     * @param addressLine2 the value for ADDRESS.ADDRESS_LINE_2
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ADDRESS.ADDRESS_LINE_3
     *
     * @return the value of ADDRESS.ADDRESS_LINE_3
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getAddressLine3() {
        return addressLine3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ADDRESS.ADDRESS_LINE_3
     *
     * @param addressLine3 the value for ADDRESS.ADDRESS_LINE_3
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setAddressLine3(String addressLine3) {
        this.addressLine3 = addressLine3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ADDRESS.ADDRESS_TYPE
     *
     * @return the value of ADDRESS.ADDRESS_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getAddressType() {
        return addressType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ADDRESS.ADDRESS_TYPE
     *
     * @param addressType the value for ADDRESS.ADDRESS_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setAddressType(String addressType) {
        this.addressType = addressType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ADDRESS.CITY
     *
     * @return the value of ADDRESS.CITY
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ADDRESS.CITY
     *
     * @param city the value for ADDRESS.CITY
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ADDRESS.COMMENT
     *
     * @return the value of ADDRESS.COMMENT
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ADDRESS.COMMENT
     *
     * @param comment the value for ADDRESS.COMMENT
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ADDRESS.COUNTRY
     *
     * @return the value of ADDRESS.COUNTRY
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ADDRESS.COUNTRY
     *
     * @param country the value for ADDRESS.COUNTRY
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ADDRESS.CREATE_DATE
     *
     * @return the value of ADDRESS.CREATE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ADDRESS.CREATE_DATE
     *
     * @param createDate the value for ADDRESS.CREATE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ADDRESS.EFFECTIVE_DATE
     *
     * @return the value of ADDRESS.EFFECTIVE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ADDRESS.EFFECTIVE_DATE
     *
     * @param effectiveDate the value for ADDRESS.EFFECTIVE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ADDRESS.INACTIVE
     *
     * @return the value of ADDRESS.INACTIVE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Boolean getInactive() {
        return inactive;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ADDRESS.INACTIVE
     *
     * @param inactive the value for ADDRESS.INACTIVE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setInactive(Boolean inactive) {
        this.inactive = inactive;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ADDRESS.POSTAL_CODE
     *
     * @return the value of ADDRESS.POSTAL_CODE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ADDRESS.POSTAL_CODE
     *
     * @param postalCode the value for ADDRESS.POSTAL_CODE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ADDRESS.RECEIVE_CORRESPONDENCE
     *
     * @return the value of ADDRESS.RECEIVE_CORRESPONDENCE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Boolean getReceiveCorrespondence() {
        return receiveCorrespondence;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ADDRESS.RECEIVE_CORRESPONDENCE
     *
     * @param receiveCorrespondence the value for ADDRESS.RECEIVE_CORRESPONDENCE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setReceiveCorrespondence(Boolean receiveCorrespondence) {
        this.receiveCorrespondence = receiveCorrespondence;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ADDRESS.SEASONAL_END_DATE
     *
     * @return the value of ADDRESS.SEASONAL_END_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getSeasonalEndDate() {
        return seasonalEndDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ADDRESS.SEASONAL_END_DATE
     *
     * @param seasonalEndDate the value for ADDRESS.SEASONAL_END_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setSeasonalEndDate(Date seasonalEndDate) {
        this.seasonalEndDate = seasonalEndDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ADDRESS.SEASONAL_START_DATE
     *
     * @return the value of ADDRESS.SEASONAL_START_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getSeasonalStartDate() {
        return seasonalStartDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ADDRESS.SEASONAL_START_DATE
     *
     * @param seasonalStartDate the value for ADDRESS.SEASONAL_START_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setSeasonalStartDate(Date seasonalStartDate) {
        this.seasonalStartDate = seasonalStartDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ADDRESS.STATE_PROVINCE
     *
     * @return the value of ADDRESS.STATE_PROVINCE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getStateProvince() {
        return stateProvince;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ADDRESS.STATE_PROVINCE
     *
     * @param stateProvince the value for ADDRESS.STATE_PROVINCE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setStateProvince(String stateProvince) {
        this.stateProvince = stateProvince;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ADDRESS.TEMPORARY_END_DATE
     *
     * @return the value of ADDRESS.TEMPORARY_END_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getTemporaryEndDate() {
        return temporaryEndDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ADDRESS.TEMPORARY_END_DATE
     *
     * @param temporaryEndDate the value for ADDRESS.TEMPORARY_END_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setTemporaryEndDate(Date temporaryEndDate) {
        this.temporaryEndDate = temporaryEndDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ADDRESS.TEMPORARY_START_DATE
     *
     * @return the value of ADDRESS.TEMPORARY_START_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getTemporaryStartDate() {
        return temporaryStartDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ADDRESS.TEMPORARY_START_DATE
     *
     * @param temporaryStartDate the value for ADDRESS.TEMPORARY_START_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setTemporaryStartDate(Date temporaryStartDate) {
        this.temporaryStartDate = temporaryStartDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ADDRESS.UPDATE_DATE
     *
     * @return the value of ADDRESS.UPDATE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ADDRESS.UPDATE_DATE
     *
     * @param updateDate the value for ADDRESS.UPDATE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ADDRESS.PERSON_ID
     *
     * @return the value of ADDRESS.PERSON_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getPersonId() {
        return personId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ADDRESS.PERSON_ID
     *
     * @param personId the value for ADDRESS.PERSON_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setPersonId(Long personId) {
        this.personId = personId;
    }
}