package com.mpower.domain.model;

public class AddressCustomField {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ADDRESS_CUSTOM_FIELD.ADDRESS_CUSTOM_FIELD_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long addressCustomFieldId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ADDRESS_CUSTOM_FIELD.ADDRESS_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long addressId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ADDRESS_CUSTOM_FIELD.CUSTOM_FIELD_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long customFieldId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ADDRESS_CUSTOM_FIELD.ADDRESS_CUSTOM_FIELD_ID
     *
     * @return the value of ADDRESS_CUSTOM_FIELD.ADDRESS_CUSTOM_FIELD_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getAddressCustomFieldId() {
        return addressCustomFieldId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ADDRESS_CUSTOM_FIELD.ADDRESS_CUSTOM_FIELD_ID
     *
     * @param addressCustomFieldId the value for ADDRESS_CUSTOM_FIELD.ADDRESS_CUSTOM_FIELD_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setAddressCustomFieldId(Long addressCustomFieldId) {
        this.addressCustomFieldId = addressCustomFieldId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ADDRESS_CUSTOM_FIELD.ADDRESS_ID
     *
     * @return the value of ADDRESS_CUSTOM_FIELD.ADDRESS_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ADDRESS_CUSTOM_FIELD.ADDRESS_ID
     *
     * @param addressId the value for ADDRESS_CUSTOM_FIELD.ADDRESS_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ADDRESS_CUSTOM_FIELD.CUSTOM_FIELD_ID
     *
     * @return the value of ADDRESS_CUSTOM_FIELD.CUSTOM_FIELD_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getCustomFieldId() {
        return customFieldId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ADDRESS_CUSTOM_FIELD.CUSTOM_FIELD_ID
     *
     * @param customFieldId the value for ADDRESS_CUSTOM_FIELD.CUSTOM_FIELD_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setCustomFieldId(Long customFieldId) {
        this.customFieldId = customFieldId;
    }
}