package com.mpower.domain.model;

import java.util.Date;

public class Audit {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column AUDIT.AUDIT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long auditId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column AUDIT.AUDIT_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String auditType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column AUDIT.DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date date;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column AUDIT.DESCRIPTION
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String description;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column AUDIT.ENTITY_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String entityType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column AUDIT.OBJECT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long objectId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column AUDIT.USER
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String user;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column AUDIT.PERSON_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long personId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column AUDIT.SITE_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String siteName;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column AUDIT.AUDIT_ID
     *
     * @return the value of AUDIT.AUDIT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getAuditId() {
        return auditId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column AUDIT.AUDIT_ID
     *
     * @param auditId the value for AUDIT.AUDIT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setAuditId(Long auditId) {
        this.auditId = auditId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column AUDIT.AUDIT_TYPE
     *
     * @return the value of AUDIT.AUDIT_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getAuditType() {
        return auditType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column AUDIT.AUDIT_TYPE
     *
     * @param auditType the value for AUDIT.AUDIT_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setAuditType(String auditType) {
        this.auditType = auditType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column AUDIT.DATE
     *
     * @return the value of AUDIT.DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column AUDIT.DATE
     *
     * @param date the value for AUDIT.DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column AUDIT.DESCRIPTION
     *
     * @return the value of AUDIT.DESCRIPTION
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column AUDIT.DESCRIPTION
     *
     * @param description the value for AUDIT.DESCRIPTION
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column AUDIT.ENTITY_TYPE
     *
     * @return the value of AUDIT.ENTITY_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getEntityType() {
        return entityType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column AUDIT.ENTITY_TYPE
     *
     * @param entityType the value for AUDIT.ENTITY_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setEntityType(String entityType) {
        this.entityType = entityType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column AUDIT.OBJECT_ID
     *
     * @return the value of AUDIT.OBJECT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getObjectId() {
        return objectId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column AUDIT.OBJECT_ID
     *
     * @param objectId the value for AUDIT.OBJECT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setObjectId(Long objectId) {
        this.objectId = objectId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column AUDIT.USER
     *
     * @return the value of AUDIT.USER
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column AUDIT.USER
     *
     * @param user the value for AUDIT.USER
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setUser(String user) {
        this.user = user;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column AUDIT.PERSON_ID
     *
     * @return the value of AUDIT.PERSON_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getPersonId() {
        return personId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column AUDIT.PERSON_ID
     *
     * @param personId the value for AUDIT.PERSON_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setPersonId(Long personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column AUDIT.SITE_NAME
     *
     * @return the value of AUDIT.SITE_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getSiteName() {
        return siteName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column AUDIT.SITE_NAME
     *
     * @param siteName the value for AUDIT.SITE_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setSiteName(String siteName) {
        this.siteName = siteName;
    }
}