package com.mpower.domain.model;

public class CodeType {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CODE_TYPE.ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CODE_TYPE.LABEL
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String label;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CODE_TYPE.NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CODE_TYPE.SITE_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String siteName;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CODE_TYPE.ID
     *
     * @return the value of CODE_TYPE.ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CODE_TYPE.ID
     *
     * @param id the value for CODE_TYPE.ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CODE_TYPE.LABEL
     *
     * @return the value of CODE_TYPE.LABEL
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CODE_TYPE.LABEL
     *
     * @param label the value for CODE_TYPE.LABEL
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setLabel(String label) {
        this.label = label;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CODE_TYPE.NAME
     *
     * @return the value of CODE_TYPE.NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CODE_TYPE.NAME
     *
     * @param name the value for CODE_TYPE.NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CODE_TYPE.SITE_NAME
     *
     * @return the value of CODE_TYPE.SITE_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getSiteName() {
        return siteName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CODE_TYPE.SITE_NAME
     *
     * @param siteName the value for CODE_TYPE.SITE_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setSiteName(String siteName) {
        this.siteName = siteName;
    }
}