package com.mpower.domain.model;

public class CommitmentCustomField {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMITMENT_CUSTOM_FIELD.COMMITMENT_CUSTOM_FIELD_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long commitmentCustomFieldId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMITMENT_CUSTOM_FIELD.COMMITMENT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long commitmentId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMITMENT_CUSTOM_FIELD.CUSTOM_FIELD_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long customFieldId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMITMENT_CUSTOM_FIELD.COMMITMENT_CUSTOM_FIELD_ID
     *
     * @return the value of COMMITMENT_CUSTOM_FIELD.COMMITMENT_CUSTOM_FIELD_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getCommitmentCustomFieldId() {
        return commitmentCustomFieldId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMITMENT_CUSTOM_FIELD.COMMITMENT_CUSTOM_FIELD_ID
     *
     * @param commitmentCustomFieldId the value for COMMITMENT_CUSTOM_FIELD.COMMITMENT_CUSTOM_FIELD_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setCommitmentCustomFieldId(Long commitmentCustomFieldId) {
        this.commitmentCustomFieldId = commitmentCustomFieldId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMITMENT_CUSTOM_FIELD.COMMITMENT_ID
     *
     * @return the value of COMMITMENT_CUSTOM_FIELD.COMMITMENT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getCommitmentId() {
        return commitmentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMITMENT_CUSTOM_FIELD.COMMITMENT_ID
     *
     * @param commitmentId the value for COMMITMENT_CUSTOM_FIELD.COMMITMENT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setCommitmentId(Long commitmentId) {
        this.commitmentId = commitmentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMITMENT_CUSTOM_FIELD.CUSTOM_FIELD_ID
     *
     * @return the value of COMMITMENT_CUSTOM_FIELD.CUSTOM_FIELD_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getCustomFieldId() {
        return customFieldId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMITMENT_CUSTOM_FIELD.CUSTOM_FIELD_ID
     *
     * @param customFieldId the value for COMMITMENT_CUSTOM_FIELD.CUSTOM_FIELD_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setCustomFieldId(Long customFieldId) {
        this.customFieldId = customFieldId;
    }
}