package com.mpower.domain.model;

import java.math.BigDecimal;
import java.util.Date;

public class Commitment {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMITMENT.COMMITMENT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long commitmentId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMITMENT.ACKNOWLEDGMENT_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date acknowledgmentDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMITMENT.AMOUNT_PER_GIFT
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private BigDecimal amountPerGift;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMITMENT.AMOUNT_TOTAL
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private BigDecimal amountTotal;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMITMENT.AUTO_PAY
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Boolean autoPay;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMITMENT.CHECK_NUMBER
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Integer checkNumber;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMITMENT.COMMENTS
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String comments;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMITMENT.COMMITMENT_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String commitmentType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMITMENT.CREATE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date createDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMITMENT.CURRENCY_CODE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String currencyCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMITMENT.END_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date endDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMITMENT.FREQUENCY
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String frequency;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMITMENT.LAST_ENTRY_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date lastEntryDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMITMENT.NOTES
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String notes;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMITMENT.PAYMENT_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String paymentType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMITMENT.PLEDGE_CANCEL_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date pledgeCancelDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMITMENT.PLEDGE_CANCEL_REASON
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String pledgeCancelReason;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMITMENT.PLEDGE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date pledgeDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMITMENT.PLEDGE_STATUS
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String pledgeStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMITMENT.PROJECTED_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date projectedDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMITMENT.RECURRING
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Boolean recurring;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMITMENT.SEND_ACKNOWLEDGMENT
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Boolean sendAcknowledgment;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMITMENT.START_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date startDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMITMENT.STATUS
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMITMENT.UPDATE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date updateDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMITMENT.ADDRESS_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long addressId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMITMENT.EMAIL_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long emailId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMITMENT.PAYMENT_SOURCE_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long paymentSourceId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMITMENT.PERSON_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long personId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMITMENT.PHONE_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long phoneId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMITMENT.COMMITMENT_ID
     *
     * @return the value of COMMITMENT.COMMITMENT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getCommitmentId() {
        return commitmentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMITMENT.COMMITMENT_ID
     *
     * @param commitmentId the value for COMMITMENT.COMMITMENT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setCommitmentId(Long commitmentId) {
        this.commitmentId = commitmentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMITMENT.ACKNOWLEDGMENT_DATE
     *
     * @return the value of COMMITMENT.ACKNOWLEDGMENT_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getAcknowledgmentDate() {
        return acknowledgmentDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMITMENT.ACKNOWLEDGMENT_DATE
     *
     * @param acknowledgmentDate the value for COMMITMENT.ACKNOWLEDGMENT_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setAcknowledgmentDate(Date acknowledgmentDate) {
        this.acknowledgmentDate = acknowledgmentDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMITMENT.AMOUNT_PER_GIFT
     *
     * @return the value of COMMITMENT.AMOUNT_PER_GIFT
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public BigDecimal getAmountPerGift() {
        return amountPerGift;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMITMENT.AMOUNT_PER_GIFT
     *
     * @param amountPerGift the value for COMMITMENT.AMOUNT_PER_GIFT
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setAmountPerGift(BigDecimal amountPerGift) {
        this.amountPerGift = amountPerGift;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMITMENT.AMOUNT_TOTAL
     *
     * @return the value of COMMITMENT.AMOUNT_TOTAL
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public BigDecimal getAmountTotal() {
        return amountTotal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMITMENT.AMOUNT_TOTAL
     *
     * @param amountTotal the value for COMMITMENT.AMOUNT_TOTAL
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setAmountTotal(BigDecimal amountTotal) {
        this.amountTotal = amountTotal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMITMENT.AUTO_PAY
     *
     * @return the value of COMMITMENT.AUTO_PAY
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Boolean getAutoPay() {
        return autoPay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMITMENT.AUTO_PAY
     *
     * @param autoPay the value for COMMITMENT.AUTO_PAY
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setAutoPay(Boolean autoPay) {
        this.autoPay = autoPay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMITMENT.CHECK_NUMBER
     *
     * @return the value of COMMITMENT.CHECK_NUMBER
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Integer getCheckNumber() {
        return checkNumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMITMENT.CHECK_NUMBER
     *
     * @param checkNumber the value for COMMITMENT.CHECK_NUMBER
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setCheckNumber(Integer checkNumber) {
        this.checkNumber = checkNumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMITMENT.COMMENTS
     *
     * @return the value of COMMITMENT.COMMENTS
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMITMENT.COMMENTS
     *
     * @param comments the value for COMMITMENT.COMMENTS
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMITMENT.COMMITMENT_TYPE
     *
     * @return the value of COMMITMENT.COMMITMENT_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getCommitmentType() {
        return commitmentType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMITMENT.COMMITMENT_TYPE
     *
     * @param commitmentType the value for COMMITMENT.COMMITMENT_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setCommitmentType(String commitmentType) {
        this.commitmentType = commitmentType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMITMENT.CREATE_DATE
     *
     * @return the value of COMMITMENT.CREATE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMITMENT.CREATE_DATE
     *
     * @param createDate the value for COMMITMENT.CREATE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMITMENT.CURRENCY_CODE
     *
     * @return the value of COMMITMENT.CURRENCY_CODE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMITMENT.CURRENCY_CODE
     *
     * @param currencyCode the value for COMMITMENT.CURRENCY_CODE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMITMENT.END_DATE
     *
     * @return the value of COMMITMENT.END_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMITMENT.END_DATE
     *
     * @param endDate the value for COMMITMENT.END_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMITMENT.FREQUENCY
     *
     * @return the value of COMMITMENT.FREQUENCY
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getFrequency() {
        return frequency;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMITMENT.FREQUENCY
     *
     * @param frequency the value for COMMITMENT.FREQUENCY
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setFrequency(String frequency) {
        this.frequency = frequency;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMITMENT.LAST_ENTRY_DATE
     *
     * @return the value of COMMITMENT.LAST_ENTRY_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getLastEntryDate() {
        return lastEntryDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMITMENT.LAST_ENTRY_DATE
     *
     * @param lastEntryDate the value for COMMITMENT.LAST_ENTRY_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setLastEntryDate(Date lastEntryDate) {
        this.lastEntryDate = lastEntryDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMITMENT.NOTES
     *
     * @return the value of COMMITMENT.NOTES
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMITMENT.NOTES
     *
     * @param notes the value for COMMITMENT.NOTES
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMITMENT.PAYMENT_TYPE
     *
     * @return the value of COMMITMENT.PAYMENT_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMITMENT.PAYMENT_TYPE
     *
     * @param paymentType the value for COMMITMENT.PAYMENT_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMITMENT.PLEDGE_CANCEL_DATE
     *
     * @return the value of COMMITMENT.PLEDGE_CANCEL_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getPledgeCancelDate() {
        return pledgeCancelDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMITMENT.PLEDGE_CANCEL_DATE
     *
     * @param pledgeCancelDate the value for COMMITMENT.PLEDGE_CANCEL_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setPledgeCancelDate(Date pledgeCancelDate) {
        this.pledgeCancelDate = pledgeCancelDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMITMENT.PLEDGE_CANCEL_REASON
     *
     * @return the value of COMMITMENT.PLEDGE_CANCEL_REASON
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getPledgeCancelReason() {
        return pledgeCancelReason;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMITMENT.PLEDGE_CANCEL_REASON
     *
     * @param pledgeCancelReason the value for COMMITMENT.PLEDGE_CANCEL_REASON
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setPledgeCancelReason(String pledgeCancelReason) {
        this.pledgeCancelReason = pledgeCancelReason;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMITMENT.PLEDGE_DATE
     *
     * @return the value of COMMITMENT.PLEDGE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getPledgeDate() {
        return pledgeDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMITMENT.PLEDGE_DATE
     *
     * @param pledgeDate the value for COMMITMENT.PLEDGE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setPledgeDate(Date pledgeDate) {
        this.pledgeDate = pledgeDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMITMENT.PLEDGE_STATUS
     *
     * @return the value of COMMITMENT.PLEDGE_STATUS
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getPledgeStatus() {
        return pledgeStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMITMENT.PLEDGE_STATUS
     *
     * @param pledgeStatus the value for COMMITMENT.PLEDGE_STATUS
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setPledgeStatus(String pledgeStatus) {
        this.pledgeStatus = pledgeStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMITMENT.PROJECTED_DATE
     *
     * @return the value of COMMITMENT.PROJECTED_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getProjectedDate() {
        return projectedDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMITMENT.PROJECTED_DATE
     *
     * @param projectedDate the value for COMMITMENT.PROJECTED_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setProjectedDate(Date projectedDate) {
        this.projectedDate = projectedDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMITMENT.RECURRING
     *
     * @return the value of COMMITMENT.RECURRING
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Boolean getRecurring() {
        return recurring;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMITMENT.RECURRING
     *
     * @param recurring the value for COMMITMENT.RECURRING
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setRecurring(Boolean recurring) {
        this.recurring = recurring;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMITMENT.SEND_ACKNOWLEDGMENT
     *
     * @return the value of COMMITMENT.SEND_ACKNOWLEDGMENT
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Boolean getSendAcknowledgment() {
        return sendAcknowledgment;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMITMENT.SEND_ACKNOWLEDGMENT
     *
     * @param sendAcknowledgment the value for COMMITMENT.SEND_ACKNOWLEDGMENT
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setSendAcknowledgment(Boolean sendAcknowledgment) {
        this.sendAcknowledgment = sendAcknowledgment;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMITMENT.START_DATE
     *
     * @return the value of COMMITMENT.START_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMITMENT.START_DATE
     *
     * @param startDate the value for COMMITMENT.START_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMITMENT.STATUS
     *
     * @return the value of COMMITMENT.STATUS
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMITMENT.STATUS
     *
     * @param status the value for COMMITMENT.STATUS
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMITMENT.UPDATE_DATE
     *
     * @return the value of COMMITMENT.UPDATE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMITMENT.UPDATE_DATE
     *
     * @param updateDate the value for COMMITMENT.UPDATE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMITMENT.ADDRESS_ID
     *
     * @return the value of COMMITMENT.ADDRESS_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMITMENT.ADDRESS_ID
     *
     * @param addressId the value for COMMITMENT.ADDRESS_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMITMENT.EMAIL_ID
     *
     * @return the value of COMMITMENT.EMAIL_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getEmailId() {
        return emailId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMITMENT.EMAIL_ID
     *
     * @param emailId the value for COMMITMENT.EMAIL_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setEmailId(Long emailId) {
        this.emailId = emailId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMITMENT.PAYMENT_SOURCE_ID
     *
     * @return the value of COMMITMENT.PAYMENT_SOURCE_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getPaymentSourceId() {
        return paymentSourceId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMITMENT.PAYMENT_SOURCE_ID
     *
     * @param paymentSourceId the value for COMMITMENT.PAYMENT_SOURCE_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setPaymentSourceId(Long paymentSourceId) {
        this.paymentSourceId = paymentSourceId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMITMENT.PERSON_ID
     *
     * @return the value of COMMITMENT.PERSON_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getPersonId() {
        return personId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMITMENT.PERSON_ID
     *
     * @param personId the value for COMMITMENT.PERSON_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setPersonId(Long personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMITMENT.PHONE_ID
     *
     * @return the value of COMMITMENT.PHONE_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getPhoneId() {
        return phoneId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMITMENT.PHONE_ID
     *
     * @param phoneId the value for COMMITMENT.PHONE_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setPhoneId(Long phoneId) {
        this.phoneId = phoneId;
    }
}