package com.mpower.domain.model;

import java.util.Date;

public class CommunicationHistory {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMUNICATION_HISTORY.COMMUNICATION_HISTORY_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long communicationHistoryId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMUNICATION_HISTORY.COMMUNICATION_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Integer communicationType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMUNICATION_HISTORY.CREATE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date createDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMUNICATION_HISTORY.RECORD_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date recordDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMUNICATION_HISTORY.SYSTEM_GENERATED
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Boolean systemGenerated;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMUNICATION_HISTORY.UPDATE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date updateDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMUNICATION_HISTORY.ASSIGNED_TO
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long assignedTo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMUNICATION_HISTORY.COMMITMENT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long commitmentId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMUNICATION_HISTORY.GIFT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long giftId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMUNICATION_HISTORY.PERSON_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long personId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMUNICATION_HISTORY.RECORDED_BY
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long recordedBy;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMUNICATION_HISTORY.COMMENTS
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String comments;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMUNICATION_HISTORY.COMMUNICATION_HISTORY_ID
     *
     * @return the value of COMMUNICATION_HISTORY.COMMUNICATION_HISTORY_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getCommunicationHistoryId() {
        return communicationHistoryId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMUNICATION_HISTORY.COMMUNICATION_HISTORY_ID
     *
     * @param communicationHistoryId the value for COMMUNICATION_HISTORY.COMMUNICATION_HISTORY_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setCommunicationHistoryId(Long communicationHistoryId) {
        this.communicationHistoryId = communicationHistoryId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMUNICATION_HISTORY.COMMUNICATION_TYPE
     *
     * @return the value of COMMUNICATION_HISTORY.COMMUNICATION_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Integer getCommunicationType() {
        return communicationType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMUNICATION_HISTORY.COMMUNICATION_TYPE
     *
     * @param communicationType the value for COMMUNICATION_HISTORY.COMMUNICATION_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setCommunicationType(Integer communicationType) {
        this.communicationType = communicationType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMUNICATION_HISTORY.CREATE_DATE
     *
     * @return the value of COMMUNICATION_HISTORY.CREATE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMUNICATION_HISTORY.CREATE_DATE
     *
     * @param createDate the value for COMMUNICATION_HISTORY.CREATE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMUNICATION_HISTORY.RECORD_DATE
     *
     * @return the value of COMMUNICATION_HISTORY.RECORD_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getRecordDate() {
        return recordDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMUNICATION_HISTORY.RECORD_DATE
     *
     * @param recordDate the value for COMMUNICATION_HISTORY.RECORD_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setRecordDate(Date recordDate) {
        this.recordDate = recordDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMUNICATION_HISTORY.SYSTEM_GENERATED
     *
     * @return the value of COMMUNICATION_HISTORY.SYSTEM_GENERATED
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Boolean getSystemGenerated() {
        return systemGenerated;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMUNICATION_HISTORY.SYSTEM_GENERATED
     *
     * @param systemGenerated the value for COMMUNICATION_HISTORY.SYSTEM_GENERATED
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setSystemGenerated(Boolean systemGenerated) {
        this.systemGenerated = systemGenerated;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMUNICATION_HISTORY.UPDATE_DATE
     *
     * @return the value of COMMUNICATION_HISTORY.UPDATE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMUNICATION_HISTORY.UPDATE_DATE
     *
     * @param updateDate the value for COMMUNICATION_HISTORY.UPDATE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMUNICATION_HISTORY.ASSIGNED_TO
     *
     * @return the value of COMMUNICATION_HISTORY.ASSIGNED_TO
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getAssignedTo() {
        return assignedTo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMUNICATION_HISTORY.ASSIGNED_TO
     *
     * @param assignedTo the value for COMMUNICATION_HISTORY.ASSIGNED_TO
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setAssignedTo(Long assignedTo) {
        this.assignedTo = assignedTo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMUNICATION_HISTORY.COMMITMENT_ID
     *
     * @return the value of COMMUNICATION_HISTORY.COMMITMENT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getCommitmentId() {
        return commitmentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMUNICATION_HISTORY.COMMITMENT_ID
     *
     * @param commitmentId the value for COMMUNICATION_HISTORY.COMMITMENT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setCommitmentId(Long commitmentId) {
        this.commitmentId = commitmentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMUNICATION_HISTORY.GIFT_ID
     *
     * @return the value of COMMUNICATION_HISTORY.GIFT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getGiftId() {
        return giftId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMUNICATION_HISTORY.GIFT_ID
     *
     * @param giftId the value for COMMUNICATION_HISTORY.GIFT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setGiftId(Long giftId) {
        this.giftId = giftId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMUNICATION_HISTORY.PERSON_ID
     *
     * @return the value of COMMUNICATION_HISTORY.PERSON_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getPersonId() {
        return personId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMUNICATION_HISTORY.PERSON_ID
     *
     * @param personId the value for COMMUNICATION_HISTORY.PERSON_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setPersonId(Long personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMUNICATION_HISTORY.RECORDED_BY
     *
     * @return the value of COMMUNICATION_HISTORY.RECORDED_BY
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getRecordedBy() {
        return recordedBy;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMUNICATION_HISTORY.RECORDED_BY
     *
     * @param recordedBy the value for COMMUNICATION_HISTORY.RECORDED_BY
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setRecordedBy(Long recordedBy) {
        this.recordedBy = recordedBy;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMUNICATION_HISTORY.COMMENTS
     *
     * @return the value of COMMUNICATION_HISTORY.COMMENTS
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMUNICATION_HISTORY.COMMENTS
     *
     * @param comments the value for COMMUNICATION_HISTORY.COMMENTS
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setComments(String comments) {
        this.comments = comments;
    }
}