package com.mpower.domain.model;

public class CommunicationHistoryCustomField {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMUNICATION_HISTORY_CUSTOM_FIELD.COMMUNICATION_HISTORY_CUSTOM_FIELD_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long communicationHistoryCustomFieldId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMUNICATION_HISTORY_CUSTOM_FIELD.COMMUNICATION_HISTORY_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long communicationHistoryId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column COMMUNICATION_HISTORY_CUSTOM_FIELD.CUSTOM_FIELD_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long customFieldId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMUNICATION_HISTORY_CUSTOM_FIELD.COMMUNICATION_HISTORY_CUSTOM_FIELD_ID
     *
     * @return the value of COMMUNICATION_HISTORY_CUSTOM_FIELD.COMMUNICATION_HISTORY_CUSTOM_FIELD_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getCommunicationHistoryCustomFieldId() {
        return communicationHistoryCustomFieldId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMUNICATION_HISTORY_CUSTOM_FIELD.COMMUNICATION_HISTORY_CUSTOM_FIELD_ID
     *
     * @param communicationHistoryCustomFieldId the value for COMMUNICATION_HISTORY_CUSTOM_FIELD.COMMUNICATION_HISTORY_CUSTOM_FIELD_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setCommunicationHistoryCustomFieldId(Long communicationHistoryCustomFieldId) {
        this.communicationHistoryCustomFieldId = communicationHistoryCustomFieldId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMUNICATION_HISTORY_CUSTOM_FIELD.COMMUNICATION_HISTORY_ID
     *
     * @return the value of COMMUNICATION_HISTORY_CUSTOM_FIELD.COMMUNICATION_HISTORY_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getCommunicationHistoryId() {
        return communicationHistoryId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMUNICATION_HISTORY_CUSTOM_FIELD.COMMUNICATION_HISTORY_ID
     *
     * @param communicationHistoryId the value for COMMUNICATION_HISTORY_CUSTOM_FIELD.COMMUNICATION_HISTORY_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setCommunicationHistoryId(Long communicationHistoryId) {
        this.communicationHistoryId = communicationHistoryId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column COMMUNICATION_HISTORY_CUSTOM_FIELD.CUSTOM_FIELD_ID
     *
     * @return the value of COMMUNICATION_HISTORY_CUSTOM_FIELD.CUSTOM_FIELD_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getCustomFieldId() {
        return customFieldId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column COMMUNICATION_HISTORY_CUSTOM_FIELD.CUSTOM_FIELD_ID
     *
     * @param customFieldId the value for COMMUNICATION_HISTORY_CUSTOM_FIELD.CUSTOM_FIELD_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setCustomFieldId(Long customFieldId) {
        this.customFieldId = customFieldId;
    }
}