package com.mpower.domain.model;

public class CustomField {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CUSTOM_FIELD.CUSTOM_FIELD_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long customFieldId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CUSTOM_FIELD.FIELD_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String fieldName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column CUSTOM_FIELD.FIELD_VALUE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String fieldValue;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CUSTOM_FIELD.CUSTOM_FIELD_ID
     *
     * @return the value of CUSTOM_FIELD.CUSTOM_FIELD_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getCustomFieldId() {
        return customFieldId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CUSTOM_FIELD.CUSTOM_FIELD_ID
     *
     * @param customFieldId the value for CUSTOM_FIELD.CUSTOM_FIELD_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setCustomFieldId(Long customFieldId) {
        this.customFieldId = customFieldId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CUSTOM_FIELD.FIELD_NAME
     *
     * @return the value of CUSTOM_FIELD.FIELD_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CUSTOM_FIELD.FIELD_NAME
     *
     * @param fieldName the value for CUSTOM_FIELD.FIELD_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CUSTOM_FIELD.FIELD_VALUE
     *
     * @return the value of CUSTOM_FIELD.FIELD_VALUE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getFieldValue() {
        return fieldValue;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CUSTOM_FIELD.FIELD_VALUE
     *
     * @param fieldValue the value for CUSTOM_FIELD.FIELD_VALUE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setFieldValue(String fieldValue) {
        this.fieldValue = fieldValue;
    }
}