package com.mpower.domain.model;

import java.math.BigDecimal;

public class DistroLine {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column DISTRO_LINE.DISTRO_LINE_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long distroLineId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column DISTRO_LINE.AMOUNT
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private BigDecimal amount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column DISTRO_LINE.MOTIVATION_CODE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String motivationCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column DISTRO_LINE.OTHER_MOTIVATION
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String otherMotivation;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column DISTRO_LINE.PERCENTAGE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private BigDecimal percentage;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column DISTRO_LINE.PROJECT_CODE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String projectCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column DISTRO_LINE.COMMITMENT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long commitmentId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column DISTRO_LINE.GIFT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long giftId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column DISTRO_LINE.DISTRO_LINE_ID
     *
     * @return the value of DISTRO_LINE.DISTRO_LINE_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getDistroLineId() {
        return distroLineId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column DISTRO_LINE.DISTRO_LINE_ID
     *
     * @param distroLineId the value for DISTRO_LINE.DISTRO_LINE_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setDistroLineId(Long distroLineId) {
        this.distroLineId = distroLineId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column DISTRO_LINE.AMOUNT
     *
     * @return the value of DISTRO_LINE.AMOUNT
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column DISTRO_LINE.AMOUNT
     *
     * @param amount the value for DISTRO_LINE.AMOUNT
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column DISTRO_LINE.MOTIVATION_CODE
     *
     * @return the value of DISTRO_LINE.MOTIVATION_CODE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getMotivationCode() {
        return motivationCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column DISTRO_LINE.MOTIVATION_CODE
     *
     * @param motivationCode the value for DISTRO_LINE.MOTIVATION_CODE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setMotivationCode(String motivationCode) {
        this.motivationCode = motivationCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column DISTRO_LINE.OTHER_MOTIVATION
     *
     * @return the value of DISTRO_LINE.OTHER_MOTIVATION
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getOtherMotivation() {
        return otherMotivation;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column DISTRO_LINE.OTHER_MOTIVATION
     *
     * @param otherMotivation the value for DISTRO_LINE.OTHER_MOTIVATION
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setOtherMotivation(String otherMotivation) {
        this.otherMotivation = otherMotivation;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column DISTRO_LINE.PERCENTAGE
     *
     * @return the value of DISTRO_LINE.PERCENTAGE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public BigDecimal getPercentage() {
        return percentage;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column DISTRO_LINE.PERCENTAGE
     *
     * @param percentage the value for DISTRO_LINE.PERCENTAGE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setPercentage(BigDecimal percentage) {
        this.percentage = percentage;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column DISTRO_LINE.PROJECT_CODE
     *
     * @return the value of DISTRO_LINE.PROJECT_CODE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getProjectCode() {
        return projectCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column DISTRO_LINE.PROJECT_CODE
     *
     * @param projectCode the value for DISTRO_LINE.PROJECT_CODE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column DISTRO_LINE.COMMITMENT_ID
     *
     * @return the value of DISTRO_LINE.COMMITMENT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getCommitmentId() {
        return commitmentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column DISTRO_LINE.COMMITMENT_ID
     *
     * @param commitmentId the value for DISTRO_LINE.COMMITMENT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setCommitmentId(Long commitmentId) {
        this.commitmentId = commitmentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column DISTRO_LINE.GIFT_ID
     *
     * @return the value of DISTRO_LINE.GIFT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getGiftId() {
        return giftId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column DISTRO_LINE.GIFT_ID
     *
     * @param giftId the value for DISTRO_LINE.GIFT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setGiftId(Long giftId) {
        this.giftId = giftId;
    }
}