package com.mpower.domain.model;

import java.util.Date;

public class Email {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EMAIL.EMAIL_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long emailId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EMAIL.ACTIVATION_STATUS
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String activationStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EMAIL.COMMENT
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String comment;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EMAIL.CREATE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date createDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EMAIL.EFFECTIVE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date effectiveDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EMAIL.EMAIL_ADDRESS
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String emailAddress;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EMAIL.EMAIL_DISPLAY
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String emailDisplay;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EMAIL.EMAIL_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String emailType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EMAIL.INACTIVE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Boolean inactive;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EMAIL.RECEIVE_CORRESPONDENCE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Boolean receiveCorrespondence;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EMAIL.SEASONAL_END_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date seasonalEndDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EMAIL.SEASONAL_START_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date seasonalStartDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EMAIL.TEMPORARY_END_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date temporaryEndDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EMAIL.TEMPORARY_START_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date temporaryStartDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EMAIL.UPDATE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date updateDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EMAIL.PERSON_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long personId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EMAIL.EMAIL_ID
     *
     * @return the value of EMAIL.EMAIL_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getEmailId() {
        return emailId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EMAIL.EMAIL_ID
     *
     * @param emailId the value for EMAIL.EMAIL_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setEmailId(Long emailId) {
        this.emailId = emailId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EMAIL.ACTIVATION_STATUS
     *
     * @return the value of EMAIL.ACTIVATION_STATUS
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getActivationStatus() {
        return activationStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EMAIL.ACTIVATION_STATUS
     *
     * @param activationStatus the value for EMAIL.ACTIVATION_STATUS
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setActivationStatus(String activationStatus) {
        this.activationStatus = activationStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EMAIL.COMMENT
     *
     * @return the value of EMAIL.COMMENT
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EMAIL.COMMENT
     *
     * @param comment the value for EMAIL.COMMENT
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EMAIL.CREATE_DATE
     *
     * @return the value of EMAIL.CREATE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EMAIL.CREATE_DATE
     *
     * @param createDate the value for EMAIL.CREATE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EMAIL.EFFECTIVE_DATE
     *
     * @return the value of EMAIL.EFFECTIVE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EMAIL.EFFECTIVE_DATE
     *
     * @param effectiveDate the value for EMAIL.EFFECTIVE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EMAIL.EMAIL_ADDRESS
     *
     * @return the value of EMAIL.EMAIL_ADDRESS
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EMAIL.EMAIL_ADDRESS
     *
     * @param emailAddress the value for EMAIL.EMAIL_ADDRESS
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EMAIL.EMAIL_DISPLAY
     *
     * @return the value of EMAIL.EMAIL_DISPLAY
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getEmailDisplay() {
        return emailDisplay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EMAIL.EMAIL_DISPLAY
     *
     * @param emailDisplay the value for EMAIL.EMAIL_DISPLAY
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setEmailDisplay(String emailDisplay) {
        this.emailDisplay = emailDisplay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EMAIL.EMAIL_TYPE
     *
     * @return the value of EMAIL.EMAIL_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getEmailType() {
        return emailType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EMAIL.EMAIL_TYPE
     *
     * @param emailType the value for EMAIL.EMAIL_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setEmailType(String emailType) {
        this.emailType = emailType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EMAIL.INACTIVE
     *
     * @return the value of EMAIL.INACTIVE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Boolean getInactive() {
        return inactive;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EMAIL.INACTIVE
     *
     * @param inactive the value for EMAIL.INACTIVE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setInactive(Boolean inactive) {
        this.inactive = inactive;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EMAIL.RECEIVE_CORRESPONDENCE
     *
     * @return the value of EMAIL.RECEIVE_CORRESPONDENCE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Boolean getReceiveCorrespondence() {
        return receiveCorrespondence;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EMAIL.RECEIVE_CORRESPONDENCE
     *
     * @param receiveCorrespondence the value for EMAIL.RECEIVE_CORRESPONDENCE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setReceiveCorrespondence(Boolean receiveCorrespondence) {
        this.receiveCorrespondence = receiveCorrespondence;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EMAIL.SEASONAL_END_DATE
     *
     * @return the value of EMAIL.SEASONAL_END_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getSeasonalEndDate() {
        return seasonalEndDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EMAIL.SEASONAL_END_DATE
     *
     * @param seasonalEndDate the value for EMAIL.SEASONAL_END_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setSeasonalEndDate(Date seasonalEndDate) {
        this.seasonalEndDate = seasonalEndDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EMAIL.SEASONAL_START_DATE
     *
     * @return the value of EMAIL.SEASONAL_START_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getSeasonalStartDate() {
        return seasonalStartDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EMAIL.SEASONAL_START_DATE
     *
     * @param seasonalStartDate the value for EMAIL.SEASONAL_START_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setSeasonalStartDate(Date seasonalStartDate) {
        this.seasonalStartDate = seasonalStartDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EMAIL.TEMPORARY_END_DATE
     *
     * @return the value of EMAIL.TEMPORARY_END_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getTemporaryEndDate() {
        return temporaryEndDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EMAIL.TEMPORARY_END_DATE
     *
     * @param temporaryEndDate the value for EMAIL.TEMPORARY_END_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setTemporaryEndDate(Date temporaryEndDate) {
        this.temporaryEndDate = temporaryEndDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EMAIL.TEMPORARY_START_DATE
     *
     * @return the value of EMAIL.TEMPORARY_START_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getTemporaryStartDate() {
        return temporaryStartDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EMAIL.TEMPORARY_START_DATE
     *
     * @param temporaryStartDate the value for EMAIL.TEMPORARY_START_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setTemporaryStartDate(Date temporaryStartDate) {
        this.temporaryStartDate = temporaryStartDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EMAIL.UPDATE_DATE
     *
     * @return the value of EMAIL.UPDATE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EMAIL.UPDATE_DATE
     *
     * @param updateDate the value for EMAIL.UPDATE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EMAIL.PERSON_ID
     *
     * @return the value of EMAIL.PERSON_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getPersonId() {
        return personId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EMAIL.PERSON_ID
     *
     * @param personId the value for EMAIL.PERSON_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setPersonId(Long personId) {
        this.personId = personId;
    }
}