package com.mpower.domain.model;

public class FieldCondition {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIELD_CONDITION.CONDITION_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long conditionId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIELD_CONDITION.DEPENDENT_VALUE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String dependentValue;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIELD_CONDITION.DEPENDENT_FIELD_DEFINITION_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String dependentFieldDefinitionId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIELD_CONDITION.DEPENDENT_SECONDARY_FIELD_DEFINITION_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String dependentSecondaryFieldDefinitionId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIELD_CONDITION.FIELD_REQUIRED_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long fieldRequiredId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIELD_CONDITION.VALIDATION_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long validationId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIELD_CONDITION.CONDITION_ID
     *
     * @return the value of FIELD_CONDITION.CONDITION_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getConditionId() {
        return conditionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIELD_CONDITION.CONDITION_ID
     *
     * @param conditionId the value for FIELD_CONDITION.CONDITION_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setConditionId(Long conditionId) {
        this.conditionId = conditionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIELD_CONDITION.DEPENDENT_VALUE
     *
     * @return the value of FIELD_CONDITION.DEPENDENT_VALUE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getDependentValue() {
        return dependentValue;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIELD_CONDITION.DEPENDENT_VALUE
     *
     * @param dependentValue the value for FIELD_CONDITION.DEPENDENT_VALUE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setDependentValue(String dependentValue) {
        this.dependentValue = dependentValue;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIELD_CONDITION.DEPENDENT_FIELD_DEFINITION_ID
     *
     * @return the value of FIELD_CONDITION.DEPENDENT_FIELD_DEFINITION_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getDependentFieldDefinitionId() {
        return dependentFieldDefinitionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIELD_CONDITION.DEPENDENT_FIELD_DEFINITION_ID
     *
     * @param dependentFieldDefinitionId the value for FIELD_CONDITION.DEPENDENT_FIELD_DEFINITION_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setDependentFieldDefinitionId(String dependentFieldDefinitionId) {
        this.dependentFieldDefinitionId = dependentFieldDefinitionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIELD_CONDITION.DEPENDENT_SECONDARY_FIELD_DEFINITION_ID
     *
     * @return the value of FIELD_CONDITION.DEPENDENT_SECONDARY_FIELD_DEFINITION_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getDependentSecondaryFieldDefinitionId() {
        return dependentSecondaryFieldDefinitionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIELD_CONDITION.DEPENDENT_SECONDARY_FIELD_DEFINITION_ID
     *
     * @param dependentSecondaryFieldDefinitionId the value for FIELD_CONDITION.DEPENDENT_SECONDARY_FIELD_DEFINITION_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setDependentSecondaryFieldDefinitionId(String dependentSecondaryFieldDefinitionId) {
        this.dependentSecondaryFieldDefinitionId = dependentSecondaryFieldDefinitionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIELD_CONDITION.FIELD_REQUIRED_ID
     *
     * @return the value of FIELD_CONDITION.FIELD_REQUIRED_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getFieldRequiredId() {
        return fieldRequiredId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIELD_CONDITION.FIELD_REQUIRED_ID
     *
     * @param fieldRequiredId the value for FIELD_CONDITION.FIELD_REQUIRED_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setFieldRequiredId(Long fieldRequiredId) {
        this.fieldRequiredId = fieldRequiredId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIELD_CONDITION.VALIDATION_ID
     *
     * @return the value of FIELD_CONDITION.VALIDATION_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getValidationId() {
        return validationId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIELD_CONDITION.VALIDATION_ID
     *
     * @param validationId the value for FIELD_CONDITION.VALIDATION_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setValidationId(Long validationId) {
        this.validationId = validationId;
    }
}