package com.mpower.domain.model;

public class FieldRequired {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIELD_REQUIRED.FIELD_REQUIRED_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long fieldRequiredId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIELD_REQUIRED.REQUIRED
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Boolean required;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIELD_REQUIRED.SECTION_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String sectionName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIELD_REQUIRED.SITE_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String siteName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIELD_REQUIRED.FIELD_DEFINITION_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String fieldDefinitionId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIELD_REQUIRED.SECONDARY_FIELD_DEFINITION_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String secondaryFieldDefinitionId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIELD_REQUIRED.FIELD_REQUIRED_ID
     *
     * @return the value of FIELD_REQUIRED.FIELD_REQUIRED_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getFieldRequiredId() {
        return fieldRequiredId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIELD_REQUIRED.FIELD_REQUIRED_ID
     *
     * @param fieldRequiredId the value for FIELD_REQUIRED.FIELD_REQUIRED_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setFieldRequiredId(Long fieldRequiredId) {
        this.fieldRequiredId = fieldRequiredId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIELD_REQUIRED.REQUIRED
     *
     * @return the value of FIELD_REQUIRED.REQUIRED
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Boolean getRequired() {
        return required;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIELD_REQUIRED.REQUIRED
     *
     * @param required the value for FIELD_REQUIRED.REQUIRED
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setRequired(Boolean required) {
        this.required = required;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIELD_REQUIRED.SECTION_NAME
     *
     * @return the value of FIELD_REQUIRED.SECTION_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getSectionName() {
        return sectionName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIELD_REQUIRED.SECTION_NAME
     *
     * @param sectionName the value for FIELD_REQUIRED.SECTION_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setSectionName(String sectionName) {
        this.sectionName = sectionName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIELD_REQUIRED.SITE_NAME
     *
     * @return the value of FIELD_REQUIRED.SITE_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getSiteName() {
        return siteName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIELD_REQUIRED.SITE_NAME
     *
     * @param siteName the value for FIELD_REQUIRED.SITE_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setSiteName(String siteName) {
        this.siteName = siteName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIELD_REQUIRED.FIELD_DEFINITION_ID
     *
     * @return the value of FIELD_REQUIRED.FIELD_DEFINITION_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getFieldDefinitionId() {
        return fieldDefinitionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIELD_REQUIRED.FIELD_DEFINITION_ID
     *
     * @param fieldDefinitionId the value for FIELD_REQUIRED.FIELD_DEFINITION_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setFieldDefinitionId(String fieldDefinitionId) {
        this.fieldDefinitionId = fieldDefinitionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIELD_REQUIRED.SECONDARY_FIELD_DEFINITION_ID
     *
     * @return the value of FIELD_REQUIRED.SECONDARY_FIELD_DEFINITION_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getSecondaryFieldDefinitionId() {
        return secondaryFieldDefinitionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIELD_REQUIRED.SECONDARY_FIELD_DEFINITION_ID
     *
     * @param secondaryFieldDefinitionId the value for FIELD_REQUIRED.SECONDARY_FIELD_DEFINITION_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setSecondaryFieldDefinitionId(String secondaryFieldDefinitionId) {
        this.secondaryFieldDefinitionId = secondaryFieldDefinitionId;
    }
}