package com.mpower.domain.model;

public class FieldValidation {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIELD_VALIDATION.VALIDATION_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long validationId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIELD_VALIDATION.VALIDATION_REGEX
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String validationRegex;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIELD_VALIDATION.SECTION_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String sectionName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIELD_VALIDATION.SITE_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String siteName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIELD_VALIDATION.FIELD_DEFINITION_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String fieldDefinitionId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIELD_VALIDATION.SECONDARY_FIELD_DEFINITION_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String secondaryFieldDefinitionId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIELD_VALIDATION.VALIDATION_ID
     *
     * @return the value of FIELD_VALIDATION.VALIDATION_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getValidationId() {
        return validationId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIELD_VALIDATION.VALIDATION_ID
     *
     * @param validationId the value for FIELD_VALIDATION.VALIDATION_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setValidationId(Long validationId) {
        this.validationId = validationId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIELD_VALIDATION.VALIDATION_REGEX
     *
     * @return the value of FIELD_VALIDATION.VALIDATION_REGEX
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getValidationRegex() {
        return validationRegex;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIELD_VALIDATION.VALIDATION_REGEX
     *
     * @param validationRegex the value for FIELD_VALIDATION.VALIDATION_REGEX
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setValidationRegex(String validationRegex) {
        this.validationRegex = validationRegex;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIELD_VALIDATION.SECTION_NAME
     *
     * @return the value of FIELD_VALIDATION.SECTION_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getSectionName() {
        return sectionName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIELD_VALIDATION.SECTION_NAME
     *
     * @param sectionName the value for FIELD_VALIDATION.SECTION_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setSectionName(String sectionName) {
        this.sectionName = sectionName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIELD_VALIDATION.SITE_NAME
     *
     * @return the value of FIELD_VALIDATION.SITE_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getSiteName() {
        return siteName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIELD_VALIDATION.SITE_NAME
     *
     * @param siteName the value for FIELD_VALIDATION.SITE_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setSiteName(String siteName) {
        this.siteName = siteName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIELD_VALIDATION.FIELD_DEFINITION_ID
     *
     * @return the value of FIELD_VALIDATION.FIELD_DEFINITION_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getFieldDefinitionId() {
        return fieldDefinitionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIELD_VALIDATION.FIELD_DEFINITION_ID
     *
     * @param fieldDefinitionId the value for FIELD_VALIDATION.FIELD_DEFINITION_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setFieldDefinitionId(String fieldDefinitionId) {
        this.fieldDefinitionId = fieldDefinitionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIELD_VALIDATION.SECONDARY_FIELD_DEFINITION_ID
     *
     * @return the value of FIELD_VALIDATION.SECONDARY_FIELD_DEFINITION_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getSecondaryFieldDefinitionId() {
        return secondaryFieldDefinitionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIELD_VALIDATION.SECONDARY_FIELD_DEFINITION_ID
     *
     * @param secondaryFieldDefinitionId the value for FIELD_VALIDATION.SECONDARY_FIELD_DEFINITION_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setSecondaryFieldDefinitionId(String secondaryFieldDefinitionId) {
        this.secondaryFieldDefinitionId = secondaryFieldDefinitionId;
    }
}