package com.mpower.domain.model;

public class FieldRelationship {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIELD_RELATIONSHIP.FIELD_RELATIONSHIP_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long fieldRelationshipId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIELD_RELATIONSHIP.CHECK_RECURSION
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Boolean checkRecursion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIELD_RELATIONSHIP.RELATIONSHIP_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String relationshipType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIELD_RELATIONSHIP.DETAIL_FIELD_DEFINITION_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String detailFieldDefinitionId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIELD_RELATIONSHIP.MASTER_FIELD_DEFINITION_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String masterFieldDefinitionId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FIELD_RELATIONSHIP.SITE_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String siteName;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIELD_RELATIONSHIP.FIELD_RELATIONSHIP_ID
     *
     * @return the value of FIELD_RELATIONSHIP.FIELD_RELATIONSHIP_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getFieldRelationshipId() {
        return fieldRelationshipId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIELD_RELATIONSHIP.FIELD_RELATIONSHIP_ID
     *
     * @param fieldRelationshipId the value for FIELD_RELATIONSHIP.FIELD_RELATIONSHIP_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setFieldRelationshipId(Long fieldRelationshipId) {
        this.fieldRelationshipId = fieldRelationshipId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIELD_RELATIONSHIP.CHECK_RECURSION
     *
     * @return the value of FIELD_RELATIONSHIP.CHECK_RECURSION
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Boolean getCheckRecursion() {
        return checkRecursion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIELD_RELATIONSHIP.CHECK_RECURSION
     *
     * @param checkRecursion the value for FIELD_RELATIONSHIP.CHECK_RECURSION
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setCheckRecursion(Boolean checkRecursion) {
        this.checkRecursion = checkRecursion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIELD_RELATIONSHIP.RELATIONSHIP_TYPE
     *
     * @return the value of FIELD_RELATIONSHIP.RELATIONSHIP_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getRelationshipType() {
        return relationshipType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIELD_RELATIONSHIP.RELATIONSHIP_TYPE
     *
     * @param relationshipType the value for FIELD_RELATIONSHIP.RELATIONSHIP_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setRelationshipType(String relationshipType) {
        this.relationshipType = relationshipType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIELD_RELATIONSHIP.DETAIL_FIELD_DEFINITION_ID
     *
     * @return the value of FIELD_RELATIONSHIP.DETAIL_FIELD_DEFINITION_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getDetailFieldDefinitionId() {
        return detailFieldDefinitionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIELD_RELATIONSHIP.DETAIL_FIELD_DEFINITION_ID
     *
     * @param detailFieldDefinitionId the value for FIELD_RELATIONSHIP.DETAIL_FIELD_DEFINITION_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setDetailFieldDefinitionId(String detailFieldDefinitionId) {
        this.detailFieldDefinitionId = detailFieldDefinitionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIELD_RELATIONSHIP.MASTER_FIELD_DEFINITION_ID
     *
     * @return the value of FIELD_RELATIONSHIP.MASTER_FIELD_DEFINITION_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getMasterFieldDefinitionId() {
        return masterFieldDefinitionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIELD_RELATIONSHIP.MASTER_FIELD_DEFINITION_ID
     *
     * @param masterFieldDefinitionId the value for FIELD_RELATIONSHIP.MASTER_FIELD_DEFINITION_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setMasterFieldDefinitionId(String masterFieldDefinitionId) {
        this.masterFieldDefinitionId = masterFieldDefinitionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FIELD_RELATIONSHIP.SITE_NAME
     *
     * @return the value of FIELD_RELATIONSHIP.SITE_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getSiteName() {
        return siteName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FIELD_RELATIONSHIP.SITE_NAME
     *
     * @param siteName the value for FIELD_RELATIONSHIP.SITE_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setSiteName(String siteName) {
        this.siteName = siteName;
    }
}