package com.mpower.domain.model;

import java.math.BigDecimal;
import java.util.Date;

public class Gift {
	
	public Long getId() {return null;}
	public void setId(Long id) {};
	
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column GIFT.GIFT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long giftId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column GIFT.ACKNOWLEDGMENT_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date acknowledgmentDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column GIFT.AMOUNT
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private BigDecimal amount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column GIFT.AUTH_CODE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String authCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column GIFT.CHECK_NUMBER
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Integer checkNumber;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column GIFT.COMMENTS
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String comments;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column GIFT.CURRENCY_CODE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String currencyCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column GIFT.DEDUCTIBLE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Boolean deductible;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column GIFT.DEDUCTIBLE_AMOUNT
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private BigDecimal deductibleAmount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column GIFT.DONATION_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date donationDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column GIFT.ENTRY_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String entryType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column GIFT.ORIGINAL_GIFT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long originalGiftId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column GIFT.PAYMENT_MESSAGE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String paymentMessage;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column GIFT.PAYMENT_STATUS
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String paymentStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column GIFT.PAYMENT_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String paymentType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column GIFT.POSTMARK_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date postmarkDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column GIFT.REFUND_GIFT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long refundGiftId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column GIFT.REFUND_GIFT_TRANSACTION_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date refundGiftTransactionDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column GIFT.SEND_ACKNOWLEDGMENT
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Boolean sendAcknowledgment;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column GIFT.TRANSACTION_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date transactionDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column GIFT.PAYMENT_TXREFNUM
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String paymentTxrefnum;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column GIFT.ADDRESS_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long addressId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column GIFT.COMMITMENT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long commitmentId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column GIFT.EMAIL_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long emailId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column GIFT.PAYMENT_SOURCE_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long paymentSourceId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column GIFT.PERSON_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long personId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column GIFT.PHONE_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long phoneId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column GIFT.GIFT_ID
     *
     * @return the value of GIFT.GIFT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getGiftId() {
        return giftId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column GIFT.GIFT_ID
     *
     * @param giftId the value for GIFT.GIFT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setGiftId(Long giftId) {
        this.giftId = giftId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column GIFT.ACKNOWLEDGMENT_DATE
     *
     * @return the value of GIFT.ACKNOWLEDGMENT_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getAcknowledgmentDate() {
        return acknowledgmentDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column GIFT.ACKNOWLEDGMENT_DATE
     *
     * @param acknowledgmentDate the value for GIFT.ACKNOWLEDGMENT_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setAcknowledgmentDate(Date acknowledgmentDate) {
        this.acknowledgmentDate = acknowledgmentDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column GIFT.AMOUNT
     *
     * @return the value of GIFT.AMOUNT
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column GIFT.AMOUNT
     *
     * @param amount the value for GIFT.AMOUNT
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column GIFT.AUTH_CODE
     *
     * @return the value of GIFT.AUTH_CODE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getAuthCode() {
        return authCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column GIFT.AUTH_CODE
     *
     * @param authCode the value for GIFT.AUTH_CODE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setAuthCode(String authCode) {
        this.authCode = authCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column GIFT.CHECK_NUMBER
     *
     * @return the value of GIFT.CHECK_NUMBER
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Integer getCheckNumber() {
        return checkNumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column GIFT.CHECK_NUMBER
     *
     * @param checkNumber the value for GIFT.CHECK_NUMBER
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setCheckNumber(Integer checkNumber) {
        this.checkNumber = checkNumber;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column GIFT.COMMENTS
     *
     * @return the value of GIFT.COMMENTS
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column GIFT.COMMENTS
     *
     * @param comments the value for GIFT.COMMENTS
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column GIFT.CURRENCY_CODE
     *
     * @return the value of GIFT.CURRENCY_CODE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column GIFT.CURRENCY_CODE
     *
     * @param currencyCode the value for GIFT.CURRENCY_CODE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column GIFT.DEDUCTIBLE
     *
     * @return the value of GIFT.DEDUCTIBLE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Boolean getDeductible() {
        return deductible;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column GIFT.DEDUCTIBLE
     *
     * @param deductible the value for GIFT.DEDUCTIBLE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setDeductible(Boolean deductible) {
        this.deductible = deductible;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column GIFT.DEDUCTIBLE_AMOUNT
     *
     * @return the value of GIFT.DEDUCTIBLE_AMOUNT
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public BigDecimal getDeductibleAmount() {
        return deductibleAmount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column GIFT.DEDUCTIBLE_AMOUNT
     *
     * @param deductibleAmount the value for GIFT.DEDUCTIBLE_AMOUNT
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setDeductibleAmount(BigDecimal deductibleAmount) {
        this.deductibleAmount = deductibleAmount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column GIFT.DONATION_DATE
     *
     * @return the value of GIFT.DONATION_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getDonationDate() {
        return donationDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column GIFT.DONATION_DATE
     *
     * @param donationDate the value for GIFT.DONATION_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setDonationDate(Date donationDate) {
        this.donationDate = donationDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column GIFT.ENTRY_TYPE
     *
     * @return the value of GIFT.ENTRY_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getEntryType() {
        return entryType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column GIFT.ENTRY_TYPE
     *
     * @param entryType the value for GIFT.ENTRY_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setEntryType(String entryType) {
        this.entryType = entryType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column GIFT.ORIGINAL_GIFT_ID
     *
     * @return the value of GIFT.ORIGINAL_GIFT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getOriginalGiftId() {
        return originalGiftId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column GIFT.ORIGINAL_GIFT_ID
     *
     * @param originalGiftId the value for GIFT.ORIGINAL_GIFT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setOriginalGiftId(Long originalGiftId) {
        this.originalGiftId = originalGiftId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column GIFT.PAYMENT_MESSAGE
     *
     * @return the value of GIFT.PAYMENT_MESSAGE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getPaymentMessage() {
        return paymentMessage;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column GIFT.PAYMENT_MESSAGE
     *
     * @param paymentMessage the value for GIFT.PAYMENT_MESSAGE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setPaymentMessage(String paymentMessage) {
        this.paymentMessage = paymentMessage;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column GIFT.PAYMENT_STATUS
     *
     * @return the value of GIFT.PAYMENT_STATUS
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getPaymentStatus() {
        return paymentStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column GIFT.PAYMENT_STATUS
     *
     * @param paymentStatus the value for GIFT.PAYMENT_STATUS
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setPaymentStatus(String paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column GIFT.PAYMENT_TYPE
     *
     * @return the value of GIFT.PAYMENT_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column GIFT.PAYMENT_TYPE
     *
     * @param paymentType the value for GIFT.PAYMENT_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column GIFT.POSTMARK_DATE
     *
     * @return the value of GIFT.POSTMARK_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getPostmarkDate() {
        return postmarkDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column GIFT.POSTMARK_DATE
     *
     * @param postmarkDate the value for GIFT.POSTMARK_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setPostmarkDate(Date postmarkDate) {
        this.postmarkDate = postmarkDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column GIFT.REFUND_GIFT_ID
     *
     * @return the value of GIFT.REFUND_GIFT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getRefundGiftId() {
        return refundGiftId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column GIFT.REFUND_GIFT_ID
     *
     * @param refundGiftId the value for GIFT.REFUND_GIFT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setRefundGiftId(Long refundGiftId) {
        this.refundGiftId = refundGiftId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column GIFT.REFUND_GIFT_TRANSACTION_DATE
     *
     * @return the value of GIFT.REFUND_GIFT_TRANSACTION_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getRefundGiftTransactionDate() {
        return refundGiftTransactionDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column GIFT.REFUND_GIFT_TRANSACTION_DATE
     *
     * @param refundGiftTransactionDate the value for GIFT.REFUND_GIFT_TRANSACTION_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setRefundGiftTransactionDate(Date refundGiftTransactionDate) {
        this.refundGiftTransactionDate = refundGiftTransactionDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column GIFT.SEND_ACKNOWLEDGMENT
     *
     * @return the value of GIFT.SEND_ACKNOWLEDGMENT
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Boolean getSendAcknowledgment() {
        return sendAcknowledgment;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column GIFT.SEND_ACKNOWLEDGMENT
     *
     * @param sendAcknowledgment the value for GIFT.SEND_ACKNOWLEDGMENT
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setSendAcknowledgment(Boolean sendAcknowledgment) {
        this.sendAcknowledgment = sendAcknowledgment;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column GIFT.TRANSACTION_DATE
     *
     * @return the value of GIFT.TRANSACTION_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getTransactionDate() {
        return transactionDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column GIFT.TRANSACTION_DATE
     *
     * @param transactionDate the value for GIFT.TRANSACTION_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column GIFT.PAYMENT_TXREFNUM
     *
     * @return the value of GIFT.PAYMENT_TXREFNUM
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getPaymentTxrefnum() {
        return paymentTxrefnum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column GIFT.PAYMENT_TXREFNUM
     *
     * @param paymentTxrefnum the value for GIFT.PAYMENT_TXREFNUM
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setPaymentTxrefnum(String paymentTxrefnum) {
        this.paymentTxrefnum = paymentTxrefnum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column GIFT.ADDRESS_ID
     *
     * @return the value of GIFT.ADDRESS_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column GIFT.ADDRESS_ID
     *
     * @param addressId the value for GIFT.ADDRESS_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column GIFT.COMMITMENT_ID
     *
     * @return the value of GIFT.COMMITMENT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getCommitmentId() {
        return commitmentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column GIFT.COMMITMENT_ID
     *
     * @param commitmentId the value for GIFT.COMMITMENT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setCommitmentId(Long commitmentId) {
        this.commitmentId = commitmentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column GIFT.EMAIL_ID
     *
     * @return the value of GIFT.EMAIL_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getEmailId() {
        return emailId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column GIFT.EMAIL_ID
     *
     * @param emailId the value for GIFT.EMAIL_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setEmailId(Long emailId) {
        this.emailId = emailId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column GIFT.PAYMENT_SOURCE_ID
     *
     * @return the value of GIFT.PAYMENT_SOURCE_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getPaymentSourceId() {
        return paymentSourceId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column GIFT.PAYMENT_SOURCE_ID
     *
     * @param paymentSourceId the value for GIFT.PAYMENT_SOURCE_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setPaymentSourceId(Long paymentSourceId) {
        this.paymentSourceId = paymentSourceId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column GIFT.PERSON_ID
     *
     * @return the value of GIFT.PERSON_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getPersonId() {
        return personId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column GIFT.PERSON_ID
     *
     * @param personId the value for GIFT.PERSON_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setPersonId(Long personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column GIFT.PHONE_ID
     *
     * @return the value of GIFT.PHONE_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getPhoneId() {
        return phoneId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column GIFT.PHONE_ID
     *
     * @param phoneId the value for GIFT.PHONE_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setPhoneId(Long phoneId) {
        this.phoneId = phoneId;
    }
}