package com.mpower.domain.model;

public class PageAccess {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PAGE_ACCESS.PAGE_ACCESS_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long pageAccessId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PAGE_ACCESS.ACCESS_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String accessType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PAGE_ACCESS.PAGE_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String pageType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PAGE_ACCESS.ROLE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String role;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PAGE_ACCESS.SITE_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String siteName;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PAGE_ACCESS.PAGE_ACCESS_ID
     *
     * @return the value of PAGE_ACCESS.PAGE_ACCESS_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getPageAccessId() {
        return pageAccessId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PAGE_ACCESS.PAGE_ACCESS_ID
     *
     * @param pageAccessId the value for PAGE_ACCESS.PAGE_ACCESS_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setPageAccessId(Long pageAccessId) {
        this.pageAccessId = pageAccessId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PAGE_ACCESS.ACCESS_TYPE
     *
     * @return the value of PAGE_ACCESS.ACCESS_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getAccessType() {
        return accessType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PAGE_ACCESS.ACCESS_TYPE
     *
     * @param accessType the value for PAGE_ACCESS.ACCESS_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setAccessType(String accessType) {
        this.accessType = accessType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PAGE_ACCESS.PAGE_TYPE
     *
     * @return the value of PAGE_ACCESS.PAGE_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getPageType() {
        return pageType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PAGE_ACCESS.PAGE_TYPE
     *
     * @param pageType the value for PAGE_ACCESS.PAGE_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setPageType(String pageType) {
        this.pageType = pageType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PAGE_ACCESS.ROLE
     *
     * @return the value of PAGE_ACCESS.ROLE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PAGE_ACCESS.ROLE
     *
     * @param role the value for PAGE_ACCESS.ROLE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PAGE_ACCESS.SITE_NAME
     *
     * @return the value of PAGE_ACCESS.SITE_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getSiteName() {
        return siteName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PAGE_ACCESS.SITE_NAME
     *
     * @param siteName the value for PAGE_ACCESS.SITE_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setSiteName(String siteName) {
        this.siteName = siteName;
    }
}