package com.mpower.domain.model;

import java.util.Date;

public class Person {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PERSON.PERSON_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long personId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PERSON.CONSTITUENT_INDIVIDUAL_ROLES
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String constituentIndividualRoles;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PERSON.CONSTITUENT_ORGANIZATION_ROLES
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String constituentOrganizationRoles;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PERSON.CONSTITUENT_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String constituentType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PERSON.CREATE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date createDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PERSON.FIRST_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String firstName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PERSON.LAPSED_DONOR
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Boolean lapsedDonor;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PERSON.LAST_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String lastName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PERSON.LEGAL_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String legalName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PERSON.LOGIN_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String loginId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PERSON.MAJOR_DONOR
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Boolean majorDonor;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PERSON.MARITAL_STATUS
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String maritalStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PERSON.MIDDLE_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String middleName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PERSON.NCAIS_CODE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String ncaisCode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PERSON.ORGANIZATION_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String organizationName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PERSON.PREFERRED_PHONE_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String preferredPhoneType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PERSON.RECOGNITION_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String recognitionName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PERSON.SUFFIX
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String suffix;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PERSON.TITLE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String title;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PERSON.UPDATE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date updateDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PERSON.SITE_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String siteName;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PERSON.PERSON_ID
     *
     * @return the value of PERSON.PERSON_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getPersonId() {
        return personId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PERSON.PERSON_ID
     *
     * @param personId the value for PERSON.PERSON_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setPersonId(Long personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PERSON.CONSTITUENT_INDIVIDUAL_ROLES
     *
     * @return the value of PERSON.CONSTITUENT_INDIVIDUAL_ROLES
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getConstituentIndividualRoles() {
        return constituentIndividualRoles;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PERSON.CONSTITUENT_INDIVIDUAL_ROLES
     *
     * @param constituentIndividualRoles the value for PERSON.CONSTITUENT_INDIVIDUAL_ROLES
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setConstituentIndividualRoles(String constituentIndividualRoles) {
        this.constituentIndividualRoles = constituentIndividualRoles;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PERSON.CONSTITUENT_ORGANIZATION_ROLES
     *
     * @return the value of PERSON.CONSTITUENT_ORGANIZATION_ROLES
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getConstituentOrganizationRoles() {
        return constituentOrganizationRoles;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PERSON.CONSTITUENT_ORGANIZATION_ROLES
     *
     * @param constituentOrganizationRoles the value for PERSON.CONSTITUENT_ORGANIZATION_ROLES
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setConstituentOrganizationRoles(String constituentOrganizationRoles) {
        this.constituentOrganizationRoles = constituentOrganizationRoles;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PERSON.CONSTITUENT_TYPE
     *
     * @return the value of PERSON.CONSTITUENT_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getConstituentType() {
        return constituentType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PERSON.CONSTITUENT_TYPE
     *
     * @param constituentType the value for PERSON.CONSTITUENT_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setConstituentType(String constituentType) {
        this.constituentType = constituentType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PERSON.CREATE_DATE
     *
     * @return the value of PERSON.CREATE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PERSON.CREATE_DATE
     *
     * @param createDate the value for PERSON.CREATE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PERSON.FIRST_NAME
     *
     * @return the value of PERSON.FIRST_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PERSON.FIRST_NAME
     *
     * @param firstName the value for PERSON.FIRST_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PERSON.LAPSED_DONOR
     *
     * @return the value of PERSON.LAPSED_DONOR
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Boolean getLapsedDonor() {
        return lapsedDonor;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PERSON.LAPSED_DONOR
     *
     * @param lapsedDonor the value for PERSON.LAPSED_DONOR
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setLapsedDonor(Boolean lapsedDonor) {
        this.lapsedDonor = lapsedDonor;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PERSON.LAST_NAME
     *
     * @return the value of PERSON.LAST_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PERSON.LAST_NAME
     *
     * @param lastName the value for PERSON.LAST_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PERSON.LEGAL_NAME
     *
     * @return the value of PERSON.LEGAL_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getLegalName() {
        return legalName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PERSON.LEGAL_NAME
     *
     * @param legalName the value for PERSON.LEGAL_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setLegalName(String legalName) {
        this.legalName = legalName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PERSON.LOGIN_ID
     *
     * @return the value of PERSON.LOGIN_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PERSON.LOGIN_ID
     *
     * @param loginId the value for PERSON.LOGIN_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PERSON.MAJOR_DONOR
     *
     * @return the value of PERSON.MAJOR_DONOR
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Boolean getMajorDonor() {
        return majorDonor;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PERSON.MAJOR_DONOR
     *
     * @param majorDonor the value for PERSON.MAJOR_DONOR
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setMajorDonor(Boolean majorDonor) {
        this.majorDonor = majorDonor;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PERSON.MARITAL_STATUS
     *
     * @return the value of PERSON.MARITAL_STATUS
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PERSON.MARITAL_STATUS
     *
     * @param maritalStatus the value for PERSON.MARITAL_STATUS
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PERSON.MIDDLE_NAME
     *
     * @return the value of PERSON.MIDDLE_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PERSON.MIDDLE_NAME
     *
     * @param middleName the value for PERSON.MIDDLE_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PERSON.NCAIS_CODE
     *
     * @return the value of PERSON.NCAIS_CODE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getNcaisCode() {
        return ncaisCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PERSON.NCAIS_CODE
     *
     * @param ncaisCode the value for PERSON.NCAIS_CODE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setNcaisCode(String ncaisCode) {
        this.ncaisCode = ncaisCode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PERSON.ORGANIZATION_NAME
     *
     * @return the value of PERSON.ORGANIZATION_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getOrganizationName() {
        return organizationName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PERSON.ORGANIZATION_NAME
     *
     * @param organizationName the value for PERSON.ORGANIZATION_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setOrganizationName(String organizationName) {
        this.organizationName = organizationName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PERSON.PREFERRED_PHONE_TYPE
     *
     * @return the value of PERSON.PREFERRED_PHONE_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getPreferredPhoneType() {
        return preferredPhoneType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PERSON.PREFERRED_PHONE_TYPE
     *
     * @param preferredPhoneType the value for PERSON.PREFERRED_PHONE_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setPreferredPhoneType(String preferredPhoneType) {
        this.preferredPhoneType = preferredPhoneType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PERSON.RECOGNITION_NAME
     *
     * @return the value of PERSON.RECOGNITION_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getRecognitionName() {
        return recognitionName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PERSON.RECOGNITION_NAME
     *
     * @param recognitionName the value for PERSON.RECOGNITION_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setRecognitionName(String recognitionName) {
        this.recognitionName = recognitionName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PERSON.SUFFIX
     *
     * @return the value of PERSON.SUFFIX
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PERSON.SUFFIX
     *
     * @param suffix the value for PERSON.SUFFIX
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PERSON.TITLE
     *
     * @return the value of PERSON.TITLE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PERSON.TITLE
     *
     * @param title the value for PERSON.TITLE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PERSON.UPDATE_DATE
     *
     * @return the value of PERSON.UPDATE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PERSON.UPDATE_DATE
     *
     * @param updateDate the value for PERSON.UPDATE_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PERSON.SITE_NAME
     *
     * @return the value of PERSON.SITE_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getSiteName() {
        return siteName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PERSON.SITE_NAME
     *
     * @param siteName the value for PERSON.SITE_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setSiteName(String siteName) {
        this.siteName = siteName;
    }
}