package com.mpower.domain.model;

public class PersonCustomField {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PERSON_CUSTOM_FIELD.PERSON_CUSTOM_FIELD_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long personCustomFieldId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PERSON_CUSTOM_FIELD.CUSTOM_FIELD_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long customFieldId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PERSON_CUSTOM_FIELD.PERSON_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long personId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PERSON_CUSTOM_FIELD.PERSON_CUSTOM_FIELD_ID
     *
     * @return the value of PERSON_CUSTOM_FIELD.PERSON_CUSTOM_FIELD_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getPersonCustomFieldId() {
        return personCustomFieldId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PERSON_CUSTOM_FIELD.PERSON_CUSTOM_FIELD_ID
     *
     * @param personCustomFieldId the value for PERSON_CUSTOM_FIELD.PERSON_CUSTOM_FIELD_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setPersonCustomFieldId(Long personCustomFieldId) {
        this.personCustomFieldId = personCustomFieldId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PERSON_CUSTOM_FIELD.CUSTOM_FIELD_ID
     *
     * @return the value of PERSON_CUSTOM_FIELD.CUSTOM_FIELD_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getCustomFieldId() {
        return customFieldId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PERSON_CUSTOM_FIELD.CUSTOM_FIELD_ID
     *
     * @param customFieldId the value for PERSON_CUSTOM_FIELD.CUSTOM_FIELD_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setCustomFieldId(Long customFieldId) {
        this.customFieldId = customFieldId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PERSON_CUSTOM_FIELD.PERSON_ID
     *
     * @return the value of PERSON_CUSTOM_FIELD.PERSON_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getPersonId() {
        return personId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PERSON_CUSTOM_FIELD.PERSON_ID
     *
     * @param personId the value for PERSON_CUSTOM_FIELD.PERSON_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setPersonId(Long personId) {
        this.personId = personId;
    }
}