package com.mpower.domain.model;

public class PicklistItem {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PICKLIST_ITEM.PICKLIST_ITEM_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long picklistItemId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PICKLIST_ITEM.DEFAULT_DISPLAY_VALUE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String defaultDisplayValue;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PICKLIST_ITEM.INACTIVE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Boolean inactive;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PICKLIST_ITEM.ITEM_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String itemName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PICKLIST_ITEM.ITEM_ORDER
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Integer itemOrder;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PICKLIST_ITEM.REFERENCE_VALUE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String referenceValue;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PICKLIST_ITEM.SUPPRESS_REFERENCE_VALUE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String suppressReferenceValue;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PICKLIST_ITEM.PICKLIST_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String picklistId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PICKLIST_ITEM.PICKLIST_ITEM_ID
     *
     * @return the value of PICKLIST_ITEM.PICKLIST_ITEM_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getPicklistItemId() {
        return picklistItemId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PICKLIST_ITEM.PICKLIST_ITEM_ID
     *
     * @param picklistItemId the value for PICKLIST_ITEM.PICKLIST_ITEM_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setPicklistItemId(Long picklistItemId) {
        this.picklistItemId = picklistItemId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PICKLIST_ITEM.DEFAULT_DISPLAY_VALUE
     *
     * @return the value of PICKLIST_ITEM.DEFAULT_DISPLAY_VALUE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getDefaultDisplayValue() {
        return defaultDisplayValue;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PICKLIST_ITEM.DEFAULT_DISPLAY_VALUE
     *
     * @param defaultDisplayValue the value for PICKLIST_ITEM.DEFAULT_DISPLAY_VALUE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setDefaultDisplayValue(String defaultDisplayValue) {
        this.defaultDisplayValue = defaultDisplayValue;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PICKLIST_ITEM.INACTIVE
     *
     * @return the value of PICKLIST_ITEM.INACTIVE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Boolean getInactive() {
        return inactive;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PICKLIST_ITEM.INACTIVE
     *
     * @param inactive the value for PICKLIST_ITEM.INACTIVE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setInactive(Boolean inactive) {
        this.inactive = inactive;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PICKLIST_ITEM.ITEM_NAME
     *
     * @return the value of PICKLIST_ITEM.ITEM_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PICKLIST_ITEM.ITEM_NAME
     *
     * @param itemName the value for PICKLIST_ITEM.ITEM_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PICKLIST_ITEM.ITEM_ORDER
     *
     * @return the value of PICKLIST_ITEM.ITEM_ORDER
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Integer getItemOrder() {
        return itemOrder;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PICKLIST_ITEM.ITEM_ORDER
     *
     * @param itemOrder the value for PICKLIST_ITEM.ITEM_ORDER
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setItemOrder(Integer itemOrder) {
        this.itemOrder = itemOrder;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PICKLIST_ITEM.REFERENCE_VALUE
     *
     * @return the value of PICKLIST_ITEM.REFERENCE_VALUE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getReferenceValue() {
        return referenceValue;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PICKLIST_ITEM.REFERENCE_VALUE
     *
     * @param referenceValue the value for PICKLIST_ITEM.REFERENCE_VALUE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setReferenceValue(String referenceValue) {
        this.referenceValue = referenceValue;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PICKLIST_ITEM.SUPPRESS_REFERENCE_VALUE
     *
     * @return the value of PICKLIST_ITEM.SUPPRESS_REFERENCE_VALUE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getSuppressReferenceValue() {
        return suppressReferenceValue;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PICKLIST_ITEM.SUPPRESS_REFERENCE_VALUE
     *
     * @param suppressReferenceValue the value for PICKLIST_ITEM.SUPPRESS_REFERENCE_VALUE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setSuppressReferenceValue(String suppressReferenceValue) {
        this.suppressReferenceValue = suppressReferenceValue;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PICKLIST_ITEM.PICKLIST_ID
     *
     * @return the value of PICKLIST_ITEM.PICKLIST_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getPicklistId() {
        return picklistId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PICKLIST_ITEM.PICKLIST_ID
     *
     * @param picklistId the value for PICKLIST_ITEM.PICKLIST_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setPicklistId(String picklistId) {
        this.picklistId = picklistId;
    }
}