package com.mpower.domain.model;

public class Picklist {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PICKLIST.PICKLIST_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String picklistId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PICKLIST.ENTITY_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String entityType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PICKLIST.MULTISELECT
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Boolean multiselect;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PICKLIST.PICKLIST_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String picklistName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column PICKLIST.SITE_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String siteName;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PICKLIST.PICKLIST_ID
     *
     * @return the value of PICKLIST.PICKLIST_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getPicklistId() {
        return picklistId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PICKLIST.PICKLIST_ID
     *
     * @param picklistId the value for PICKLIST.PICKLIST_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setPicklistId(String picklistId) {
        this.picklistId = picklistId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PICKLIST.ENTITY_TYPE
     *
     * @return the value of PICKLIST.ENTITY_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getEntityType() {
        return entityType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PICKLIST.ENTITY_TYPE
     *
     * @param entityType the value for PICKLIST.ENTITY_TYPE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setEntityType(String entityType) {
        this.entityType = entityType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PICKLIST.MULTISELECT
     *
     * @return the value of PICKLIST.MULTISELECT
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Boolean getMultiselect() {
        return multiselect;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PICKLIST.MULTISELECT
     *
     * @param multiselect the value for PICKLIST.MULTISELECT
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setMultiselect(Boolean multiselect) {
        this.multiselect = multiselect;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PICKLIST.PICKLIST_NAME
     *
     * @return the value of PICKLIST.PICKLIST_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getPicklistName() {
        return picklistName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PICKLIST.PICKLIST_NAME
     *
     * @param picklistName the value for PICKLIST.PICKLIST_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setPicklistName(String picklistName) {
        this.picklistName = picklistName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column PICKLIST.SITE_NAME
     *
     * @return the value of PICKLIST.SITE_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getSiteName() {
        return siteName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column PICKLIST.SITE_NAME
     *
     * @param siteName the value for PICKLIST.SITE_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setSiteName(String siteName) {
        this.siteName = siteName;
    }
}