package com.mpower.domain.model;

public class QueryLookupParam {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column QUERY_LOOKUP_PARAM.QUERY_LOOKUP_PARAM_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long queryLookupParamId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column QUERY_LOOKUP_PARAM.PARAM_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private String paramName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column QUERY_LOOKUP_PARAM.QUERY_LOOKUP_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long queryLookupId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column QUERY_LOOKUP_PARAM.QUERY_LOOKUP_PARAM_ID
     *
     * @return the value of QUERY_LOOKUP_PARAM.QUERY_LOOKUP_PARAM_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getQueryLookupParamId() {
        return queryLookupParamId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column QUERY_LOOKUP_PARAM.QUERY_LOOKUP_PARAM_ID
     *
     * @param queryLookupParamId the value for QUERY_LOOKUP_PARAM.QUERY_LOOKUP_PARAM_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setQueryLookupParamId(Long queryLookupParamId) {
        this.queryLookupParamId = queryLookupParamId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column QUERY_LOOKUP_PARAM.PARAM_NAME
     *
     * @return the value of QUERY_LOOKUP_PARAM.PARAM_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public String getParamName() {
        return paramName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column QUERY_LOOKUP_PARAM.PARAM_NAME
     *
     * @param paramName the value for QUERY_LOOKUP_PARAM.PARAM_NAME
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setParamName(String paramName) {
        this.paramName = paramName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column QUERY_LOOKUP_PARAM.QUERY_LOOKUP_ID
     *
     * @return the value of QUERY_LOOKUP_PARAM.QUERY_LOOKUP_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getQueryLookupId() {
        return queryLookupId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column QUERY_LOOKUP_PARAM.QUERY_LOOKUP_ID
     *
     * @param queryLookupId the value for QUERY_LOOKUP_PARAM.QUERY_LOOKUP_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setQueryLookupId(Long queryLookupId) {
        this.queryLookupId = queryLookupId;
    }
}