package com.mpower.domain.model;

import java.util.Date;

public class RecurringGift {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RECURRING_GIFT.RECURRING_GIFT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long recurringGiftId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RECURRING_GIFT.NEXT_RUN_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Date nextRunDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RECURRING_GIFT.COMMITMENT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    private Long commitmentId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RECURRING_GIFT.RECURRING_GIFT_ID
     *
     * @return the value of RECURRING_GIFT.RECURRING_GIFT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getRecurringGiftId() {
        return recurringGiftId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RECURRING_GIFT.RECURRING_GIFT_ID
     *
     * @param recurringGiftId the value for RECURRING_GIFT.RECURRING_GIFT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setRecurringGiftId(Long recurringGiftId) {
        this.recurringGiftId = recurringGiftId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RECURRING_GIFT.NEXT_RUN_DATE
     *
     * @return the value of RECURRING_GIFT.NEXT_RUN_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Date getNextRunDate() {
        return nextRunDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RECURRING_GIFT.NEXT_RUN_DATE
     *
     * @param nextRunDate the value for RECURRING_GIFT.NEXT_RUN_DATE
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setNextRunDate(Date nextRunDate) {
        this.nextRunDate = nextRunDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RECURRING_GIFT.COMMITMENT_ID
     *
     * @return the value of RECURRING_GIFT.COMMITMENT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public Long getCommitmentId() {
        return commitmentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RECURRING_GIFT.COMMITMENT_ID
     *
     * @param commitmentId the value for RECURRING_GIFT.COMMITMENT_ID
     *
     * @ibatorgenerated Mon Feb 16 12:53:27 CST 2009
     */
    public void setCommitmentId(Long commitmentId) {
        this.commitmentId = commitmentId;
    }
}