/*
 * Copyright (c) 2009. Orange Leap Inc. Active Constituent
 * Relationship Management Platform.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.20 at 05:14:35 PM CDT 
//


package com.orangeleap.tangerine.ws.schema;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for abstractCommunicationEntity complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="abstractCommunicationEntity">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.orangeleap.com/orangeleap/services/1.0}abstractCustomizableEntity">
 *       &lt;sequence>
 *         &lt;element name="activationStatus" type="{http://www.orangeleap.com/orangeleap/services/1.0}activationType" minOccurs="0"/>
 *         &lt;element name="comments" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="effectiveDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="inactive" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="constituentId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="primary" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="receiveCorrespondence" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="seasonalEndDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="seasonalStartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="temporaryEndDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="temporaryStartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="undeliverable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "abstractCommunicationEntity", propOrder = {
        "activationStatus",
        "comments",
        "effectiveDate",
        "inactive",
        "constituentId",
        "primary",
        "receiveCorrespondence",
        "seasonalEndDate",
        "seasonalStartDate",
        "temporaryEndDate",
        "temporaryStartDate",
        "undeliverable"
})
@XmlSeeAlso({
        Address.class,
        Phone.class,
        Email.class
})
public abstract class AbstractCommunicationEntity
        extends AbstractCustomizableEntity {

    protected ActivationType activationStatus;
    protected String comments;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar effectiveDate;
    protected boolean inactive;
    protected long constituentId;
    protected boolean primary;
    protected boolean receiveCorrespondence;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar seasonalEndDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar seasonalStartDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar temporaryEndDate;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar temporaryStartDate;
    protected boolean undeliverable;

    /**
     * Gets the value of the activationStatus property.
     *
     * @return possible object is
     *         {@link ActivationType }
     */
    public ActivationType getActivationStatus() {
        return activationStatus;
    }

    /**
     * Sets the value of the activationStatus property.
     *
     * @param value allowed object is
     *              {@link ActivationType }
     */
    public void setActivationStatus(ActivationType value) {
        this.activationStatus = value;
    }

    /**
     * Gets the value of the comments property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setComments(String value) {
        this.comments = value;
    }

    /**
     * Gets the value of the effectiveDate property.
     *
     * @return possible object is
     *         {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setEffectiveDate(XMLGregorianCalendar value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the inactive property.
     */
    public boolean isInactive() {
        return inactive;
    }

    /**
     * Sets the value of the inactive property.
     */
    public void setInactive(boolean value) {
        this.inactive = value;
    }

    /**
     * Gets the value of the constituentId property.
     */
    public long getConstituentId() {
        return constituentId;
    }

    /**
     * Sets the value of the constituentId property.
     */
    public void setConstituentId(long value) {
        this.constituentId = value;
    }

    /**
     * Gets the value of the primary property.
     */
    public boolean isPrimary() {
        return primary;
    }

    /**
     * Sets the value of the primary property.
     */
    public void setPrimary(boolean value) {
        this.primary = value;
    }

    /**
     * Gets the value of the receiveCorrespondence property.
     */
    public boolean isReceiveCorrespondence() {
        return receiveCorrespondence;
    }

    /**
     * Sets the value of the receiveCorrespondence property.
     */
    public void setReceiveCorrespondence(boolean value) {
        this.receiveCorrespondence = value;
    }

    /**
     * Gets the value of the seasonalEndDate property.
     *
     * @return possible object is
     *         {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getSeasonalEndDate() {
        return seasonalEndDate;
    }

    /**
     * Sets the value of the seasonalEndDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setSeasonalEndDate(XMLGregorianCalendar value) {
        this.seasonalEndDate = value;
    }

    /**
     * Gets the value of the seasonalStartDate property.
     *
     * @return possible object is
     *         {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getSeasonalStartDate() {
        return seasonalStartDate;
    }

    /**
     * Sets the value of the seasonalStartDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setSeasonalStartDate(XMLGregorianCalendar value) {
        this.seasonalStartDate = value;
    }

    /**
     * Gets the value of the temporaryEndDate property.
     *
     * @return possible object is
     *         {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getTemporaryEndDate() {
        return temporaryEndDate;
    }

    /**
     * Sets the value of the temporaryEndDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setTemporaryEndDate(XMLGregorianCalendar value) {
        this.temporaryEndDate = value;
    }

    /**
     * Gets the value of the temporaryStartDate property.
     *
     * @return possible object is
     *         {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getTemporaryStartDate() {
        return temporaryStartDate;
    }

    /**
     * Sets the value of the temporaryStartDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setTemporaryStartDate(XMLGregorianCalendar value) {
        this.temporaryStartDate = value;
    }

    /**
     * Gets the value of the undeliverable property.
     */
    public boolean isUndeliverable() {
        return undeliverable;
    }

    /**
     * Sets the value of the undeliverable property.
     */
    public void setUndeliverable(boolean value) {
        this.undeliverable = value;
    }

}
