//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.26 at 05:18:00 PM CST 
//


package com.orangeleap.tangerine.ws.schema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.orangeleap.tangerine.ws.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.orangeleap.tangerine.ws.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Segmentation }
     * 
     */
    public Segmentation createSegmentation() {
        return new Segmentation();
    }

    /**
     * Create an instance of {@link GetConstituentByIdResponse }
     * 
     */
    public GetConstituentByIdResponse createGetConstituentByIdResponse() {
        return new GetConstituentByIdResponse();
    }

    /**
     * Create an instance of {@link DistributionLine }
     * 
     */
    public DistributionLine createDistributionLine() {
        return new DistributionLine();
    }

    /**
     * Create an instance of {@link Pledge }
     * 
     */
    public Pledge createPledge() {
        return new Pledge();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Site }
     * 
     */
    public Site createSite() {
        return new Site();
    }

    /**
     * Create an instance of {@link GetConstituentGiftResponse }
     * 
     */
    public GetConstituentGiftResponse createGetConstituentGiftResponse() {
        return new GetConstituentGiftResponse();
    }

    /**
     * Create an instance of {@link CustomField }
     * 
     */
    public CustomField createCustomField() {
        return new CustomField();
    }

    /**
     * Create an instance of {@link CommunicationHistory }
     * 
     */
    public CommunicationHistory createCommunicationHistory() {
        return new CommunicationHistory();
    }

    /**
     * Create an instance of {@link BulkAddCommunicationHistoryRequest }
     * 
     */
    public BulkAddCommunicationHistoryRequest createBulkAddCommunicationHistoryRequest() {
        return new BulkAddCommunicationHistoryRequest();
    }

    /**
     * Create an instance of {@link SearchConstituentsResponse }
     * 
     */
    public SearchConstituentsResponse createSearchConstituentsResponse() {
        return new SearchConstituentsResponse();
    }

    /**
     * Create an instance of {@link SaveOrUpdateConstituentRequest }
     * 
     */
    public SaveOrUpdateConstituentRequest createSaveOrUpdateConstituentRequest() {
        return new SaveOrUpdateConstituentRequest();
    }

    /**
     * Create an instance of {@link GetSegmentationListByTypeRequest }
     * 
     */
    public GetSegmentationListByTypeRequest createGetSegmentationListByTypeRequest() {
        return new GetSegmentationListByTypeRequest();
    }

    /**
     * Create an instance of {@link GetSegmentationByNameResponse }
     * 
     */
    public GetSegmentationByNameResponse createGetSegmentationByNameResponse() {
        return new GetSegmentationByNameResponse();
    }

    /**
     * Create an instance of {@link Constituent }
     * 
     */
    public Constituent createConstituent() {
        return new Constituent();
    }

    /**
     * Create an instance of {@link GetSegmentationListResponse }
     * 
     */
    public GetSegmentationListResponse createGetSegmentationListResponse() {
        return new GetSegmentationListResponse();
    }

    /**
     * Create an instance of {@link GetSegmentationByNameRequest }
     * 
     */
    public GetSegmentationByNameRequest createGetSegmentationByNameRequest() {
        return new GetSegmentationByNameRequest();
    }

    /**
     * Create an instance of {@link GetSegmentationListByTypeResponse }
     * 
     */
    public GetSegmentationListByTypeResponse createGetSegmentationListByTypeResponse() {
        return new GetSegmentationListByTypeResponse();
    }

    /**
     * Create an instance of {@link FindConstituentsResponse }
     * 
     */
    public FindConstituentsResponse createFindConstituentsResponse() {
        return new FindConstituentsResponse();
    }

    /**
     * Create an instance of {@link SaveOrUpdateConstituentResponse }
     * 
     */
    public SaveOrUpdateConstituentResponse createSaveOrUpdateConstituentResponse() {
        return new SaveOrUpdateConstituentResponse();
    }

    /**
     * Create an instance of {@link com.orangeleap.tangerine.ws.schema.AbstractCustomizableEntity.CustomFieldMap.Entry }
     * 
     */
    public com.orangeleap.tangerine.ws.schema.AbstractCustomizableEntity.CustomFieldMap.Entry createAbstractCustomizableEntityCustomFieldMapEntry() {
        return new com.orangeleap.tangerine.ws.schema.AbstractCustomizableEntity.CustomFieldMap.Entry();
    }

    /**
     * Create an instance of {@link GetSegmentationListRequest }
     * 
     */
    public GetSegmentationListRequest createGetSegmentationListRequest() {
        return new GetSegmentationListRequest();
    }

    /**
     * Create an instance of {@link com.orangeleap.tangerine.ws.schema.AbstractCustomizableEntity.CustomFieldMap }
     * 
     */
    public com.orangeleap.tangerine.ws.schema.AbstractCustomizableEntity.CustomFieldMap createAbstractCustomizableEntityCustomFieldMap() {
        return new com.orangeleap.tangerine.ws.schema.AbstractCustomizableEntity.CustomFieldMap();
    }

    /**
     * Create an instance of {@link SaveOrUpdateGiftRequest }
     * 
     */
    public SaveOrUpdateGiftRequest createSaveOrUpdateGiftRequest() {
        return new SaveOrUpdateGiftRequest();
    }

    /**
     * Create an instance of {@link GetSegmentationByIdResponse }
     * 
     */
    public GetSegmentationByIdResponse createGetSegmentationByIdResponse() {
        return new GetSegmentationByIdResponse();
    }

    /**
     * Create an instance of {@link GetSegmentationByIdRequest }
     * 
     */
    public GetSegmentationByIdRequest createGetSegmentationByIdRequest() {
        return new GetSegmentationByIdRequest();
    }

    /**
     * Create an instance of {@link GetConstituentByIdRequest }
     * 
     */
    public GetConstituentByIdRequest createGetConstituentByIdRequest() {
        return new GetConstituentByIdRequest();
    }

    /**
     * Create an instance of {@link Gift }
     * 
     */
    public Gift createGift() {
        return new Gift();
    }

    /**
     * Create an instance of {@link SearchConstituentsRequest }
     * 
     */
    public SearchConstituentsRequest createSearchConstituentsRequest() {
        return new SearchConstituentsRequest();
    }

    /**
     * Create an instance of {@link GetConstituentPledgeRequest }
     * 
     */
    public GetConstituentPledgeRequest createGetConstituentPledgeRequest() {
        return new GetConstituentPledgeRequest();
    }

    /**
     * Create an instance of {@link Phone }
     * 
     */
    public Phone createPhone() {
        return new Phone();
    }

    /**
     * Create an instance of {@link FindConstituentsRequest }
     * 
     */
    public FindConstituentsRequest createFindConstituentsRequest() {
        return new FindConstituentsRequest();
    }

    /**
     * Create an instance of {@link GetCommunicationHistoryRequest }
     * 
     */
    public GetCommunicationHistoryRequest createGetCommunicationHistoryRequest() {
        return new GetCommunicationHistoryRequest();
    }

    /**
     * Create an instance of {@link CreateDefaultConstituentResponse }
     * 
     */
    public CreateDefaultConstituentResponse createCreateDefaultConstituentResponse() {
        return new CreateDefaultConstituentResponse();
    }

    /**
     * Create an instance of {@link SaveOrUpdateGiftResponse }
     * 
     */
    public SaveOrUpdateGiftResponse createSaveOrUpdateGiftResponse() {
        return new SaveOrUpdateGiftResponse();
    }

    /**
     * Create an instance of {@link SaveOrUpdatePledgeResponse }
     * 
     */
    public SaveOrUpdatePledgeResponse createSaveOrUpdatePledgeResponse() {
        return new SaveOrUpdatePledgeResponse();
    }

    /**
     * Create an instance of {@link CreateDefaultConstituentRequest }
     * 
     */
    public CreateDefaultConstituentRequest createCreateDefaultConstituentRequest() {
        return new CreateDefaultConstituentRequest();
    }

    /**
     * Create an instance of {@link SaveOrUpdatePledgeRequest }
     * 
     */
    public SaveOrUpdatePledgeRequest createSaveOrUpdatePledgeRequest() {
        return new SaveOrUpdatePledgeRequest();
    }

    /**
     * Create an instance of {@link Email }
     * 
     */
    public Email createEmail() {
        return new Email();
    }

    /**
     * Create an instance of {@link GetConstituentGiftRequest }
     * 
     */
    public GetConstituentGiftRequest createGetConstituentGiftRequest() {
        return new GetConstituentGiftRequest();
    }

    /**
     * Create an instance of {@link PaymentSource }
     * 
     */
    public PaymentSource createPaymentSource() {
        return new PaymentSource();
    }

    /**
     * Create an instance of {@link GetConstituentPledgeResponse }
     * 
     */
    public GetConstituentPledgeResponse createGetConstituentPledgeResponse() {
        return new GetConstituentPledgeResponse();
    }

    /**
     * Create an instance of {@link GetCommunicationHistoryResponse }
     * 
     */
    public GetCommunicationHistoryResponse createGetCommunicationHistoryResponse() {
        return new GetCommunicationHistoryResponse();
    }

    /**
     * Create an instance of {@link AddCommunicationHistoryRequest }
     * 
     */
    public AddCommunicationHistoryRequest createAddCommunicationHistoryRequest() {
        return new AddCommunicationHistoryRequest();
    }

}
