//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.01 at 03:59:42 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.orangeleap.com/orangeleap/services/1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.orangeleap.tangerine.ws.schema;
