
/*
 * 
 */

package com.orangeleap.theguru.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.3
 * Wed Oct 14 16:04:49 CDT 2009
 * Generated source version: 2.2.3
 * 
 */


@WebServiceClient(name = "OrangeLeapService", 
                  wsdlLocation = "file:/var/folders/Je/JeiE3Q8HFN07UhvhV5uZqU+++TI/-Tmp-/tempdir1350386514181150513.tmp/orangeleap_1.wsdl",
                  targetNamespace = "http://www.orangeleap.com/orangeleap/services/1.0") 
public class OrangeLeapService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.orangeleap.com/orangeleap/services/1.0", "OrangeLeapService");
    public final static QName OrangeLeapPort = new QName("http://www.orangeleap.com/orangeleap/services/1.0", "OrangeLeapPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/var/folders/Je/JeiE3Q8HFN07UhvhV5uZqU+++TI/-Tmp-/tempdir1350386514181150513.tmp/orangeleap_1.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/var/folders/Je/JeiE3Q8HFN07UhvhV5uZqU+++TI/-Tmp-/tempdir1350386514181150513.tmp/orangeleap_1.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public OrangeLeapService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrangeLeapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrangeLeapService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns OrangeLeap
     */
    @WebEndpoint(name = "OrangeLeapPort")
    public OrangeLeap getOrangeLeapPort() {
        return super.getPort(OrangeLeapPort, OrangeLeap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrangeLeap
     */
    @WebEndpoint(name = "OrangeLeapPort")
    public OrangeLeap getOrangeLeapPort(WebServiceFeature... features) {
        return super.getPort(OrangeLeapPort, OrangeLeap.class, features);
    }

}
