-- ROLE_ADMIN view of constituent search
--INSERT INTO SECTION_DEFINITION (SECTION_DEFINITION_ID, PAGE_TYPE, SECTION_NAME, DEFAULT_LABEL, SECTION_ORDER, LAYOUT_TYPE, ROLE, SITE_NAME) VALUES (15, 'constituentSearch', 'constituentSearch.searchInfo', 'Search People', 1, 'TWO_COLUMN', 'ROLE_ADMIN', 'company1');


-- ROLE_MANAGER view of constituent search
--INSERT INTO SECTION_DEFINITION (SECTION_DEFINITION_ID, PAGE_TYPE, SECTION_NAME, DEFAULT_LABEL, SECTION_ORDER, LAYOUT_TYPE, ROLE, SITE_NAME) VALUES (16, 'constituentSearch', 'constituentSearch.searchInfo', 'Search People', 1, 'TWO_COLUMN', 'ROLE_MANAGER', 'company1');
--INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, SECONDARY_FIELD_DEFINITION_ID, FIELD_ORDER, SITE_NAME) VALUES (16, 'constituent.addressMap[home]', 'address.postalCode', 0, 'company1');
--INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, SECONDARY_FIELD_DEFINITION_ID, FIELD_ORDER, SITE_NAME) VALUES (16, 'constituent.addressMap[home]', 'address.addressLine1', 0, 'company1');
--INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, SECONDARY_FIELD_DEFINITION_ID, FIELD_ORDER, SITE_NAME) VALUES (16, 'constituent.addressMap[home]', 'address.city', 0, 'company1');
--INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, SECONDARY_FIELD_DEFINITION_ID, FIELD_ORDER, SITE_NAME) VALUES (16, 'constituent.addressMap[home]', 'address.stateProvince', 0, 'company1');
--INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER, SITE_NAME) VALUES (16, 'constituent.phoneMap[generic]', 0, 'company1');



-- ROLE_USER view of constituent search
--INSERT INTO SECTION_DEFINITION (SECTION_DEFINITION_ID, PAGE_TYPE, SECTION_NAME, DEFAULT_LABEL, SECTION_ORDER, LAYOUT_TYPE, ROLE, SITE_NAME) VALUES (17, 'constituentSearch', 'constituentSearch.searchInfo', 'Search People', 1, 'TWO_COLUMN', 'ROLE_USER', 'company1');
--INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER, SITE_NAME) VALUES (17, 'constituent.organizationName', 0, 'company1');
--INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER, SITE_NAME) VALUES (17, 'constituent.email', 0, 'company1');
--INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, SECONDARY_FIELD_DEFINITION_ID, FIELD_ORDER, SITE_NAME) VALUES (17, 'constituent.addressMap[home]', 'address.postalCode', 0, 'company1');
--INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, SECONDARY_FIELD_DEFINITION_ID, FIELD_ORDER, SITE_NAME) VALUES (17, 'constituent.addressMap[home]', 'address.addressLine1', 0, 'company1');
--INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, SECONDARY_FIELD_DEFINITION_ID, FIELD_ORDER, SITE_NAME) VALUES (17, 'constituent.addressMap[home]', 'address.city', 0, 'company1');
--INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, SECONDARY_FIELD_DEFINITION_ID, FIELD_ORDER, SITE_NAME) VALUES (17, 'constituent.addressMap[home]', 'address.stateProvince', 0, 'company1');
--INSERT INTO SECTION_FIELD (SECTION_DEFINITION_ID, FIELD_DEFINITION_ID, FIELD_ORDER, SITE_NAME) VALUES (17, 'constituent.phoneMap[generic]', 0, 'company1');
