<PC3LineItem>
	<PC3DtlIndex>[% PC3DtlIndex %]</PC3DtlIndex>
	<PC3DtlDesc>[% PC3DtlDesc= %]</PC3DtlDesc>
	<PC3DtlProdCd>[% PC3DtlProdCd= %]</PC3DtlProdCd>
	<PC3DtlQty>[% PC3DtlQty= %]</PC3DtlQty>
	<PC3DtlUOM>[% PC3DtlUOM= %]</PC3DtlUOM>
	<PC3DtlTaxAmt>[% PC3DtlTaxAmt= %]</PC3DtlTaxAmt>
	<PC3DtlTaxRate>[% PC3DtlTaxRate= %]</PC3DtlTaxRate>
	<PC3Dtllinetot>[% PC3Dtllinetot= %]</PC3Dtllinetot>
	<PC3DtlDisc>[% PC3DtlDisc= %]</PC3DtlDisc>
	<PC3DtlCommCd>[% PC3DtlCommCd= %]</PC3DtlCommCd>
	<PC3DtlUnitCost>[% PC3DtlUnitCost= %]</PC3DtlUnitCost>
	<PC3DtlGrossNet>[% PC3DtlGrossNet= %]</PC3DtlGrossNet>
	<PC3DtlTaxType>[% PC3DtlTaxType= %]</PC3DtlTaxType>
	<PC3DtlDiscInd>[% PC3DtlDiscInd= %]</PC3DtlDiscInd>
	<PC3DtlDebitInd>[% PC3DtlDebitInd= %]</PC3DtlDebitInd>
</PC3LineItem>
