/*
V7 Schema changes
*********************************************************************
*/
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;


ALTER TABLE THEGURU_SEGMENTATION_RESULT 
	DROP INDEX THEGURU_SEGMENTATION_RESULT_REPORT_ID_IDX;

ALTER TABLE THEGURU_SEGMENTATION_RESULT 
	ADD INDEX `THEGURU_SEGMENTATION_RESULT_REPORT_ID_IDX` (`REPORT_ID`,`ENTITY_ID`);
	

	
	
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;



