/*
V7 Schema changes
*********************************************************************
*/
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;


ALTER TABLE THEGURU_SEGMENTATION_RESULT 
	DROP INDEX THEGURU_SEGMENTATION_RESULT_REPORT_ID_IDX;

ALTER TABLE THEGURU_SEGMENTATION_RESULT 
	ADD INDEX `THEGURU_SEGMENTATION_RESULT_REPORT_ID_IDX` (`REPORT_ID`,`ENTITY_ID`);
	

DROP TABLE IF EXISTS `BACKGROUND`;

CREATE TABLE `BACKGROUND` (
`BACKGROUND_ID` bigint(20) NOT NULL auto_increment,
`COMMENTS` text,
`CREATE_DATE` datetime default NULL,
`UPDATE_DATE` datetime default NULL,
`CONSTITUENT_ID` bigint(20) default NULL,
PRIMARY KEY  (`BACKGROUND_ID`),
KEY `FK_BACKGROUND_CONSTITUENT` (`CONSTITUENT_ID`),
CONSTRAINT `FK_BACKGROUND_CONSTITUENT` FOREIGN KEY (`CONSTITUENT_ID`) REFERENCES `CONSTITUENT` (`CONSTITUENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


	
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;



