/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


SET AUTOCOMMIT = 0;


DELETE FROM jv.PICKLIST_ITEM
WHERE ITEM_NAME = 'check'
AND PICKLIST_ID IN (SELECT PICKLIST_ID FROM jv.PICKLIST WHERE PICKLIST_NAME_ID = 'paymentSource.paymentType' AND PICKLIST_NAME = 'paymentType') order by PICKLIST_ID, ITEM_ORDER;


UPDATE jv.SECTION_DEFINITION SET SECTION_ORDER = 7 WHERE SECTION_DEFINITION_ID = (SELECT SECTION_DEFINITION_ID FROM jv.SECTION_DEFINITION WHERE SECTION_NAME='gift.donation' AND PAGE_TYPE='gift') AND SECTION_ORDER = 6;

COMMIT;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
