-- Create recurring gifts and pledges
-- Must be executed AFTER CONSTITUENT insertions (personSetup.sql)

INSERT INTO RECURRING_GIFT (COMMENTS, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('', 1000, 1, false);
INSERT INTO RECURRING_GIFT (COMMENTS, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('', 1000, 1, false);
INSERT INTO RECURRING_GIFT (COMMENTS, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('', 1000, 1, false);
INSERT INTO RECURRING_GIFT (COMMENTS, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('', 1000, 1, false);
INSERT INTO RECURRING_GIFT (COMMENTS, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('', 1000, 1, false);
INSERT INTO RECURRING_GIFT (COMMENTS, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('', 1000, 2, false);
INSERT INTO RECURRING_GIFT (COMMENTS, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('', 1000, 2, false);
INSERT INTO RECURRING_GIFT (COMMENTS, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('', 1000, 2, false);
INSERT INTO RECURRING_GIFT (COMMENTS, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('', 1000, 2, false);
INSERT INTO RECURRING_GIFT (COMMENTS, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('', 1000, 2, false);
INSERT INTO RECURRING_GIFT (COMMENTS, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('', 1000, 3, false);
INSERT INTO RECURRING_GIFT (COMMENTS, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('', 1000, 3, false);
INSERT INTO RECURRING_GIFT (COMMENTS, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('', 1000, 3, false);
INSERT INTO RECURRING_GIFT (COMMENTS, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('', 1000, 3, false);
INSERT INTO RECURRING_GIFT (COMMENTS, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('', 1000, 3, false);
INSERT INTO RECURRING_GIFT (COMMENTS, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('', 1000, 3, false);
INSERT INTO RECURRING_GIFT (COMMENTS, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('', 1000, 4, false);
INSERT INTO RECURRING_GIFT (COMMENTS, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('', 1000, 4, false);
INSERT INTO RECURRING_GIFT (COMMENTS, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('', 1000, 4, false);
INSERT INTO RECURRING_GIFT (COMMENTS, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('', 1000, 5, false);
INSERT INTO RECURRING_GIFT (COMMENTS, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('', 1000, 5, false);
INSERT INTO RECURRING_GIFT (COMMENTS, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('', 1000, 5, false);

INSERT INTO PLEDGE (COMMENTS, AMOUNT_PER_GIFT, AMOUNT_TOTAL, CONSTITUENT_ID,  PLEDGE_DATE, PLEDGE_STATUS) VALUES ('', 10, 100, 1, adddate(now(), -123), 'pending');
INSERT INTO PLEDGE (COMMENTS, AMOUNT_PER_GIFT, AMOUNT_TOTAL, CONSTITUENT_ID,  PLEDGE_DATE, PLEDGE_STATUS) VALUES ('', 20, 200, 2, adddate(now(), -93), 'pending');
INSERT INTO PLEDGE (COMMENTS, AMOUNT_PER_GIFT, AMOUNT_TOTAL, CONSTITUENT_ID,  PLEDGE_DATE, PLEDGE_STATUS) VALUES ('', 30, 300, 3, adddate(now(), -63), 'pending');
INSERT INTO PLEDGE (COMMENTS, AMOUNT_PER_GIFT, AMOUNT_TOTAL, CONSTITUENT_ID,  PLEDGE_DATE, PLEDGE_STATUS) VALUES ('', 40, 400, 4, adddate(now(), -33), 'pending');
INSERT INTO PLEDGE (COMMENTS, AMOUNT_PER_GIFT, AMOUNT_TOTAL, CONSTITUENT_ID,  PLEDGE_DATE, PLEDGE_STATUS) VALUES ('', 50, 500, 5, adddate(now(), -1), 'pending');