-- Create commitments
-- Must be executed AFTER PERSON insertions (personSetup.sql)

INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, PERSON_ID, DEDUCTIBLE, AUTO_PAY) VALUES ('RECURRING_GIFT', 'Thank you for your ministry', 1000, 1, false, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, PERSON_ID, DEDUCTIBLE, AUTO_PAY) VALUES ('RECURRING_GIFT', 'Thank you for your ministry', 1000, 1, false, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, PERSON_ID, DEDUCTIBLE, AUTO_PAY) VALUES ('RECURRING_GIFT', 'Thank you for your ministry', 1000, 1, false, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, PERSON_ID, DEDUCTIBLE, AUTO_PAY) VALUES ('RECURRING_GIFT', 'Thank you for your ministry', 1000, 1, false, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, PERSON_ID, DEDUCTIBLE, AUTO_PAY) VALUES ('RECURRING_GIFT', 'Thank you for your ministry', 1000, 1, false, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, PERSON_ID, DEDUCTIBLE, AUTO_PAY) VALUES ('RECURRING_GIFT', 'Thank you for your ministry', 1000, 2, false, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, PERSON_ID, DEDUCTIBLE, AUTO_PAY) VALUES ('RECURRING_GIFT', 'Thank you for your ministry', 1000, 2, false, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, PERSON_ID, DEDUCTIBLE, AUTO_PAY) VALUES ('RECURRING_GIFT', 'Thank you for your ministry', 1000, 2, false, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, PERSON_ID, DEDUCTIBLE, AUTO_PAY) VALUES ('RECURRING_GIFT', 'Thank you for your ministry', 1000, 2, false, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, PERSON_ID, DEDUCTIBLE, AUTO_PAY) VALUES ('RECURRING_GIFT', 'Thank you for your ministry', 1000, 2, false, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, PERSON_ID, DEDUCTIBLE, AUTO_PAY) VALUES ('RECURRING_GIFT', 'Thank you for your ministry', 1000, 3, false, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, PERSON_ID, DEDUCTIBLE, AUTO_PAY) VALUES ('RECURRING_GIFT', 'Thank you for your ministry', 1000, 3, false, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, PERSON_ID, DEDUCTIBLE, AUTO_PAY) VALUES ('RECURRING_GIFT', 'Thank you for your ministry', 1000, 3, false, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, PERSON_ID, DEDUCTIBLE, AUTO_PAY) VALUES ('RECURRING_GIFT', 'Thank you for your ministry', 1000, 3, false, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, PERSON_ID, DEDUCTIBLE, AUTO_PAY) VALUES ('RECURRING_GIFT', 'Thank you for your ministry', 1000, 3, false, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, PERSON_ID, DEDUCTIBLE, AUTO_PAY) VALUES ('RECURRING_GIFT', 'Thank you for your ministry', 1000, 3, false, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, PERSON_ID, DEDUCTIBLE, AUTO_PAY) VALUES ('RECURRING_GIFT', 'Thank you for your ministry', 1000, 4, false, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, PERSON_ID, DEDUCTIBLE, AUTO_PAY) VALUES ('RECURRING_GIFT', 'Thank you for your ministry', 1000, 4, false, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, PERSON_ID, DEDUCTIBLE, AUTO_PAY) VALUES ('RECURRING_GIFT', 'Thank you for your ministry', 1000, 4, false, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, PERSON_ID, DEDUCTIBLE, AUTO_PAY) VALUES ('RECURRING_GIFT', 'Thank you for your ministry', 1000, 5, false, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, PERSON_ID, DEDUCTIBLE, AUTO_PAY) VALUES ('RECURRING_GIFT', 'Thank you for your ministry', 1000, 5, false, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, PERSON_ID, DEDUCTIBLE, AUTO_PAY) VALUES ('RECURRING_GIFT', 'Thank you for your ministry', 1000, 5, false, false);