-- Create commitments
-- Must be executed AFTER CONSTITUENT insertions (personSetup.sql)

INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('RECURRING_GIFT', '', 1000, 1, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('RECURRING_GIFT', '', 1000, 1, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('RECURRING_GIFT', '', 1000, 1, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('RECURRING_GIFT', '', 1000, 1, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('RECURRING_GIFT', '', 1000, 1, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('RECURRING_GIFT', '', 1000, 2, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('RECURRING_GIFT', '', 1000, 2, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('RECURRING_GIFT', '', 1000, 2, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('RECURRING_GIFT', '', 1000, 2, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('RECURRING_GIFT', '', 1000, 2, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('RECURRING_GIFT', '', 1000, 3, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('RECURRING_GIFT', '', 1000, 3, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('RECURRING_GIFT', '', 1000, 3, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('RECURRING_GIFT', '', 1000, 3, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('RECURRING_GIFT', '', 1000, 3, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('RECURRING_GIFT', '', 1000, 3, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('RECURRING_GIFT', '', 1000, 4, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('RECURRING_GIFT', '', 1000, 4, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('RECURRING_GIFT', '', 1000, 4, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('RECURRING_GIFT', '', 1000, 5, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('RECURRING_GIFT', '', 1000, 5, false);
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, CONSTITUENT_ID,  AUTO_PAY) VALUES ('RECURRING_GIFT', '', 1000, 5, false);

INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, AMOUNT_TOTAL, CONSTITUENT_ID,  AUTO_PAY, PLEDGE_DATE) VALUES ('PLEDGE', '', 10, 100, 1, false, adddate(now(), -123));
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, AMOUNT_TOTAL, CONSTITUENT_ID,  AUTO_PAY, PLEDGE_DATE) VALUES ('PLEDGE', '', 20, 200, 2, false, adddate(now(), -93));
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, AMOUNT_TOTAL, CONSTITUENT_ID,  AUTO_PAY, PLEDGE_DATE) VALUES ('PLEDGE', '', 30, 300, 3, false, adddate(now(), -63));
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, AMOUNT_TOTAL, CONSTITUENT_ID,  AUTO_PAY, PLEDGE_DATE) VALUES ('PLEDGE', '', 40, 400, 4, false, adddate(now(), -33));
INSERT INTO COMMITMENT (COMMITMENT_TYPE, NOTES, AMOUNT_PER_GIFT, AMOUNT_TOTAL, CONSTITUENT_ID,  AUTO_PAY, PLEDGE_DATE) VALUES ('PLEDGE', '', 50, 500, 5, false, adddate(now(), -1));