-- Create gifts
-- Must be executed AFTER PERSON insertions (personSetup.sql)

INSERT INTO GIFT (COMMENTS, VALUE, PAYMENT_TYPE, TRANSACTION_DATE, PERSON_ID) VALUES ('Thank you for your ministry', 1000, 'Cash', '2007-06-01 10:50:57', 1);
INSERT INTO GIFT (COMMENTS, VALUE, PAYMENT_TYPE, TRANSACTION_DATE, PERSON_ID) VALUES ('Thank you for your ministry', 1000, 'Cash', '2007-06-01 10:50:57', 1);
INSERT INTO GIFT (COMMENTS, VALUE, PAYMENT_TYPE, TRANSACTION_DATE, PERSON_ID) VALUES ('Thank you for your ministry', 1000, 'Cash', '2007-06-01 10:50:57', 1);
INSERT INTO GIFT (COMMENTS, VALUE, PAYMENT_TYPE, TRANSACTION_DATE, PERSON_ID) VALUES ('Thank you for your ministry', 1000, 'Cash', '2007-06-01 10:50:57', 1);
INSERT INTO GIFT (COMMENTS, VALUE, PAYMENT_TYPE, TRANSACTION_DATE, PERSON_ID) VALUES ('Thank you for your ministry', 1000, 'Cash', '2007-06-01 10:50:57', 1);
INSERT INTO GIFT (COMMENTS, VALUE, PAYMENT_TYPE, TRANSACTION_DATE, PERSON_ID) VALUES ('Thank you for your ministry', 1000, 'Cash', current_timestamp(), 2);
INSERT INTO GIFT (COMMENTS, VALUE, PAYMENT_TYPE, TRANSACTION_DATE, PERSON_ID) VALUES ('Thank you for your ministry', 1000, 'Cash', current_timestamp(), 2);
INSERT INTO GIFT (COMMENTS, VALUE, PAYMENT_TYPE, TRANSACTION_DATE, PERSON_ID) VALUES ('Thank you for your ministry', 1000, 'Cash', current_timestamp(), 2);
INSERT INTO GIFT (COMMENTS, VALUE, PAYMENT_TYPE, TRANSACTION_DATE, PERSON_ID) VALUES ('Thank you for your ministry', 1000, 'Cash', current_timestamp(), 2);
INSERT INTO GIFT (COMMENTS, VALUE, PAYMENT_TYPE, TRANSACTION_DATE, PERSON_ID) VALUES ('Thank you for your ministry', 1000, 'Cash', current_timestamp(), 2);
INSERT INTO GIFT (COMMENTS, VALUE, PAYMENT_TYPE, TRANSACTION_DATE, PERSON_ID) VALUES ('Thank you for your ministry', 1000, 'Cash', '2008-06-01 10:50:57', 3);
INSERT INTO GIFT (COMMENTS, VALUE, PAYMENT_TYPE, TRANSACTION_DATE, PERSON_ID) VALUES ('Thank you for your ministry', 1000, 'Cash', '2008-06-01 10:50:57', 3);
INSERT INTO GIFT (COMMENTS, VALUE, PAYMENT_TYPE, TRANSACTION_DATE, PERSON_ID) VALUES ('Thank you for your ministry', 1000, 'Cash', '2008-06-01 10:50:57', 3);
INSERT INTO GIFT (COMMENTS, VALUE, PAYMENT_TYPE, TRANSACTION_DATE, PERSON_ID) VALUES ('Thank you for your ministry', 1000, 'Cash', '2008-06-01 10:50:57', 3);
INSERT INTO GIFT (COMMENTS, VALUE, PAYMENT_TYPE, TRANSACTION_DATE, PERSON_ID) VALUES ('Thank you for your ministry', 1000, 'Cash', '2008-06-01 10:50:57', 3);