-- Create a list of people in the database
-- Executing a list of people must come BEFORE executing:
	-- PERSON_ADDRESS insertions (addressSetup.sql)
	-- PERSON_PHONE insertions (phoneSetup.sql)
	-- GIFTS insertions (giftSetup.sql)
	
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Mr.', 'Adam', 'Jay', 'Smith', 'thepatriarch@gmail.com', null, 'Single', 'Eve', 'Alpha Omega Inc.', 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Ms.', 'Eve', 'Kay', 'Smith', 'thematriarch@gmail.com', null, 'Single', null, 'Alpha Omega, Inc.', 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Mr.', 'Erik', null, 'Weibust', 'original_gangsta@tamu.edu', null, 'Married', null, 'Credera', 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Mr.', 'Jonathan', null, 'Ball', 'hotchocolate01@yahoo.com', null, 'Married', null, 'Credera', 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Mr.', 'Ryan', null, 'Smith',  'grapples2apples@gmail.com', null, 'Single', null, 'Credera', 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Ms.', 'Jennifer', null, 'Stephenson', 'jstephenson@mpowersystems.com', null, 'Single', null, 'MPower Open', 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Mr.', 'Leo', null, 'D''Angelo', 'lDAngelo@mpowersystems.com', null, 'Married', null, 'MPower Open', 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Mr.', 'Vincent', null, 'Young', 'longhorn4life@utexas.edu', null, 'Single', null, 'The University of Texas at Austin', 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Mr.', 'Jack', null, 'Jones', 'mothergooserhymez@msn.com', null, 'Married', 'Jill', 'Mother Goose', 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Mrs.', 'Jill', null, 'Jones', 'tumbler@aol.com', null, 'Married', null, 'Mother Goose', 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Mr.', 'James', null, 'Hook', 'codfish@gmail.com', null, 'Unknown', null, null, 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Ms.', 'Jane', null, 'Porter', 'gorilla@gmail.com', null, 'Single', null, null, 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Mr.', 'Tarzan', null, 'Ape', 'ahauhaua@yahoo.com', null, 'Single', null, null, 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Mr.', 'Frodo', null, 'Baggins', 'ringbearer@gmail.com', null, 'Single', null, 'Fellowship', 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Ms.', 'Pam', null, 'Beesly', 'ilovejim@gmail.com', null, 'Single', null, 'Dunder Mifflin, Inc.', 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Mr.', 'Jim', null, 'Halpert', 'ilovepam@gmail.com', null, 'Single', null, 'Dunder Mifflin, Inc.', 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Ms.', 'Angela', null, 'Martin', 'kittycats@yahoo.com', null, 'Single', null, 'Dunder Mifflin, Inc.', 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Mrs.', 'Phyllis', null, 'Vance',  'pvance@gmail.com', null, 'Married', null, 'Dunder Mifflin, Inc.', 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Mr.', 'Bob', null, 'Vance', 'bvance@vancerefrigeration.com', null, 'Unknown', null, 'Vance Refrigeration', 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Mr.', 'Dwight', null, 'Schrute', 'bearsnbeets@yahoo.com', null, 'Single', null, 'Dunder Mifflin, Inc.', 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Ms.', 'Karen', null, 'Filippelli', 'kfilippelli@dmifflin.com', null, 'Single', null, 'Dunder Mifflin, Inc.', 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Mr.', 'Jack', null, 'Shephard', 'drj@msn.com', null, 'Single', null, 'ABC', 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Mr.', 'John', null, 'Locke', 'adventurer@aol.com', null, 'Single', null, 'ABC', 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Ms.', 'Kate', null, 'Austen', 'thefugitive@gmail.com', null, 'Unknown', null, 'ABC', 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Mr.', 'James', 'Sawyer', 'Ford', 'lonewolf@gmail.com', null, 'Single', null, 'ABC', 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Mrs.', 'Sun', null, 'Kwon', 'sunny@yahoo.com', null, 'Married', 'Jin', 'ABC', 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Mr.', 'Jin', null, 'Kwon', 'fisherman@yahoo.com', null, 'Married', 'Jin', 'ABC', 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Mr.', 'Homer', 'Jay', 'Simpson', 'doh@yahoo.com', null, 'Married', 'Marge', 'Fox', 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Mrs.', 'Marge', null, 'Simpson', 'bluetree@yahoo.com', null, 'Married', null, 'Fox', 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Mr.', 'Bob', null, 'Incredible', 'bigguy@yahoo.com', null, 'Married', null, 'Pixar', 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Mrs.', 'Helen', null, 'Incredible', 'mom@yahoo.com', null, 'Married', null, 'Pixar', 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Mr.', 'William', null, 'Fitzpatrick', 'gogreen@yahoo.com', null, 'Unknown', null, 'O''Reilly''s', 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Ms.', 'Mary', null, 'O''Doul', 'gogreener@yahoo.com', null, 'Widowed', null, 'O''Doul''s', 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Mr.', 'Tom', null, 'Sawyer', 'painter@yahoo.com', null, 'Single', null, null, 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Mr.', 'Huckleberry', null, 'Finn', 'livinfree@yahoo.com', null, 'Married', null, null, 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Ms.', 'Amy', null, 'Abbott', 'lady@yahoo.com', null, 'Married', 'Aaron', null, 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Mr.', 'Oliver', null, 'Twist', 'fictional@yahoo.com', null, 'Married', 'Nancy', null, 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Mr.', 'John', 'Doe', 'Kwon', 'plainojohn@yahoo.com', null, 'Married', null, null, 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Ms.', 'Jane', null, 'Doe', 'fisherman@yahoo.com', null, 'Single', null, null, 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Mr.', 'Colt', null, 'McCoy', 'hookem@utexas.edu', null, 'Single', null, 'The University of Texas at Austin', 1, false, false);
INSERT INTO PERSON (TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMAIL, SUFFIX, MARITAL_STATUS, SPOUSE_FIRST_NAME, ORGANIZATION_NAME, SITE_ID, MAJOR_DONOR, LAPSED_DONOR) VALUES ('Mr.', 'George', null, 'Washington', 'fisherman@yahoo.com', null, 'Married', null, 'USA', 1, false, false);