-- phoneSetup.sql contatins PHONE insertions and PERSON_PHONE cross references

-- Create phone number list
-- Must be executed BEFORE PERSON_PHONE insertions

INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2144436829, 'home');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2149116681, 'work');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2145480929, 'mobile');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2141056590, 'home');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2141299781, 'work');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2148781663, 'mobile');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2141132542, 'home');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2146423253, 'work');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2149189851, 'mobile');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2147561687, 'home');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2144871581, 'work');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2148202725, 'home');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2141222394, 'work');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2142368824, 'mobile');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2141649149, 'home');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2147981229, 'work');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2141859155, 'mobile');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2142878431, 'home');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2147319815, 'work');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2147876507, 'mobile');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2143083942, 'home');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2142449403, 'work');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2144428248, 'home');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2147056173, 'work');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2143089287, 'mobile');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2146305617, 'home');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2146142230, 'work');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2142623664, 'mobile');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2146042984, 'home');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2149779562, 'work');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2145560383, 'mobile');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2142571382, 'home');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2141133055, 'work');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2148702222, 'home');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2146203524, 'work');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2145926636, 'mobile');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2148291284, 'home');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2149453722, 'work');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2142279317, 'mobile');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2141116576, 'home');
INSERT INTO PHONE (NUMBER, PHONE_TYPE) VALUES (2148544211, 'work');

-- Create person/phone cross references
-- Must be executed AFTER:
	-- PERSON insertions (personSetup.sql) 
	-- PHONE insertions

INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (1, 1);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (2, 2);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (3, 3);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (4, 4);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (5, 5);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (6, 6);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (7, 7);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (8, 8);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (9, 9);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (10, 10);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (11, 11);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (12, 12);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (13, 13);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (14, 14);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (15, 15);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (16, 16);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (17, 17);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (18, 18);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (19, 19);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (20, 20);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (21, 21);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (22, 22);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (23, 23);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (24, 24);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (25, 25);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (26, 26);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (27, 27);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (28, 28);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (29, 29);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (30, 30);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (31, 31);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (32, 32);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (33, 33);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (34, 34);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (35, 35);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (36, 36);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (37, 37);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (38, 38);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (39, 39);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (40, 40);
INSERT INTO PERSON_PHONE (PERSON_ID, PHONE_ID) VALUES (41, 41);