// Rollup test
INSERT INTO CONSTITUENT (CONSTITUENT_ID, CONSTITUENT_TYPE, TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SUFFIX, MARITAL_STATUS, ORGANIZATION_NAME, SITE_NAME, CREATE_DATE, UPDATE_DATE) VALUES (100001, 'organization', null, null, null, null, null, 'Unknown', 'A1 Holding Company', 'company1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CONSTITUENT (CONSTITUENT_TYPE, TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SUFFIX, MARITAL_STATUS, ORGANIZATION_NAME, SITE_NAME, CREATE_DATE, UPDATE_DATE) VALUES ('organization', null, null, null, null, null, 'Unknown', 'B2 Conglomerate', 'company1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CONSTITUENT (CONSTITUENT_TYPE, TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SUFFIX, MARITAL_STATUS, ORGANIZATION_NAME, SITE_NAME, CREATE_DATE, UPDATE_DATE) VALUES ('organization', null, null, null, null, null, 'Unknown', 'B3 Conglomerate', 'company1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CONSTITUENT (CONSTITUENT_TYPE, TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SUFFIX, MARITAL_STATUS, ORGANIZATION_NAME, SITE_NAME, CREATE_DATE, UPDATE_DATE) VALUES ('organization', null, null, null, null, null, 'Unknown', 'B4 Conglomerate', 'company1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CONSTITUENT (CONSTITUENT_TYPE, TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SUFFIX, MARITAL_STATUS, ORGANIZATION_NAME, SITE_NAME, CREATE_DATE, UPDATE_DATE) VALUES ('organization', null, null, null, null, null, 'Unknown', 'C5 Corporation', 'company1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CONSTITUENT (CONSTITUENT_TYPE, TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SUFFIX, MARITAL_STATUS, ORGANIZATION_NAME, SITE_NAME, CREATE_DATE, UPDATE_DATE) VALUES ('organization', null, null, null, null, null, 'Unknown', 'C6 Corporation', 'company1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CONSTITUENT (CONSTITUENT_TYPE, TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SUFFIX, MARITAL_STATUS, ORGANIZATION_NAME, SITE_NAME, CREATE_DATE, UPDATE_DATE) VALUES ('organization', null, null, null, null, null, 'Unknown', 'C7 Corporation', 'company1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CONSTITUENT (CONSTITUENT_TYPE, TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SUFFIX, MARITAL_STATUS, ORGANIZATION_NAME, SITE_NAME, CREATE_DATE, UPDATE_DATE) VALUES ('organization', null, null, null, null, null, 'Unknown', 'D8 Company', 'company1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CONSTITUENT (CONSTITUENT_TYPE, TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SUFFIX, MARITAL_STATUS, ORGANIZATION_NAME, SITE_NAME, CREATE_DATE, UPDATE_DATE) VALUES ('organization', null, null, null, null, null, 'Unknown', 'D9 Company', 'company1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CONSTITUENT (CONSTITUENT_TYPE, TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SUFFIX, MARITAL_STATUS, ORGANIZATION_NAME, SITE_NAME, CREATE_DATE, UPDATE_DATE) VALUES ('organization', null, null, null, null, null, 'Unknown', 'D10 Company', 'company1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

UPDATE CONSTITUENT SET ACCOUNT_NUMBER=GENERATEID(SITE_NAME) WHERE ACCOUNT_NUMBER IS NULL;

// Level 1
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('organization.subsidiaryList','100002', 'constituent', 100001);
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('organization.subsidiaryList','100003', 'constituent', 100001);
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('organization.subsidiaryList','100004', 'constituent', 100001);


// Level 2
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('organization.parent','100001', 'constituent', 100002);
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('organization.subsidiaryList','100005', 'constituent', 100002);
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('organization.subsidiaryList','100006', 'constituent', 100002);

INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('organization.parent','100001', 'constituent', 100003);

INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('organization.parent','100001', 'constituent', 100004);

// Level 3

INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('organization.parent','100002', 'constituent', 100005);
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('organization.subsidiaryList','100008', 'constituent', 100005);
INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('organization.subsidiaryList','100009', 'constituent', 100005);

INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('organization.parent','100002', 'constituent', 100006);

INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('organization.parent','100003', 'constituent', 100007);

// Level 4

INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('organization.parent','100005', 'constituent', 100008);

INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('organization.parent','100005', 'constituent', 100009);

INSERT INTO CUSTOM_FIELD(FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES ('organization.parent','100007', 'constituent', 100010);

