// Rollup test
INSERT INTO CONSTITUENT (CONSTITUENT_ID, CONSTITUENT_TYPE, TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SUFFIX, MARITAL_STATUS, ORGANIZATION_NAME, SITE_NAME, CREATE_DATE, UPDATE_DATE) VALUES (100001, 'organization', null, null, null, null, null, 'Unknown', 'A1 Holding Company', 'company1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CONSTITUENT (CONSTITUENT_TYPE, TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SUFFIX, MARITAL_STATUS, ORGANIZATION_NAME, SITE_NAME, CREATE_DATE, UPDATE_DATE) VALUES ('organization', null, null, null, null, null, 'Unknown', 'B2 Conglomerate', 'company1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CONSTITUENT (CONSTITUENT_TYPE, TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SUFFIX, MARITAL_STATUS, ORGANIZATION_NAME, SITE_NAME, CREATE_DATE, UPDATE_DATE) VALUES ('organization', null, null, null, null, null, 'Unknown', 'B3 Conglomerate', 'company1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CONSTITUENT (CONSTITUENT_TYPE, TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SUFFIX, MARITAL_STATUS, ORGANIZATION_NAME, SITE_NAME, CREATE_DATE, UPDATE_DATE) VALUES ('organization', null, null, null, null, null, 'Unknown', 'B4 Conglomerate', 'company1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CONSTITUENT (CONSTITUENT_TYPE, TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SUFFIX, MARITAL_STATUS, ORGANIZATION_NAME, SITE_NAME, CREATE_DATE, UPDATE_DATE) VALUES ('organization', null, null, null, null, null, 'Unknown', 'C5 Corporation', 'company1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CONSTITUENT (CONSTITUENT_TYPE, TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SUFFIX, MARITAL_STATUS, ORGANIZATION_NAME, SITE_NAME, CREATE_DATE, UPDATE_DATE) VALUES ('organization', null, null, null, null, null, 'Unknown', 'C6 Corporation', 'company1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CONSTITUENT (CONSTITUENT_TYPE, TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SUFFIX, MARITAL_STATUS, ORGANIZATION_NAME, SITE_NAME, CREATE_DATE, UPDATE_DATE) VALUES ('organization', null, null, null, null, null, 'Unknown', 'C7 Corporation', 'company1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CONSTITUENT (CONSTITUENT_TYPE, TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SUFFIX, MARITAL_STATUS, ORGANIZATION_NAME, SITE_NAME, CREATE_DATE, UPDATE_DATE) VALUES ('organization', null, null, null, null, null, 'Unknown', 'D8 Company', 'company1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CONSTITUENT (CONSTITUENT_TYPE, TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SUFFIX, MARITAL_STATUS, ORGANIZATION_NAME, SITE_NAME, CREATE_DATE, UPDATE_DATE) VALUES ('organization', null, null, null, null, null, 'Unknown', 'D9 Company', 'company1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CONSTITUENT (CONSTITUENT_TYPE, TITLE, FIRST_NAME, MIDDLE_NAME, LAST_NAME, SUFFIX, MARITAL_STATUS, ORGANIZATION_NAME, SITE_NAME, CREATE_DATE, UPDATE_DATE) VALUES ('organization', null, null, null, null, null, 'Unknown', 'D10 Company', 'company1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


// Level 1
INSERT INTO CUSTOM_FIELD(CUSTOM_FIELD_ID, FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES (1, 'organization.parent','', 'person', 100001);
INSERT INTO CUSTOM_FIELD(CUSTOM_FIELD_ID, FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES (2, 'organization.subsidiaryList','100002,100003,100004', 'person', 100001);


// Level 2
INSERT INTO CUSTOM_FIELD(CUSTOM_FIELD_ID, FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES (3, 'organization.parent','100001', 'person', 100002);
INSERT INTO CUSTOM_FIELD(CUSTOM_FIELD_ID, FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES (4, 'organization.subsidiaryList','100005,100006', 'person', 100001);

INSERT INTO CUSTOM_FIELD(CUSTOM_FIELD_ID, FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES (5, 'organization.parent','100001', 'person', 100003);
INSERT INTO CUSTOM_FIELD(CUSTOM_FIELD_ID, FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES (6, 'organization.subsidiaryList','100007', 'person', 100003);

INSERT INTO CUSTOM_FIELD(CUSTOM_FIELD_ID, FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES (7, 'organization.parent','100001', 'person', 100004);
INSERT INTO CUSTOM_FIELD(CUSTOM_FIELD_ID, FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES (8, 'organization.subsidiaryList','', 'person', 100004);

// Level 3

INSERT INTO CUSTOM_FIELD(CUSTOM_FIELD_ID, FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES (9, 'organization.parent','100002', 'person', 100005);
INSERT INTO CUSTOM_FIELD(CUSTOM_FIELD_ID, FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES (10, 'organization.subsidiaryList','100008,100009', 'person', 100005);

INSERT INTO CUSTOM_FIELD(CUSTOM_FIELD_ID, FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES (11, 'organization.parent','100002', 'person', 100006);
INSERT INTO CUSTOM_FIELD(CUSTOM_FIELD_ID, FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES (12, 'organization.subsidiaryList','', 'person', 100006);

INSERT INTO CUSTOM_FIELD(CUSTOM_FIELD_ID, FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES (13, 'organization.parent','100003', 'person', 100007);
INSERT INTO CUSTOM_FIELD(CUSTOM_FIELD_ID, FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES (14, 'organization.subsidiaryList','100010', 'person', 100007);

// Level 4

INSERT INTO CUSTOM_FIELD(CUSTOM_FIELD_ID, FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES (15, 'organization.parent','100005', 'person', 100008);
INSERT INTO CUSTOM_FIELD(CUSTOM_FIELD_ID, FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES (16, 'organization.subsidiaryList','', 'person', 100008);

INSERT INTO CUSTOM_FIELD(CUSTOM_FIELD_ID, FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES (17, 'organization.parent','100005', 'person', 100009);
INSERT INTO CUSTOM_FIELD(CUSTOM_FIELD_ID, FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES (18, 'organization.subsidiaryList','', 'person', 100009);

INSERT INTO CUSTOM_FIELD(CUSTOM_FIELD_ID, FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES (19, 'organization.parent','100007', 'person', 100010);
INSERT INTO CUSTOM_FIELD(CUSTOM_FIELD_ID, FIELD_NAME, FIELD_VALUE, ENTITY_TYPE, ENTITY_ID) VALUES (20, 'organization.subsidiaryList','', 'person', 100010);

