-- Create two new sites company1 and company2

INSERT INTO SITE (SITE_NAME, PARENT_SITE_NAME, CREATE_DATE, UPDATE_DATE) VALUES ('company1', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO SITE (SITE_NAME, PARENT_SITE_NAME, CREATE_DATE, UPDATE_DATE) VALUES ('company2', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);