-- Create a new site crederaDev

INSERT INTO SITE (SITE_ID, SITE_NAME, PARENT_SITE_ID) VALUES (1, 'CrederaDev', NULL);

INSERT INTO SITE (SITE_ID, SITE_NAME, PARENT_SITE_ID) VALUES (2, 'company1', NULL);