-- Create a new user
-- Creating a new user must come BEFORE creating user roles

INSERT INTO MPOWER_USER (USER_NAME, SITE_ID) VALUES ('rod', 2);
INSERT INTO MPOWER_USER (USER_NAME, SITE_ID) VALUES ('dianne', 2);
INSERT INTO MPOWER_USER (USER_NAME, SITE_ID) VALUES ('scott', 2);

INSERT INTO MPOWER_USER (USER_NAME, SITE_ID) VALUES ('jack', 3);
INSERT INTO MPOWER_USER (USER_NAME, SITE_ID) VALUES ('locke', 3);
INSERT INTO MPOWER_USER (USER_NAME, SITE_ID) VALUES ('hurley', 3);
